### ISSUE TITLE
Dashboard showing empty state even when AWS have been setup

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#100]
**Describe the bug**
If you open your browser in Incognito or Private mode and go to the dashboard you will always be presented with the empty state for the dashboard. If AWS accounts have been configured and you refresh the browser you will then be able to view the dashboard widgets.

**To Reproduce**
1. Go to the dashboard in Incognito or Private browsing
2. Login to the app
3. See empty state even when AWS accounts have been previously configured
4. Refresh browser and you will see the dashboard widgets.

**Expected behavior**
You should only see the empty state if no AWS accounts have been configured otherwise you should see the dashboard widgets.

**Screenshots**
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/29379759/45097758-8c2a7600-b0f1-11e8-8236-bceb20b9c6cd.png">

**Comment by chambridge** [comment]
@dlabrecq FYI^

**Comment by dlabrecq** [comment]
Yes, I've also seen this. It can take some time before the dashboard is populated with data. If the UI cannot obtain a list of providers, upon login, the empty state is shown instead.
