### ISSUE TITLE
PF4 tab warning messages

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1013]
**Describe the bug**
PatternFly tabs are generating a warning message for a missing, required title property.

**To Reproduce**
1. Go to 'overview'
2. See error

**Expected behavior**
Don't want to see warnings in the browser console.

**Screenshots**
![Screen Shot 2019-09-24 at 1 13 03 PM](https://user-images.githubusercontent.com/17481322/65538311-0c767180-ded5-11e9-85d2-a51ef9d6002a.png)

**Comment by boaz0** [comment]
@dlabrecq I had this issue too on cost models page and adding title didn't fix it.
I think it's related to patternfly 4. If you don't mind - assign it to me.

**Comment by dlabrecq** [comment]
This may be a PatternFly issue. We're already setting `title` for the Tab component. We're not even using `TabContainer` directly.

**Comment by dlabrecq** [comment]
Created this issue with PatternFly https://github.com/patternfly/patternfly-react/issues/3006

**Comment by dlabrecq** [comment]
This should be fixed by https://github.com/patternfly/patternfly-react/pull/3031

Will update PatternFly via https://github.com/project-koku/koku-ui/pull/1031

**Comment by dlabrecq** [comment]
This has been fixed with the latest PatternFly update
