### ISSUE TITLE
Cost model: Invalid prop message

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1034]
The cost model table is generating the following warning message in the browser console.

![Screen Shot 2019-09-30 at 11 07 44 AM](https://user-images.githubusercontent.com/17481322/65892357-24863f00-e374-11e9-83a5-a2c277ec314f.png)

**Comment by boaz0** [comment]
I don't see this problem any more, I assume it was fixed in #1014

**Comment by boaz0** [comment]
Feel to reopen it if you see this error again.
Thanks @dlabrecq
