### ISSUE TITLE
Cost models fit & finish: create cost model - price list sub step - view rates

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1041]
**Describe the bug**
Fit and finish to the sub step in create cost model wizard - view rates

**Expected behavior**
- [x] Space between title-description section and table-filter part
- [x] Use "Remove" instead of "Delete" in the action button
- [x] Add pagination with 2, 4 and 6 items per page
- [x] Add search icon in the filter input

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/66131400-0894ce80-e5fc-11e9-9750-93216a558ace.png)

**Comment by dlabrecq** [comment]
I suspect this is in progress; thus, adding Sprint 33 as the milestone and epic (for QE to test)
