### ISSUE TITLE
Cost models fit & finish: create cost model - markup

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1042]
**Describe the bug**

Fit and finish to the markup step in create cost model wizard.

**Expected behavior**

- [x] Percent icon next to the input
- [x] Length of the input field should be at least 340px
- [x] Placeholder should be set
- [x] Remove the asterisk 

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/66133164-df297200-e5fe-11e9-91bd-0c3c731d0b53.png)

**Comment by dlabrecq** [comment]
I suspect this is in progress; thus, adding Sprint 33 as the milestone and epic (for QE to test)
