### ISSUE TITLE
Add source modal has incomplete commands for crontab

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1052]
**Describe the bug**
Add source modal has incomplete commands for crontab

**To Reproduce**
1. Go to 'Add a source'
2. Click through setting up ocp provider
3. See Configure data collection screen
4. Commands on this step are missing some items

**Expected behavior**
`crontab -u <username> -e`

` */45 * * * * /path/to/ocp_usage.sh --collect --e OCP_CLUSTER_ID=<YOUR_OCP_IDENTIFIER>`

**Screenshots**
![Screenshot from 2019-10-09 20-40-14](https://user-images.githubusercontent.com/18352403/66551885-3ae48580-eb40-11e9-8a2f-92d0821a3790.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 77

**Additional context**
Seeing this issue on CI beta

**Comment by boaz0** [comment]
@dayleparker can you confirm?
thanks.

**Comment by dayleparker** [comment]
I just checked the onboarding doc and we are missing the part of the second command, so I've added it now too:

--e OCP_CLUSTER_ID=<YOUR_OCP_IDENTIFIER>

**Comment by lcouzens** [comment]
@dayleparker 
This is still not % correct.. We should be pulling the cluster identifier from the wizard flow. 
We set the ID on the previous page so should display that in the copy command line. See screenshots, 

![Screenshot from 2019-10-25 14-54-21.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/ab5d0222-1510-4b66-becd-bcdd85374038)
![Screenshot from 2019-10-25 14-54-27.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/78086199-16c3-4b84-9b7a-2014ac226f63)

It's also strange that we copy to clipboard the command without the real username `crontab -u <username> -e` maybe we should just not have the copy to clipboard link on this one?

**Comment by boaz0** [comment]
@lcouzens closing this in favor of #1070
