### ISSUE TITLE
Azure overview bar percentages

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1058]
**Describe the bug**
Cards in Azure overview display usage totals and percentages as 0 even though there are line items displayed.

**To Reproduce**
1. Go to Azure overview
2. See error

**Expected behavior**
Correct numbers in the cards, similar to other overview pages

**Screenshots**
![Screenshot from 2019-10-11 12-58-29](https://user-images.githubusercontent.com/46324552/66647030-1532ab80-ec28-11e9-85b5-e88d5285915d.png)

**Desktop (please complete the following information):**
 - OS: rhel
 - Browser chrome
 - Version 75

**Additional context**
tested on CI beta

**Comment by dlabrecq** [comment]
Currently, the Azure instance-types API returns a single property for meta total usage, where we typically expect value and units.

See https://github.com/project-koku/koku/issues/1387
