### ISSUE TITLE
Refreshing details page navigates to Cost Management Overview

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1072]
**Describe the bug**
After refreshing the page in any of the details (OCP, OCP on AWS, Cloud), the UI takes us to the Overview. 

**To Reproduce**
1. Log in, navigate to Cost Management
2. Click on Cloud details
3. Refresh the page

**Expected behavior**
After the refresh, we don't get to overview

**Desktop (please complete the following information):**
 - OS: Rhel
 - Browser Chrome 

**Additional context**
If we navigate back to a details page and refresh again, we don't get to overview completely, but the side navigation shows "Overview" as the selected item.

Tested on CI Beta

**Comment by boaz0** [comment]
Yes, I do notice this odd thing. My guess it's related to moving from `hybrid`. I will look at it tomorrow.

Thanks.

**Comment by boaz0** [comment]
fixed in https://github.com/project-koku/koku-ui/pull/1074

//cc @dchorvat1 feel free to test.

**Comment by dchorvat1** [comment]
@boaz0 the page now stays on the page after refresh, but the side navigation shows "Overview"
![Screenshot from 2019-11-04 13-54-52](https://user-images.githubusercontent.com/46324552/68122863-afc29980-ff0b-11e9-9f09-b9e21b368394.png)

**Comment by boaz0** [comment]
Hi @dchorvat1 I see. This is going to be addressed in https://github.com/RedHatInsights/insights-chrome/pull/434
