### ISSUE TITLE
Typos in cost model wizard

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1077]
**Describe the bug**
There are some minor typos in cost model wizard
("precentage", "posotive" in markup step, "tthe" in sources)

**To Reproduce**
1. Go to Cost model details
2. Go through the wizard
3. See error

**Expected behavior**
No typos

**Screenshots**
![Screenshot from 2019-11-06 11-18-58](https://user-images.githubusercontent.com/46324552/68318295-d4aa3e80-00bc-11ea-8bf6-02284a7402ed.png)
![Screenshot from 2019-11-06 11-19-57](https://user-images.githubusercontent.com/46324552/68318389-01f6ec80-00bd-11ea-927c-c5d2fe5d4ca3.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser Firefox
 - Version 70

**Additional context**
Tested on CI beta

**Comment by boaz0** [comment]
Thanks.

**Comment by dchorvat1** [comment]
![Screenshot from 2019-11-13 14-26-18](https://user-images.githubusercontent.com/46324552/68767825-af1fb680-0621-11ea-8615-23b90d0caa4f.png)
There's also a typo in markup tab in cost model details
