### ISSUE TITLE
Azure: Units

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1079]
The Azure cards; Virtual machines & storage, do not show units

![Screen Shot 2019-11-08 at 3 37 24 PM](https://user-images.githubusercontent.com/17481322/68508979-de0ee480-023d-11ea-867f-82827511c89f.png)

**Comment by ddonahue007** [comment]
We will be adding a work-around for the below. According to this bug Azure is not passing back proper unit values.

[ISSUE-#1360](https://github.com/project-koku/koku/issues/1360)
