### ISSUE TITLE
RFE for UI HCCM/AWS heath check/current status

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#112]
We should consider adding a monitor for Cost and sources (AWS, Azure, OCP) so we can see current status, basically being able to quickly tell if cost management has stale data and what time stamp the last data was collected on.

**Comment by chargio** [comment]
Thanks for contributing and welcome to the community.

Yes, it looks like a good idea

**Comment by nlcwong** [comment]
I've seen designs for the Sources UI that shows a list of sources (aka providers) and their status, so maybe that is what we can hitch onto?

**Comment by chargio** [comment]
If Sources UI is already providing this, I am ok with that design. We don't need to replicate use cases and functionality.

**Comment by nlcwong** [comment]
I'm going to keep this open until Sources deliver with support for cost.  Until then, keeping this open as a reminder.

**Comment by dlabrecq** [comment]
Decided we will not to port this issue to Jira.
