### ISSUE TITLE
Charts are not using correct data

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#114]
Charts should use the API for monthly data, while "top services", "top accounts", and "top regions" should use an API for daily data. Instead of seeing several (9+) services, the daily data should be limited to the top 5 most used. 

Some investigation is needed, but it's suspected that "top services" may be using the same API used to create the monthly chart?

<img width="959" alt="screen shot 2018-09-12 at 2 21 05 pm" src="https://user-images.githubusercontent.com/17481322/45445196-8efc0c80-b697-11e8-9b87-c9806c1968c8.png">

**Comment by boaz1337** [comment]
@dlabrecq @chambridge can I work on this?

**Comment by chambridge** [comment]
@boaz1337 fine with me!
