### ISSUE TITLE
Cost models description should be held in a pop up link similar to overview

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1141]
**Describe the bug**
Cost models description should be held in a pop up link similar to overview

**To Reproduce**
1. Go to 'Cost models'
2. See description below title

**Expected behavior**
This description should probably sit in a pop up similar to what we have on the overview page

**Screenshots**
![Screenshot from 2019-12-10 15-07-33.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/c16b3232-3440-4494-84fc-7b01f0e02101)

**Desktop (please complete the following information):**
  - OS: Fedora
  - Browser Firefox
  - Version 70

**Additional context**
Noticed this testing against CI Beta

**Comment by boaz0** [comment]
@nlcwong - in the mock I don't remember seeing popover to display the description. Is this necessary here?

**Comment by boaz0** [comment]
Spoke with @nlcwong and it was one of the things we had to take care of in the "fit and finish" phase.
I will be working on this today.

Thanks for your ticket.
