### ISSUE TITLE
Cluster infomation missing from project/node views in openshift details

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1144]
**Describe the bug**
Cluster infomation missing from project/node views in openshift details

**To Reproduce**
1. Add/ingest openshift provider
2. Go to 'Openshift details'
3. Group cost by project or node
4. Expand a row in the list
4. See cluster information is blank

**Expected behavior**
If we show `Cluster:` we should have the relevant information listed.

**Screenshots**
![Screenshot from 2019-12-10 14-58-35.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/c8cea630-5cdc-4adf-a1ae-284039f94b3d)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Additional context**
Testing against CI Beta

**Comment by dlabrecq** [comment]
The cluster name appears to be missing from the APIs. I created an issue with koku instead

https://github.com/project-koku/koku/issues/1536
