### ISSUE TITLE
Cost models view have no ability to sort asc/desc

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1149]
**Describe the bug**
Cost models view have no ability to sort asc/desc

**To Reproduce**
1. Go to 'cost models'
2. Create a bunch of cost models
3. See there is no table ability to sort created cost models

**Expected behavior**
We should provider some basic table sorting functionality similar to that on the details pages

**Screenshots**
![Screenshot from 2019-12-10 15-58-53.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/0c67893a-7492-4d4b-8238-02d63ac92dad)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Additional context**
Testing against CI beta

**Comment by boaz0** [comment]
@adberglund is this possible in the back-end. Both looking at the OpenAPI and did trial & error but couldn't work it out.

**Comment by boaz0** [comment]
OK, after investigating, `Koku` supports sorting by update_timestamp, name and source type, I will work on it next sprint probably.
