### ISSUE TITLE
Cost models are not sorted in a sensible order

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1150]
**Describe the bug**
Cost models are not sorted in a sensible order

**To Reproduce**
1. Go to 'Cost models'
2. Create a bunch of cost models
3. See creation times

**Expected behavior**
Cost models should be sorted by last modified asc by default 

**Screenshots**
![Screenshot from 2019-12-10 15-58-53.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/1e79653e-077c-4717-a8af-29c96e7838e4)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Additional context**
Testing against CI beta, see Jens account

**Comment by boaz0** [comment]
This is related to back-end I believe
@adberglund

**Comment by nlcwong** [comment]
The behavior should be that the user would be able to sort any of the columns in the table with a default set to "Name" as the thing that sorts the first time A->Z

**Comment by boaz0** [comment]
Looking at Koku - it looks like this is already supported.
https://github.com/project-koku/koku/blob/master/koku/cost_models/view.py#L122-L123
So I am confused why you didn't see the cost models sorted by name.

**Comment by boaz0** [comment]
I'm closing this as this is not really related to the UI. The order of the results is coming from the backend. Moreover, looking at the CI environment, it seems like working
