### ISSUE TITLE
User is forced to enter a markup value when they may not want one

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1159]
**Describe the bug**
User is forced to enter a markup value when they may not want one

**To Reproduce**
1. Go to 'cost models'
2. Click on 'Add new cost model'
3. Fill in name type
4. Cost markup screen requires a value before you can click next

**Expected behavior**
We really should set the default to 0 so the user can continue without needing to input 0 manually.

**Screenshots**
![Screenshot from 2019-12-11 11-47-40.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/4f99465a-d305-4726-b871-3c08e76d9ef5)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Additional context**
Testing against CI beta

The current flow requires you to add a markup value even if that value is 0. Problem is if you need to add lots of cost models without markup values it could become annoying needing to supply that 0 value every time. Also we already display a default value of 0 but its greyed out and blocks the next button.

**Comment by chargio** [comment]
It would be great to be able to continue without adding explicitly the 0%.

**Comment by boaz0** [comment]
@chargio - should the markup step be optional too?

**Comment by chargio** [comment]
Yes

Sergio Ocón-Cárdenas

Product Manager, Cost Management

Red Hat <https://www.redhat.com/>

sergio.ocon@redhat.com
M: +34-692058130
<https://www.redhat.com/>
