### ISSUE TITLE
Add node_cost_per_month to cost models UI. 

### ISSUE THREAD

**Issue by werwty** [project-koku/koku-ui#1169]
## User Story
As a Koku customer, I want to see my billing cost for OCP usage as my configured $X/month/node.

This is the UI component of https://github.com/project-koku/koku/issues/1238

## Impacts
UI

## Assumptions
- API changes are already in place, a sample API call to add the node_cost_per_month looks like 

```
http POST 0.0.0.0:8000/api/cost-management/v1/costmodels/ name='testCost' source_type='OCP' description='node-cost' \
provider_uuids:='["83b4fe56-df0d-47b3-a8f3-eb820526ebbf"]' \
rates:='[{"metric": { "name": "node_cost_per_month", "unit": "node-month", "display_name": "Compute Node Rate"}, "tiered_rates": [{ "value": 200, "unit": "USD"}]}]'
```
-

## UI Details
Changes should probably be in this page, Cost per Node should be added to the dropdown
![image](https://user-images.githubusercontent.com/6206134/71027614-97809580-20d9-11ea-982b-806d4a79b80e.png)

## Acceptance Criteria

- [ ] Cost per Node added to the price list metric for OCP
- [ ]

**Comment by boaz0** [comment]
Thank you so much @werwty 
I will be working on this, probably next sprint.
