### ISSUE TITLE
Integrate with Insights UI and enable local development utilizing Insights Proxy

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#118]
## User Story
As a UI developer, I want to be able to simulate access to the cost management UI via the Insights Platform API Gateway

## Impacts
UI, API, Docs

## Role
UI Developer / Service Developer / Quality Engineer

## Assumptions
- Insights provides proxy that allows for local development
- Insights provides Fake Akamai for staging deployment
- API Gateway will provide a Principal and Account information
- If our endpoints are reached we assume the Principal has been authenticated

## UI Details

- Update UI application to fit into Insights Starter Application flow with masthead and nav provided by Insights UI template
- On-boarding data [Front-end Starter](https://docs.google.com/document/d/1eSmZ2sswtf7gi5kB1EbSMtG8y--mL2Kc80u_I978KvQ/edit#heading=h.f645foq8xr29)
- Provide documentation for how to run with Insights UI Proxy for local development

## Acceptance Criteria

- [ ] Verify that Cost Management UI is available via Insights UI from the proxy view.

**Comment by chambridge** [comment]
https://github.com/project-koku/koku/pull/380
https://github.com/project-koku/masu/pull/215
https://github.com/project-koku/koku-ui/pull/139

**Comment by dlabrecq** [comment]
The PRs above have all been merged -- closing
