### ISSUE TITLE
Get price list rates' metrics and measurements from server

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1213]
## User Story
As a developer, I want to get metrics and measurements for rates so that I won't need to update UI any time a new metric or measurement is added on the backend.

## Impacts
UI
## Acceptance Criteria

- [ ] Get metrics and measurements from `api/v1/metrics`

**Comment by dlabrecq** [comment]
Is this an API that has yet to be created? Perhaps this issue should be moved to koku?

**Comment by dlabrecq** [comment]
Does this require a change to the backend API? Perhaps this should be moved to koku?

**Comment by boaz0** [comment]
The backend API has this under `/api/v1/metrics`. It's just no body updated me/us that it exists.
