### ISSUE TITLE
Cluster free space

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1214]
Added functionality to the Ocp details to show the free space of clusters (i.e., what is not being used).

The following special use cases are handled regarding requests. Natalie and I want to confirm that the data shown is expected? In particular, what we're showing for percentages (e.g., "117% of capacity").

1. More requests than capacity
2. Requests equal capacity
3. Zero requests

**More requests than capacity**
<img width="571" alt="Screen Shot 2020-01-03 at 5 13 55 PM" src="https://user-images.githubusercontent.com/17481322/71753875-f6703980-2e51-11ea-9c41-c2594afb90fd.png">

**Requests equal capacity**
<img width="545" alt="Screen Shot 2020-01-03 at 6 21 15 PM" src="https://user-images.githubusercontent.com/17481322/71754812-e3f7ff00-2e55-11ea-81b7-b7d069415206.png">

**Zero requests**
<img width="575" alt="Screen Shot 2020-01-03 at 5 14 47 PM" src="https://user-images.githubusercontent.com/17481322/71752900-dbe89100-2e4e-11ea-9501-bc22dd33b438.png">

@chargio @nlcwong @chambridge 

Mockup: https://marvelapp.com/1jj511j6/screen/64401384

**Comment by nlcwong** [comment]
The percentage, i assumed that the calculation of that is (capacity-requests)/capacity, but in the case of when requests goes beyond capacity, I'm thinking that we show negative numbers, so if capacity is 500 and requests is 700, then its -200 with an "-40% of capacity" or maybe state that is "40% overage in capacity".
