### ISSUE TITLE
Ocp Cloud Details: PF data toolbar

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1217]
Replace existing PatternFly toolbar, on the details pages, with the experimental PatternFly data toolbar. The PF data toolbar follows the latest PatternFly design pattern, which includes new icons, chip layout, etc.

See https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#attribute-value-textbox-filters

Filterable table example: https://patternfly-react.surge.sh/patternfly-4/documentation/react/demos/filtertabledemo

Data toolbar example: https://patternfly-react.surge.sh/patternfly-4/documentation/react/experimental/datatoolbar

<img width="1524" alt="Screen Shot 2020-01-10 at 10 11 00 PM" src="https://user-images.githubusercontent.com/17481322/72198016-1bd2e980-33f6-11ea-9e02-711c69179813.png">

**Comment by dlabrecq** [comment]
For reference, below are the known issues I encountered with PatternFly's data toolbar.

https://github.com/patternfly/patternfly-react/issues/3574
https://github.com/patternfly/patternfly-react/issues/3565
https://github.com/patternfly/patternfly-react/issues/3563
https://github.com/patternfly/patternfly-react/issues/3554
https://github.com/patternfly/patternfly-react/issues/3553
https://github.com/patternfly/patternfly-react/issues/3552
https://github.com/patternfly/patternfly-react/issues/3586

**Comment by dchorvat1** [comment]
verified, c2e1fe0662a7ec9f0781a913531373ee4f32fdae
