### ISSUE TITLE
Ocp cloud details: Update path

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1230]
Update URL from "/ocp-on-aws" to "/ocp-cloud"

Depends on https://github.com/project-koku/koku-ui/issues/1177
See https://github.com/RedHatInsights/cloud-services-config/pull/108

**Comment by boaz0** [comment]
Closing:

- https://github.com/RedHatInsights/cloud-services-config/pull/108 was merged
- changes are in https://ci.cloud.redhat.com/beta/cost-management

Thanks. 

![](https://media.giphy.com/media/5qpYb3R5JRES4/giphy.gif)
