### ISSUE TITLE
"View all tags" title does not fit into the dialog

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1239]
**Describe the bug**
In case of an account with a long name, the dialog title does not get fully displayed (as shown in the screenshot)
#1185 also states that we should display the title as `<account name> related tags` instead of `Account <account name>'s related tags`

**To Reproduce**
1. Go to Cloud details
2. Click on kebab button, view all tags
3. See error

**Expected behavior**
Title displayed correctly 

**Screenshots**
![Screenshot from 2020-01-14 13-18-35](https://user-images.githubusercontent.com/46324552/72344332-3f858080-36d1-11ea-8527-02b310860504.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
Tested on CI beta

**Comment by dlabrecq** [comment]
PatternFly automatically truncates long titles. According to @nwong, PatternFly should display the truncated title as a tooltip. That is, considering PatternFly is automatically truncating.

That said, I've filed the PatternFly issue below.
https://github.com/patternfly/patternfly-react/issues/3503

**Comment by dlabrecq** [comment]
The title at 50% window width.

![Screen Shot 2020-01-14 at 9.14.58 AM.png](https://images.zenhubusercontent.com/5b47705f01db7d22de6439cd/da8da307-eae4-420e-86a3-6a89251d55f1)
