### ISSUE TITLE
Rework sources flow to accommodate expert user

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#1249]
## User Story
- As a novice user, I want a detailed explanation on how to configure my AWS and/or Azure instance to collect cost and OpenShift cluster's usage report and/or metering usage report 
- As an expert user, I want a reminder on how to configure my AWS and/or Azure instance to collect cost and OpenShift cluster's usage report and/or metering usage report

## Impacts
- UI
- Docs

## Role
Cost source administrator (is that a thing?)

## Assumptions
- Novice user would need more hand holding
- Expert user would not need any documentation as they have done this so many times, that all they need to do is fill in the blanks which they can easily recall/obtain/copy from AWS instance.

## UI Details
If the user is a novice with setting up cost and usage reports in AWS, Azure, or metering reports in OpenShift, we should provide a link to the official cost management documentation that would provide detailed (e.g. step by step) information and for the wizard flow, we would provide short hints on what is expected to remind expert users what is needed in the form fields.

## Acceptance Criteria
- [ ] 
- [ ]

**Comment by dlabrecq** [comment]
Decided we will not to port this issue to Jira.
