### ISSUE TITLE
Kebab option misplaced when description is too long

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1257]
**Describe the bug**
In the cost model details page if the description is too long, the kebab option is placed under the tags while it is supposed to be on the right corner.

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'The true cost of a potato? I have no idea.'
3. See error

![image](https://user-images.githubusercontent.com/2453279/72683965-21f75300-3ae5-11ea-9289-0486151c08c8.png)

**Expected behavior**
The kebab option should stay on the right corner.

![image](https://user-images.githubusercontent.com/2453279/72684054-fc1e7e00-3ae5-11ea-8115-64a9a28f5d1b.png)

**Comment by dchorvat1** [comment]
@boaz0 
In case of a description without spaces, the kebab button goes out of page bounds, see screenshot
![Screenshot from 2020-01-27 14-49-42](https://user-images.githubusercontent.com/46324552/73179897-91d49180-4114-11ea-8bc9-000905630e1b.png)

**Comment by boaz0** [comment]
This looks like a bug in patternfly.

Do you mind opening a new ticket for this bug?
Thanks.

**Comment by dchorvat1** [comment]
https://github.com/patternfly/patternfly-react/issues/3598

**Comment by boaz0** [comment]
Thanks a lot @dchorvat1
