### ISSUE TITLE
Ocp Cloud Details: Add dropdown for tag key values

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1261]
When filtering by tags, in the details pages, we want to replace the existing input text filed with a drop down containing the available tag key values.

In a future update, we will use the PatternFly data toolbar to select multiple values.

Note that the text field below is showing previously entered values, it's not a dropdown
![Screen Shot 2020-01-20 at 10 24 50 AM](https://user-images.githubusercontent.com/17481322/72738348-5f082780-3b6f-11ea-897c-84b405abbc14.png)

**Comment by dlabrecq** [comment]
For reference, below are known issues I encountered with the PatternFly data toolbar.

https://github.com/patternfly/patternfly-react/issues/3574
https://github.com/patternfly/patternfly-react/issues/3565
https://github.com/patternfly/patternfly-react/issues/3563
https://github.com/patternfly/patternfly-react/issues/3554
https://github.com/patternfly/patternfly-react/issues/3553
https://github.com/patternfly/patternfly-react/issues/3552

**Comment by dlabrecq** [comment]
This functionality is included with PR https://github.com/project-koku/koku-ui/pull/1270

**Comment by dchorvat1** [comment]
Using the dropdown currently results in a page crash. (API returns 500)
Raised a bug here: https://github.com/project-koku/koku/issues/1647

**Comment by dlabrecq** [comment]
Yes, this is a known issue. See https://github.com/project-koku/koku/issues/1589
