### ISSUE TITLE
Details: no data available text

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1262]
When the "month over month change" delta is null, we want to show "No data available for 1-20 Dec", instead of "$0.00 for 1-20 Dec".

This would look similar to:
![Screen Shot 2020-01-20 at 11 46 15 AM](https://user-images.githubusercontent.com/17481322/72744037-cc6d8580-3b7a-11ea-9a9f-827ce84038a7.png)

Note that the delta percentage currently returns null, but delta value does not.
See https://github.com/project-koku/koku/issues/1395

**Comment by dchorvat1** [comment]
Verified, 05ff1b5ffc73dc37254a6d4348cac18f3fdc155d
