### ISSUE TITLE
[create cost model wizard] Allow user to go back to price list table

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1266]
## User Story

As a user, I want to be able to go to price list table (when there is at least one rate) so that I won't have to create a new rate.

## Impacts
UI

## Acceptance Criteria

- [x] Show the "Cancel" button when adding additional rate.
- [x] Change the "Save rate" button text to "Add rate"
- [x] Make "Add rate" and "Cancel" next to each other

**Comment by lcouzens** [comment]
Verified
