### ISSUE TITLE
Cost model wizard: selecting source w/o cost model shows a warning message

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1274]
**Describe the bug**
In the Assign source(s) step, when selecting a source that already has a cost model a warning triangle should be shown. However, if a source has the "Default" cost model, no warnings should be given.

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'Create cost model'
3. Fill information
4. Get to Assign source(s)
5. Select a source that is assigned to "Default cost model"

**Expected behavior**
No warning messages when selecting a source that is assigned to "Default cost model"

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/73173864-073d6380-410f-11ea-9774-ca66a3edb625.png)

**Comment by dchorvat1** [comment]
Verified, 948ddf7f311ee405a1723a00ca7c3eb81b5894bc
