### ISSUE TITLE
Remove AWS prefix

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1283]
Considering the Ocp cloud infrastructure details page now includes AWS and Azure, we should remove the AWS prefix from the component below.

![Screen Shot 2020-01-28 at 4 54 18 PM](https://user-images.githubusercontent.com/17481322/73308792-08de5880-41ef-11ea-99e0-6d5ac10f336e.png)

**Comment by dchorvat1** [comment]
verified, c9e8b13abe99720621407871a6268422044354d9
