### ISSUE TITLE
Bullet chart: Invalid prop domain

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1284]
Seeing an "invalid prop `domain`" error with bullet chart when grouping by tag. I believe this is happening when all values are zero. When expanding the others category (e.g., "no-app").

![Screen Shot 2020-01-28 at 6 11 42 PM](https://user-images.githubusercontent.com/17481322/73313643-c8d0a300-41f9-11ea-9f5c-2d9b5b1b861d.png)

![Screen Shot 2020-01-28 at 6 12 52 PM](https://user-images.githubusercontent.com/17481322/73313663-d1c17480-41f9-11ea-89dd-0188dff4b7e1.png)

**Comment by dchorvat1** [comment]
verified, c9e8b13abe99720621407871a6268422044354d9
