### ISSUE TITLE
Make data toolbar more generic

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1290]
Want to make the details data toolbar more generic so it can (possibly) be used in pages other than details. 

- Syncing groupBy with selected category options should be optional
- The export icon should be optional
- Filtering by tags should be optional
- Options should not be localized inside the data toolbar
- Restoring chip state based on filter_by query params should be optional
- The category options should be optional

**Comment by dchorvat1** [comment]
verified, c9e8b13abe99720621407871a6268422044354d9
