### ISSUE TITLE
Data toolbar must wrap Select with DataToolbarItem

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1292]
As a workaround for https://github.com/patternfly/patternfly-react/issues/3574 (see below), we set the width for the PatternFly Select component.

<img width="1305" alt="Screen Shot 2020-01-24 at 9 41 54 AM" src="https://user-images.githubusercontent.com/17481322/73077481-3f823f00-3e8e-11ea-81e4-9acd2d1b9c7a.png">

Looks like we just need to wrap the select menu with `DataToolbarItem` and the width prop can be removed.

**Comment by dchorvat1** [comment]
Verified, 948ddf7f311ee405a1723a00ca7c3eb81b5894bc
