### ISSUE TITLE
Replace logical AND with OR

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1298]
Users want the ability to group_by categories. In the UI details page; for example, we want the ability to  group_by `tag:environment=dev` OR `tag:environment=qe`, but only show results for `cluster_1` or `cluster_2`.

![Screen Shot 2020-01-30 at 10 16 40 AM](https://user-images.githubusercontent.com/17481322/73462369-b4032500-4349-11ea-8f4d-603bf93ef193.png)

In order to do that, the backend APIs may need to change slightly? See https://github.com/project-koku/koku/issues/1619.

The UI also needs to remove the logical AND we currently apply to all group_by query params -- see https://github.com/project-koku/koku-ui/blob/master/src/api/ocpCloudQuery.ts#L41.

Note that we should ensure the issue below is resolved. That is, to be certain this is what needs to be done in the UI.

See https://github.com/project-koku/koku/issues/1619

**Comment by dlabrecq** [comment]
After speaking with @blentz, it appears that we may already apply logical AND to unique group_by categories. Therefore, I'll go ahead and remove the `:and` prefix applied to group_by values.

**Comment by dchorvat1** [comment]
verified, 2b823abfb9fe715010ccb0078c5a155c0e5eb0e1
