### ISSUE TITLE
Text updates to cost model

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1304]
**Describe the fit and finish**
Text updates to cost model

**Change table**

Change | Description 
---------- | --------------
Cost models page | Change the help popup text “A cost model allows you to associate a price to metrics provided by your sources to charge for utilization of resources."
Create cost model wizard | Change the description under the title to “A cost model allows you to associate a price to metrics provided by your sources to charge for utilization of resources."
Price list table | we should replace the dash with a space between the resource and its metric and make the metric lowercase, when listing the rates. For example: "Memory-Requests (GB-hours)" should now look like "Memory requests (GB-hours)"
Add rate form | when listing the metric's measurement unit (e.g. GB-hour or core-hours), if it is not an acronym/abbreviation, it should follow sentence capitalization. For example: "Memory requests (GB-hours)" is OK.  "Node currency (node-month)" is preferred.  When we are just listing the measurement unit by itself (not sure where this would occur in our UI, but just in case we do, it would follow sentence capitalization: "Core-hours is the measurement unit..." or "The measurement unit is core-hours for...", that's what is meant for sentence capitalization. 
Create cost model wizard (markup) | Replace the step's introductory text with: “To apply a markup to the base cost of your source(s), enter a positive percentage value. To apply a discount, enter a negative value (using -)  to subtract from the base costs.”
Create cost model wizard (markup) | The error message - edit: “Markup must be a positive or negative number”
Create cost model wizard (assign sources) | Edit the step's description to: "Select the source(s) you want to assign the cost model to. Assigning a new cost model will overwrite any previous cost model assignments. You can also save your cost model and assign it to a source later."
Create cost model wizard (review) | Edit step's introductory text: "Review and confirm your cost model configuration and assignments. Click **Finish** to create the cost model, or **Back** to revise."

**Comment by dchorvat1** [comment]
verified, 2b823abfb9fe715010ccb0078c5a155c0e5eb0e1
