### ISSUE TITLE
Create cost model wizard (assign sources): PF data toolbar

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1306]
Replace existing PatternFly toolbar, on the details pages, with the experimental PatternFly data toolbar. The PF data toolbar follows the latest PatternFly design pattern, which includes new icons, chip layout, etc.

**Comment by dchorvat1** [comment]
I found some issues with `assign sources` step in create cost model wizard:
  - It seems to me that the toolbar is still the PatternFly Toolbar and not a PatternFly Data Toolbar
  - For Azure, this step misses some localized strings
  - This step could not display sources we can assign, even though there were providers present

Screenshot:
![Screenshot from 2020-03-03 11-13-06.png](https://images.zenhubusercontent.com/5c3320c5ea2ab97902b1b15b/89e5783f-79c0-415d-abc9-15c8c8de26ef)

cc @boaz0

**Comment by boaz0** [comment]
@dchorvat1 - please be advised, you don't see the sources because the `/sources/` endpoint doesn't contain the "cost_models" attribute.

There is a PR for that https://github.com/project-koku/koku/pull/1832.

**Comment by dchorvat1** [comment]
@boaz0 yep, that looks like it's been resolved. Besides that, could you take a look at the two other points I addressed?

**Comment by boaz0** [comment]
@dchorvat1 - in regards to your other points:
- I checked it and it's using the Data Toolbar (you can see by the chips when you add query).
- I fixed the translation error in #1363
