### ISSUE TITLE
Create cost model wizard (price list table): PF data toolbar

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1307]
Replace existing PatternFly toolbar, on the details pages, with the experimental PatternFly data toolbar. The PF data toolbar follows the latest PatternFly design pattern, which includes new icons, chip layout, etc.

**Comment by dlabrecq** [comment]
This should remain open for QA

**Comment by dchorvat1** [comment]
Verified, 2b823abfb9fe715010ccb0078c5a155c0e5eb0e1
