### ISSUE TITLE
Details: show array of cluster names

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1314]
The details pages are expected to display a single cluster name, belonging to a particular project, node, etc., when expanding each data table row. 

The cluster name/alias has not been available in the API calls for quite a while. However, the API will soon restore that info, but as an array of cluster names/aliases.

When the PR below is merged, the UI should be updated to display clusters similar to tags.

Depends on https://github.com/project-koku/koku-ui/issues/1294

**Comment by dchorvat1** [comment]
verified, 2b823abfb9fe715010ccb0078c5a155c0e5eb0e1
