### ISSUE TITLE
 Strange bold text on OCP details page

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1316]
**Describe the bug**
unused/unrequested capacity text is bold on the OCP details page when grouping by cluster

**To Reproduce**
1. Go to 'Openshift details'
2. Click on 'group by cluster'
3. Scroll down to cluster and expand row
4. See the cluster capacity text

**Expected behavior**
Text should match other text in UI

**Screenshots**
![Screenshot from 2020-02-06 20-52-42.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/c3626e9a-72ce-4a74-8c31-9d5f6262fbf5)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Comment by dlabrecq** [comment]
This styling comes from the PatternFly TextList component. You can see this with the PatternFly data list example https://patternfly-react.surge.sh/documentation/react/components/text#examples

Note that this also matches the mock https://marvelapp.com/1jj511j6/screen/64401384

Mock snapshot:
![Screen Shot 2020-02-07 at 8.34.02 AM.png](https://images.zenhubusercontent.com/5b47705f01db7d22de6439cd/84ba9f45-68e4-4695-8046-d36c41ec3ff5)
