### ISSUE TITLE
Cost model wizard texting updates (fit and finish)

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1321]
**Describe the fit and finish updates**
Wording updates regarding the `create cost model` wizard

**Change table**

| Change | Description |
| ---------- | --------------- |
| step: Assign sources | Edit the source step title to "Assign a source to the cost model" |
| step: Review | Edit the field label "Set markup or discount" to "Markup/discount" (for brevity) and "Assign sources" should be "Assigned sources" (past tense). |
| step: Review (on success) | Change text to "`<Cost model name>` has been successfully created." |
| Confirmation dialog (cancel the create wizard process) | cc @nlcwong add a mock here |

//fyi @dayleparker @nlcwong - this ticket covers all the fit and finish changes we went through in the spreadsheet.
//cc @nlcwong please upload the necessary mock in your comment and I will add it to the table.

Thanks.

**Comment by nlcwong** [comment]
![CancelCostModel](https://user-images.githubusercontent.com/31672086/74280716-14e81100-4ceb-11ea-819b-146d72a5bf0f.png)

@dayleparker  Please let me know if this copy is OK with you

**Comment by dayleparker** [comment]
Looks good to me @nlcwong!

**Comment by dlabrecq** [comment]
This should not be closed until QA approves

**Comment by lcouzens** [comment]
Most of this looks good apart from the review screen. I Expect to see `Assigned sources` but actually see `cost_models_wizard.review.sources`

![Screenshot from 2020-02-17 10-38-38.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/9e8f7b41-aa62-4982-80b3-a8bec070095c)

**Comment by nlcwong** [comment]
Now that I look at it, for the review step, "Create price list" should say "Price list".  That would eventually list out the rates in the price list.

**Comment by boaz0** [comment]
@nlcwong - I added that change to #1327

**Comment by lcouzens** [comment]
Verified

**Comment by boaz0** [comment]
Thanks a lot @lcouzens 
![](https://media.giphy.com/media/39fj7g99qyD72/giphy.gif)
