### ISSUE TITLE
No sources link should point the user to platform sources

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#1322]
**Describe the bug**

Now sources integration is complete our links should be pointing users to that UI (cost management sources should no longer be used).

https://github.com/project-koku/koku-ui/blob/cdf31e9f4f3c2b7f61d51cf1f12fe63b09514914/src/components/state/noProvidersState/noProvidersState.tsx#L32

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/29379759/74252881-4f868500-4cbc-11ea-94a1-b15d8cea0ddb.png">

**To Reproduce**
1. Login to an account without sources created
2. Click on Cost Management
3. See link to setup sources and click

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/29379759/74253130-aee49500-4cbc-11ea-8117-3f027a70a818.png">

**Expected behavior**
We should link users to platform sources (https://cloud.redhat.com/beta/settings/sources)
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/29379759/74253198-c9b70980-4cbc-11ea-8ed6-c914c6f93b6e.png">

**Comment by lcouzens** [comment]
My guess is this didn't land in CI yet for w/e reason, or its still not fixed.

**Comment by lcouzens** [comment]
@dlabrecq could it be from the failed travis run? https://travis-ci.org/project-koku/koku-ui/builds/649700134?utm_source=github_status&utm_medium=notification

**Comment by dlabrecq** [comment]
Yea, that's a likely problem. Will look into that, thanks.

**Comment by lcouzens** [comment]
Verified
