### ISSUE TITLE
DataToolbarFilter: Maximum update depth exceeded

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1326]
**Describe the bug**
Ingested a large amount of OCP data attempted to load openshift details page

**To Reproduce**
1. Ingest OCP data
2. Go to openshift details page
3. See console errors

**Expected behavior**
Page should load correctly

**Screenshots**

![Screenshot from 2020-02-17 11-42-07.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/3dfdd6ab-8f5d-4b13-a6b9-9b3738350589)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 72

**Additional context**
Testing against CI environment also error is currently failing on the insights-qa account for a quick reproducer.

**Comment by boaz0** [comment]
Oh boy, please don't be a webpack problem. :scream_cat:

**Comment by boaz0** [comment]
I think the source of the error is in [these lines](https://github.com/project-koku/koku-ui/blob/master/src/pages/details/components/toolbar/toolbar.tsx#L588-L590):

```js
{this.getTagKeyOptions().map(option =>
  this.getTagValueSelect(option)
)}
```

@dlabrecq is there a way to avoid the loop over tag key options?

**Comment by dlabrecq** [comment]
This may be a problem with how the PatternFly requires a unique DataToolbarFilter component to represent the chip values for each tag key. If there are 100 tags, there would 100 DataToolbarFilter components.

**Comment by boaz0** [comment]
If that so, do we need to open a ticket in pf4-react and set it as blocker (unless 100 tag keys is not a common thing)?

**Comment by dlabrecq** [comment]
Yes, I created https://github.com/patternfly/patternfly-react/issues/3770

In the mean time, we may have to limit this to the first 25 tags or so?

**Comment by lcouzens** [comment]
Verified
