### ISSUE TITLE
Github actions: Run failed for master

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1333]
Emails are being generated stating, "Run failed for master". It gives the impression that the recent merge failed. Thus, it's caused confusion in the team -- not clear if it's something we should ignore?

Some code was recently pushed (see https://github.com/project-koku/koku-ui/pull/1329), which appears to be related to github actions. We should consider disabling the feature until it's is fully working.

>Begin forwarded message:
>
>From: Doug Donahue <notifications@github.com>
>Subject: [project-koku/koku-ui] Run failed: github-bot - master (c37762a)
>Date: February 19, 2020 at 3:32:18 PM EST
>To: project-koku/koku-ui <koku-ui@noreply.github.com>
>Cc: Ci activity <ci_activity@noreply.github.com>
>Reply-To: project-koku/koku-ui <noreply@github.com>
>
>Run failed for master (c37762a)
>
>Repository: project-koku/koku-ui
>Workflow: github-bot
>Duration: 18.0 seconds
>Finished: 2020-02-19 20:32:17 UTC
>
>View results
>Jobs:
>
>    39365b96-3505-5d9b-4c42-e85a2ce45a4f failed (1 annotation)
>
>—

@boaz0 FYI

**Comment by boaz0** [comment]
Github actions are not suppose to fail the merge. They are just updating labels.
You can ignore these messages in the future as they're not related to the build process. 
I believe you can set to not receive such messages to your email.

In addition, I think I know why this task fails, I will fix it soon. Thanks.
