### ISSUE TITLE
Details: Filter chips disappear

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1335]
When filtering by tag, the PatternFly `DataToolbarFilter` chips disappear when a new category is selected.

![chrome-capture](https://user-images.githubusercontent.com/17481322/75053257-f29a8400-549e-11ea-9232-ef3b64608784.gif)

Note that this is due to the workaround implemented for https://github.com/project-koku/koku-ui/pull/1328

**Comment by lcouzens** [comment]
Verified
