### ISSUE TITLE
Overview: OpenShift supplemental cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1339]
Introducing a new "OpenShift supplemental cost" page to the overview per mocks below.

Mock: https://marvelapp.com/4b95ibf/screen/66066598

![Screen Shot 2020-02-25 at 4 20 25 PM](https://user-images.githubusercontent.com/17481322/75288644-c0fd2200-57ea-11ea-9a63-9ee095371f42.png)

**Comment by dlabrecq** [comment]
I believe we will use the reports/openshift/infrastructures/all/costs/ API here, but it's not clear what filters we need to use for a supplementary view?

@adberglund @nlcwong

**Comment by adberglund** [comment]
This will be the `reports/openshift/costs/` API, but instead of grabbing the costs from `cost` you'll grab from `supplementary`

**Comment by dlabrecq** [comment]
Depends on https://github.com/project-koku/koku/issues/1762

**Comment by chambridge** [comment]
This should be unblocked now.

**Comment by dchorvat1** [comment]
verified
