### ISSUE TITLE
Overview: Amazon Web Services filtered by OpenShift

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1340]
Introducing a new "Amazon Web Services filtered by OpenShift" page to the overview per mocks below.

Mock: https://marvelapp.com/4b95ibf/screen/66066594

![Screen Shot 2020-02-25 at 4 48 03 PM](https://user-images.githubusercontent.com/17481322/75290575-9dd47180-57ee-11ea-9cf6-6a5eb9f31702.png)

**Comment by dlabrecq** [comment]
I believe we will use the `reports/aws/costs/` API here, but it's not clear what filter(s) we need to use for a OpenShift view?

@adberglund @nlcwong

**Comment by adberglund** [comment]
This is `reports/openshift/infrastructures/aws/`

**Comment by dlabrecq** [comment]
Depends on https://github.com/project-koku/koku/issues/1762

**Comment by chambridge** [comment]
This should be unblocked.

**Comment by dchorvat1** [comment]
verified
