### ISSUE TITLE
Overview: Microsoft Azure filtered by OpenShift

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1341]
Introducing a new "Microsoft Azure filtered by OpenShift" page to the overview per mocks below.

Mock: https://marvelapp.com/4b95ibf/screen/66066596

![Screen Shot 2020-02-25 at 4 50 52 PM](https://user-images.githubusercontent.com/17481322/75290785-00c60880-57ef-11ea-9be2-0f8af6f61ebc.png)

**Comment by dlabrecq** [comment]
I believe we will use the `reports/azure/costs/` API here, but it's not clear what filter(s) we need to use for a OpenShift view?

@adberglund @nlcwong

**Comment by adberglund** [comment]
This is `reports/openshift/infrastructures/azure/`

**Comment by dlabrecq** [comment]
Depends on https://github.com/project-koku/koku/issues/1762

**Comment by chambridge** [comment]
This should be unblocked.

**Comment by dchorvat1** [comment]
verified
