### ISSUE TITLE
Overview: OpenShift usage

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1342]
Introducing a new "OpenShift usage" page to the overview per mocks below.

Mock: https://marvelapp.com/4b95ibf/screen/66066597

![Screen Shot 2020-02-25 at 4 52 31 PM](https://user-images.githubusercontent.com/17481322/75290915-3b2fa580-57ef-11ea-8e72-a4e1ffb5b922.png)

**Comment by dlabrecq** [comment]
I believe we will use the `reports/openshift/costs/` API here, but it's not clear what filter(s) we need to use for a OpenShift usage view?

@adberglund @nlcwong

**Comment by adberglund** [comment]
@nlcwong @chargio Correct me if I'm wrong, but I believe this view is equivalent to OpenShift on Premises? We don't want to show any OpenShift on Cloud costs here?

If so @dlabrecq the API would be `reports/openshift/costs` and you'd want to show infrastructure->usage here.

**Comment by dlabrecq** [comment]
Depends on https://github.com/project-koku/koku/issues/1762

**Comment by chargio** [comment]
I understand that this is equivalent to OpenShift Infrastructure (including monthly charging). Non-infra would be visible in the OpenShift tab, this provides a view of the infra used for OpenShift that is not raw cloud costs.
I don't know if the name makes sense or should be changed

**Comment by chargio** [comment]
@dayleparker Comments?

**Comment by chambridge** [comment]
This should be unblocked.

**Comment by dlabrecq** [comment]
@adberglund @chargio Would it not make sense to use the reports/openshift/infrastructures/all/costs/ APIs here, since this is under the Infrastructure overview? 

After all, these are the APIs used for the Infrastructure > "All cloud filtered by Openshift" overview page. I've simply moved the OpenShift cards to their own "OpenShift usage" overview page.

**Comment by dlabrecq** [comment]
After feedback from @nwong, we will use the infrastructure APIs.

Note that the first card (i.e., cost) is the exactly same for both "All cloud filtered by OpenShift" and "OpenShift usage" pages -- they use the same costs API

**Comment by dchorvat1** [comment]
verified

**Comment by adberglund** [comment]
@nlcwong @chargio @dlabrecq @chambridge Let's put together a quick call to verify the API calls and intent here. I don't think the `reports/openshift/infrastructures/all/costs/` does what you actually want here, and I'd like to make sure we're on the same page.
