### ISSUE TITLE
Overview: Refactor OpenShift tab

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1343]
Refactor the "OpenShift" overview page to use a dropdown in conjunction with tab navigation. This also removes progress bars for most cards (i.e., except 1st), and updates titles.

Mock: https://marvelapp.com/4b95ibf/screen/65806667

![Screen Shot 2020-02-25 at 4 59 16 PM](https://user-images.githubusercontent.com/17481322/75291428-2d2e5480-57f0-11ea-9ca8-512079af98ef.png)

**Comment by dchorvat1** [comment]
verified, 54ec1fef4d374c1453fdf1a996d591660260ff7c
