### ISSUE TITLE
Overview: Refactor OpenShift on cloud infrastructure

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1344]
Refactor the "OpenShift on cloud infrastructure" overview page to use a dropdown in conjunction with tab navigation. This also removes progress bars for most cards (i.e., except 1st), and updates titles.

Mock: https://marvelapp.com/4b95ibf/screen/65806666

![Screen Shot 2020-02-25 at 4 59 55 PM](https://user-images.githubusercontent.com/17481322/75291523-623aa700-57f0-11ea-8746-709373c8ba07.png)

**Comment by dchorvat1** [comment]
verified, 54ec1fef4d374c1453fdf1a996d591660260ff7c
