### ISSUE TITLE
Overview: Refactor AWS

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1345]
Refactor the "AWS" overview page to use a dropdown in conjunction with tab navigation. This also removes progress bars for most cards (i.e., except 1st), and updates titles.

Mock: https://marvelapp.com/4b95ibf/screen/66066593

![Screen Shot 2020-02-25 at 5 01 18 PM](https://user-images.githubusercontent.com/17481322/75291561-75e60d80-57f0-11ea-90d3-77d9f0d3fd60.png)

**Comment by dchorvat1** [comment]
verified, 54ec1fef4d374c1453fdf1a996d591660260ff7c
