### ISSUE TITLE
Overview: Refactor Azure

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1346]
Refactor the "Azure" overview page to use a dropdown in conjunction with tab navigation. This also removes progress bars for most cards (i.e., except 1st), and updates titles.

Mock: https://marvelapp.com/4b95ibf/screen/66066595

![Screen Shot 2020-02-25 at 5 02 10 PM](https://user-images.githubusercontent.com/17481322/75291633-97df9000-57f0-11ea-96bc-c393b9ea799b.png)

**Comment by dchorvat1** [comment]
verified, 54ec1fef4d374c1453fdf1a996d591660260ff7c
