### ISSUE TITLE
Github actions are not working as expected

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1352]
I just merged two PRs, tagged with "status/code-review". These particular PRs were not in the "Review" category, nor did they move into the "QA" category after the merge. They remained in the "In Progress" category, son I manually moved them to "QA".

Similarly, I have some of my own PRs that do not have any tags whatsoever. I've been moving issues manually thru the different categories.

![Screen Shot 2020-03-02 at 10 14 00 AM](https://user-images.githubusercontent.com/17481322/75689231-d5b83a80-5c6e-11ea-96d9-acabb4462eea.png)

**Comment by dlabrecq** [comment]
Just received a build failure message in my email.

![Screen Shot 2020-03-02 at 11 10 40 AM](https://user-images.githubusercontent.com/17481322/75694456-8ece4300-5c76-11ea-8ce7-513cc6bc8054.png)

**Comment by boaz0** [comment]
Thanks - I will disable github actions and come with a better idea how to do that.

**Comment by dlabrecq** [comment]
FYI, I've received 7 of these emails today -- one every hour. Is this on a cron job?

**Comment by boaz0** [comment]
Yes, at least I know it fixed the problem with the authentication...

**Comment by boaz0** [comment]
removed github actions workflows
