### ISSUE TITLE
No cost data available even though there are reports and providers.

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1358]
**Describe the bug**
Even though, there are providers with data when going to Azure or to OCP there is a message saying: `No cost data available yet`.

**To Reproduce**
1. Go to 'OpenShift cloud infrastructure details'
2. See error

**Expected behavior**
Display table with details

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/75764461-8f360f00-5d46-11ea-888b-0e3745b1a2fa.png)

**Additional context**
Looking at the Network tab, all requests are successful especially to `/reports/`.
I don't see requests to `/providers/` though.

**Comment by dlabrecq** [comment]
The API recently changed from `providers` to `sources`. This may not be available in CI, yet?

See https://github.com/project-koku/koku-ui/pull/1350/files

**Comment by dlabrecq** [comment]
This appears to be working for me, running local CI beta, using the cost-demo user.

The following APIs are returning data as expected.

https://ci.foo.redhat.com:1337/api/cost-management/v1/sources/?type=AWS
https://ci.foo.redhat.com:1337/api/cost-management/v1/sources/?type=AZURE
https://ci.foo.redhat.com:1337/api/cost-management/v1/sources/?type=OCP

![Screen Shot 2020-03-03 at 9 59 49 AM](https://user-images.githubusercontent.com/17481322/75788153-d071f300-5d35-11ea-849b-f29dd9d5f630.png)

![Screen Shot 2020-03-03 at 9 59 58 AM](https://user-images.githubusercontent.com/17481322/75788162-d4057a00-5d35-11ea-8c65-1dcfcc6da8ea.png)

![Screen Shot 2020-03-03 at 10 00 09 AM](https://user-images.githubusercontent.com/17481322/75788172-d8ca2e00-5d35-11ea-85bf-42843df93dd5.png)

**Comment by dlabrecq** [comment]
Confirmed this is working with CI beta and the cost-demo user.

**Comment by boaz0** [comment]
//cc @dchorvat1 can you look at this since you mentioned this to me.
