### ISSUE TITLE
Azure cost model wizard - screen 3 fields not rendering

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#1362]
**Describe the bug**
Two lines on the "Assign a source to the cost model" step (in the Azure cost model part of the wizard) are not rendering as expected. Screenshot attached.

**To Reproduce**
1. Go to https://cloud.redhat.com/beta/cost-management/cost-models (I'm looking at the ci version)
2. Start creating a cost model for Azure and go to step 3 - Assign a source to the cost model
3. See error

cost_models_wizard.source.title_AZURE

Select the source(s) you want to assign the cost model to. Assigning a new cost model will overwrite any previous cost model assignments. You can also save your cost model and assign it to a source later.

Select from the following source_details.type.AZURE sources:

**Expected behavior**

Something similar to the AWS screen but for Azure:

Assign Amazon Web Service source(s) (optional)
Select the source(s) you want to assign the cost model to. Assigning a new cost model will overwrite any previous cost model assignments. You can also save your cost model and assign it to a source later.
Select from the following AWS sources:

**Screenshots**

<img width="909" alt="Screenshot 2020-03-06 at 11 33 18" src="https://user-images.githubusercontent.com/20275317/76076213-aff8a180-5f9e-11ea-812e-0301455af511.png">

**Comment by dchorvat1** [comment]
Verified
