### ISSUE TITLE
Sources UI docs update

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1366]
Update sources UI docs.

| Source type | Step # | Description |
| ---------------- | --------- | --------------  |
| AWS | 3 | Add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#creating_an_aws_s3_bucket) |
| AWS | 5 | De-link AWS IAM link and add Learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#enabling_aws_account_access)|
| Azure | 3 | Add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#creating_an_azure_storage_account) |
| Azure | 4 | Update learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#configuring_an_azure_service_principal) |
| Azure | 5 | Update learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#configuring_an_azure_daily_export_schedule) |
| OCP | 3 | De-link all links in the bullets and add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#installing_ocp_prerequisites) |
| OCP | 4 | Remove the `?` icon and add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#obtaining_metering_operator_login_ocp) |
| OCP | 4 | Remove the word “your” from the left nav and title for brevity and style consistency. |
| OCP | 5 | Add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#downloading_and_configuring_usage_collector_ocp) |
| OCP | 5 | Update text in the 3rd item to "Run the ocp_usage.sh script to configure the Usage Collector with the values for your OpenShift API endpoint,  Reporting Operator namespace, and reporting-operator token file path." |
| OCP | 5 | Update text in the 4th item to "When configuration is complete, the confirmation message will provide your cluster identifier." |
| OCP | 5 | Add learn more [link](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#uploading_data_with_usage_collector_ocp) |

**Comment by dlabrecq** [comment]
@boaz0 Was this merged? Having trouble tracking the PR down

**Comment by boaz0** [comment]
It was merged [here](https://github.com/RedHatInsights/frontend-components/pull/397) and I know it's in CI (on Sources). Don't know what is the procedure (does our QE test it or sources QE do?), though.

**Comment by dlabrecq** [comment]
I'll just move this to the QA category

**Comment by dchorvat1** [comment]
verified
