### ISSUE TITLE
Create cost model button missing

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1368]
**Describe the bug**
Create cost model button is missing in cost model details page when there are cost models present, so we can't access the Cost model wizard.

**To Reproduce**
1. Go to cost model details
2. See error

**Expected behavior**
Create cost model button present.

**Screenshots**
![Screenshot from 2020-03-10 13-41-08](https://user-images.githubusercontent.com/46324552/76313460-439adc80-62d5-11ea-8d68-9f15551728ac.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
CI beta

**Comment by chambridge** [comment]
@dchorvat1 I know @boaz0 has been working on enabling RBAC for this scenario. Can you provide some information, was the user an org_admin or did the user have permission to write a rate?

**Comment by dchorvat1** [comment]
The user was `insights-qa`, it has permission to create cost models, I was able to add them both using api and from empty state cost model details page. The button is missing only when we have some cost models in the database.

**Comment by dchorvat1** [comment]
verified
