### ISSUE TITLE
Omit OpenShift cards from infrastructure overview

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1372]
Omit the following OpenShift cards from the infrastructure tab's "all filtered by OpenShift" perspective. These cards should only appear in the "OpenShift usage" perspective.

- OpenShift CPU usage and requests
- OpenShift memory usage and requests
- OpenShift volume usage and requests

Infrastructure tab:
![Screen Shot 2020-03-10 at 11 19 10 AM](https://user-images.githubusercontent.com/17481322/76327932-0593bd80-62c1-11ea-8693-692ef16895c0.png)

OpenShift cards (!database):
![Screen Shot 2020-03-10 at 11 19 26 AM](https://user-images.githubusercontent.com/17481322/76327938-07f61780-62c1-11ea-9134-18e66d8279df.png)

**Comment by dlabrecq** [comment]
This has been fixed with PR https://github.com/project-koku/koku-ui/pull/1376

**Comment by dchorvat1** [comment]
verified
