### ISSUE TITLE
Use `filter[]` pagination on details page

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku-ui#1373]
**Describe the bug**
I loaded the AWS details page on an account with 1100+ AWS accounts, and the results returned from the API included all of those accounts. The data load made the UI almost unresponsive. 

**Expected behavior**
The API calls should use `filter[limit]` and `filter[offset]` to control how many items are returned in the response. 

**Additional context**
See https://cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?filter[time_scope_value]=-1&group_by[account]=*&order_by[cost]=desc&filter[limit]=10&filter[offset]=10 for an example

**Comment by dlabrecq** [comment]
Looking at AWS details and we do call the API with `filter[limit]=10` and `filter[offset]=0` -- for the first paginated page. Below is the actual API call.

`https://ci.foo.redhat.com:1337/api/cost-management/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[account]=*&order_by[cost]=desc`

**Comment by dlabrecq** [comment]
The header also makes a call to the AWS costs API; however, we're only interested in the total cost -- there's no pagination here.

https://ci.foo.redhat.com:1337/api/cost-management/v1/reports/aws/costs/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly

We should ensure the header and the table to use the same report.

**Comment by dchorvat1** [comment]
verified
