### ISSUE TITLE
Wrong wording used for node cost

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1383]
**Describe the bug**
When creating a cost model we use the word currency to refer to price or cost.

**To Reproduce**
1. Go to cost models
2. Click on create new cost model
3. Enter a name
4. Click add rate
5. Select node
6. See node measurement

**Expected behavior**
Currency is not a measurement it should be price or similar

**Screenshots**
![Screenshot from 2020-03-17 18-11-24.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/89284731-e5a8-4036-8e2b-19cddebcd808)
![Screenshot from 2020-03-17 18-11-11.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/244c21d5-23d0-41c8-b142-8438d74c9001)
![Screenshot from 2020-03-17 18-11-00.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/e0b393ab-55a4-42c3-9e36-d18114fc4db4)

**Additional context**
Testing against CI

**Comment by dchorvat1** [comment]
verified
