### ISSUE TITLE
Create cost model - price list step

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#1386]
**Describe the bug**
The filter components found in the data toolbar in the create cost model wizard's price list step is inconsistent with how we are filtering elsewhere.

**To Reproduce**
1. Go to the Create a cost model wizard (launch it)
2. Make sure to select "OpenShift Container Platform" as the source type
3. Then after clicking Next to advance to the second step of the wizard (which should be Create a price list)
4. The empty table view show two drop downs to the left of the "Add rate" button (see screenshot below)

![Screen Shot 2020-03-12 at 10.43.01 AM.png](https://images.zenhubusercontent.com/5ae342d14b5806bc2bd0ec3f/f142c4cd-be00-4eb8-a563-8f3631107558)

**Expected behavior**
I would like the filter options to be more like what attribute-value filtering would look like:

![CreatePriceList-Step2b-EmptyTable.png](https://images.zenhubusercontent.com/5ae342d14b5806bc2bd0ec3f/2929efc7-770d-4f72-b50c-be8e3d713faa)

**Comment by dchorvat1** [comment]
verified
