### ISSUE TITLE
 Infrastructure overview to show top services, accounts, & regions

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1387]
For the infrastructure overview (i.e., the "All filtered by OpenShift" view), we want to show top services, accounts, and regions in the cost card instead of projects, nodes, & clusters.

Mock: https://marvelapp.com/4b95ibf/screen/65806666

<img width="1502" alt="Screen Shot 2020-03-18 at 12 46 18 PM" src="https://user-images.githubusercontent.com/17481322/76985365-80d71e00-6916-11ea-9e89-4c3bf1468aa2.png">

**Comment by dchorvat1** [comment]
verified
