### ISSUE TITLE
Update Insights navigation panel

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1389]
The Insights navigation panel would appear as follows.
```

Overview
Details
 > OpenShift
 > Infrastructure
Cost models
```

This replaces existing links for "OpenShift could infrastructure details", "OpenShift details", & "Cloud details".

Mock: https://marvelapp.com/4d8h858/screen/67166322

<img width="290" alt="Screen Shot 2020-03-18 at 2 05 00 PM" src="https://user-images.githubusercontent.com/17481322/76993880-f0073f00-6923-11ea-8e9b-01c091fb00eb.png">

**Comment by dlabrecq** [comment]
See Insights...

PR: https://github.com/RedHatInsights/cloud-services-config/pull/136
Issue: https://projects.engineering.redhat.com/browse/RHCLOUD-5267

**Comment by dlabrecq** [comment]
Kyle is making changes to the navigation. Will place this on hold for now.

**Comment by dchorvat1** [comment]
verified
