### ISSUE TITLE
Add routes for new navigation panel

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1390]
Want to add routes to support the new navigation panel. This will ensure the Insights nav panel works properly when promoted. 

The new navigation panel will appear as follows.

```
Overview
Details
 > OpenShift
 > Infrastructure
Cost models
```

The new routes will look like this:

```
/details/infrastructure/aws
/details/infrastructure/azure
/details/infrastructure/ocp-cloud
/details/ocp
```

And `/details/infrastructure` will redirect to `/details/infrastructure/aws`

Note: Keeping the old routes until Insights updates the nav panel.

**Comment by dchorvat1** [comment]
verified
