### ISSUE TITLE
Assign Sources modal filter does not show correct results

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1392]
**Describe the bug**
Filtering sources in the assign sources modal doesn't filter the results correctly.

**To Reproduce**
1. Go to 'cost models'
2. Click on one of the cost models
3. Choose the 'sources' tab
4. Click on "Assign Source"
5. Make sure there are sources to filter
6. Filter by name that exists
7. See error

In addition:
8. Removing the chip will show all the sources! -> error

**Expected behavior**
See correct results. So for example, having the following sources: yada, bla, haha
Filtering by "ha" will show only haha, removing it will show yada, bla, haha (which are Azure sources) and not moo, foo and bar which are OCP and AWS sources.

**Comment by dchorvat1** [comment]
verified
