### ISSUE TITLE
Supplementary cost description in Ocp details

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1396]
Need to update the supplementary cost description in the info popup, shown in Ocp details.

<img width="372" alt="Screen Shot 2020-03-19 at 1 13 14 PM" src="https://user-images.githubusercontent.com/17481322/77094836-6dde4f80-69e3-11ea-993a-4b15edd18d77.png">

FYI...

>Hey Dan! Sorry for my slowness on the Supplementary cost definition, I meant to do this after our meetings today and crashed (house arrest is hard!). FYI - I added a comment to the Marvel screen for Supplementary cost — but I couldn’t find you to tag on https://marvelapp.com/4d8h858/screen/67166322/comments

>This is the terminology page where we worked out our definitions — I’ll make a point of adding the descriptions to the lexicon if they are not there yet. https://docs.google.com/document/d/1hnwS0uwPuAKw75QyE2QEl8IZcczaQredMvDY10UVhLk/edit#

**Comment by dchorvat1** [comment]
verified
