### ISSUE TITLE
Overview list items for cost don't show currency

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1402]
**Describe the bug**
Overview cards for cost don't show currency in specific list items for costs.

**To Reproduce**
1. Go to Cost Management overview
2. See error

**Expected behavior**
Currency is shown for each of the items

**Screenshots**
![Screenshot from 2020-03-20 13-32-38](https://user-images.githubusercontent.com/46324552/77164511-bfa0db80-6ab0-11ea-93c4-3321b8d0e25b.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
CI beta

**Comment by dlabrecq** [comment]
Due to the recent `supplementary` API changes, we're not obtaining units correctly in the computed report items, used by the charts

**Comment by dchorvat1** [comment]
verified
