### ISSUE TITLE
Rename overview perspective as "All cloud filtered by OpenShift"

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1404]
Rename the "All filtered by OpenShift" overview perspective as "All cloud filtered by OpenShift"

>According to Andrew, the “All filtered by OpenShift” is today “All cloud filtered by OpenShift” so I think we need a name change on that drop down to better clarify what those totals mean and the API today already supports that

<img width="427" alt="Screen Shot 2020-03-20 at 2 05 54 PM" src="https://user-images.githubusercontent.com/17481322/77193234-4d31fa80-6ab4-11ea-9e69-6d165c5e8138.png">

**Comment by dchorvat1** [comment]
verified
