### ISSUE TITLE
Update overview "view all..." links

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1406]
Ensure all overview "view all..." links navigate correctly.

Also omit the "view all" links from the "filtered by OpenShift" overview pages. Only the following overview pages should show links.

- OpenShift > All
- Infrastructure > AWS
- Infrastructure > Azure
- ~~Infrastructure > OpenShift Usage~~

Note that the `Infrastructure > OpenShift Usage` link will eventually point to `details > infrastructure > RHOCP`. That is a future page, so the "view all" link can be omitted for now.

> Do you recall which overview pages have the "view all" links?

>The overview pages with the “view all” are the non-“filtered by OpenShift” ones and the OpenShift - All 

>So OpenShift-All; Infrastructure-AWS; Infrastructure-Azure; Infrastructure-OpenShift Usage those have the “View all…” links to the various details with the view by drop down already selected to that category

Mock:  https://marvelapp.com/project/4780029/screen/67395607

**Comment by dchorvat1** [comment]
verified
