### ISSUE TITLE
Cost model details error state

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1410]
**Describe the bug**
~~Cost model details page crashes because it makes a request to~~

 ~~`/api/cost-management/v1/cost-models/`~~

~~instead of~~

~~`/api/cost-management/v1/costmodels/`~~

in addition to this, the page displays the empty state message down below the error message.

**To Reproduce**
1. Go to cost model details
2. See error

**Expected behavior**
The page should display only the error message when the page crashes.

**Screenshots**
![bbb](https://user-images.githubusercontent.com/46324552/77318136-d2175100-6d0c-11ea-892e-8831a95c7d5a.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
CI beta

**Comment by dchorvat1** [comment]
I just noticed that the API will be updated to `cost-models`, however, the empty state message should not be displayed when the page errors out

**Comment by boaz0** [comment]
Thanks... I am working on it

**Comment by dchorvat1** [comment]
verified
