### ISSUE TITLE
Remove StyleSheet dependency

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1417]
PatternFly's StyleSheet functionality is being dropped from react-styles in v4. We use this heavily in Cost Management, but there is a security issue related to using Emotion.

>This code includes <style> tags in webpages which is a pattern that violates the CSP style-src unless using a nonce (which emotion does not support, see associated issue). Now that we've committed to Webpack, Webpack takes care of bundling CSS for us so that we no longer have need to use <style> tags. When inline styles are required (like BackgroundImage), it makes much more sense to use an inline style="" tag on a single element that does not violate the CSP nor require a 3rd party dependency. -- Zack Allen

>as long as we include emotion, we are breaking several products that have more strict security guidelines
>even putting the library in the package causes that problem -- Dana Gutride

We need to change our CSS styles from this format:
```
import { StyleSheet } from '@patternfly/react-styles';
export const styles = StyleSheet.create({
  chartSkeleton: {
    height: '125px',
    marginBottom: global_spacer_md.value,
    marginTop: global_spacer_3xl.value,
  },
});
```

To this:
```
import React from 'react';
import React from '@patternfly/react-styles';
export const styles = {
  chartSkeleton: {
    height: '125px',
    marginBottom: global_spacer_md.value,
    marginTop: global_spacer_3xl.value,
  } as React.CSSProperties,
};
```

Then, the components use the `style` prop instead of `className`, like so:
```
<Skeleton
  size={SkeletonSize.md}
  style={styles.chartSkeleton}
/>
```

**Comment by dchorvat1** [comment]
verified
