### ISSUE TITLE
Remove Emotion dependency

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1419]
PatternFly's StyleSheet functionality, which depends on Emotion, is being dropped from react-styles in PatternFly v4. This is due to a security issue related to using Emotion. The Koku UI should strongly consider dropping Emotion as well, in favor of using CSS style sheets.

>This code includes <style> tags in webpages which is a pattern that violates the CSP style-src unless using a nonce (which emotion does not support, see associated issue). Now that we've committed to Webpack, Webpack takes care of bundling CSS for us so that we no longer have need to use <style> tags. When inline styles are required (like BackgroundImage), it makes much more sense to use an inline style="" tag on a single element that does not violate the CSP nor require a 3rd party dependency. -- Zack Allen

>as long as we include emotion, we are breaking several products that have more strict security guidelines
>even putting the library in the package causes that problem -- Dana Gutride

Note that we've made a first pass at removing the PatternFly StyleSheet dependency. (See https://github.com/project-koku/koku-ui/pull/1418.)  However, we still depend on Emotion to add CSS style in a few places.

**Comment by boaz0** [comment]
Isn't it related to https://github.com/project-koku/koku-ui/pull/1418 ?

**Comment by dlabrecq** [comment]
@boaz, 1418 removed PatternFly's StyleSheet object. However, we still depend on Emotion to add CSS style in a few places.

**Comment by dlabrecq** [comment]
Created Jira issue: https://issues.redhat.com/browse/COST-49
