### ISSUE TITLE
Update paths for Insights navigation panel changes

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1432]
The new Insights navigation panel will appear as follows.

```
Overview
Details
 > OpenShift
 > Infrastructure
Cost models
```

This still needs to work with the existing links for "OpenShift could infrastructure details", "OpenShift details", & "Cloud details".

For testing cloud-services-config changes locally, see: 
https://github.com/RedHatInsights/cloud-services-config#testing-your-changes-locally

**Comment by dchorvat1** [comment]
verified
