### ISSUE TITLE
Cost details pages return 404

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1438]
**Describe the bug**
Navigating to openshift details or infrastructure details results in a 404.

**To Reproduce**
1. Go to Cost Management
2. Click on Openshift details
3. See error

**Expected behavior**
No 404s

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
Seen on CI beta/QA beta

**Comment by boaz0** [comment]
I guess https://github.com/project-koku/koku-ui/pull/1437 fixes this.

**Comment by dlabrecq** [comment]
This was an issue with the Insights navigation pane and has been fixed

https://github.com/RedHatInsights/cloud-services-config/pull/155

**Comment by dchorvat1** [comment]
verified
