### ISSUE TITLE
Cluster-currency rate missing translation

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1440]
**Describe the bug**
Cluster per currency rate was just merged https://github.com/project-koku/koku/pull/1959
Even though the rate is available in the wizard its translation is missing.

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'Create cost model'
3. Enter name, select Openshift Container Platform in type and click 'Next'
4. Click on 'Add rate'
5. Select Metric and see "cost_models.Cluster"

**Expected behavior**
Metric name should be Cluster and not cost_models.Cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/78033539-340c3200-736f-11ea-8bf3-5f3953d97dcd.png)

**Comment by dchorvat1** [comment]
verified
