### ISSUE TITLE
Refreshing Azure details redirects to OpenShift details

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1445]
**Describe the bug**
After refreshing at Azure details, we get to OpenShift details page

**To Reproduce**
1. Go to Azure details
2. Refresh
3. See error

**Expected behavior**
We should stay at Azure details after refresh.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 71

**Additional context**
AWS details works normally, the refresh does not change the page to OpenShift.

Tested on CI beta

**Comment by dlabrecq** [comment]
This is related to the Insights navigation issue below.

https://projects.engineering.redhat.com/browse/RHCLOUD-5575

**Comment by dlabrecq** [comment]
I'm temporarily removing our route redirects from the Koku UI. This was a request made by the Insights team to help debug their navigation pane.

While Insights works out the kinks, folks won't be able to navigate to the details pages.

**Comment by dlabrecq** [comment]
khala:  2:02 PM
Hey folks, here are the 2 PRs that fixes the navigation for cost-management

https://github.com/project-koku/koku-ui/pull/1482 - chrome sends on each load navigation update so we have to find correct path to redirect to (chrome only knows about app IDs ocp, aws, cost-management etc)

https://github.com/RedHatInsights/cloud-services-config/pull/164 - previously we've added group in navigation to indicate that cerain apps don't need to refresh if they see certain path, with this improvement details pages won't refresh

**Comment by dlabrecq** [comment]
I encountered a couple highlighting issues with the nav links. This Insights PR will fix that
https://github.com/RedHatInsights/cloud-services-config/pull/166

**Comment by dchorvat1** [comment]
verified
