### ISSUE TITLE
Cost model - price list cost type header wording

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1448]
| Change |  Description
| ----------- | ---------------
| Add price list form | Replace "Used for infrastructure type" in the table header to "Used for infrastructure cost" |

![image](https://user-images.githubusercontent.com/2453279/78222341-c1fe2f00-74cd-11ea-8f5d-1fc12b33db21.png)

**Comment by dchorvat1** [comment]
verified
