### ISSUE TITLE
Add reportPathsType to report ID

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1449]
When a report is requested, the data is cached in the store via a report ID. The problem is that the next report requested may share that same ID. This can result in some overview cards are displaying the wrong report. 

Now that we are using common report code, the report ID needs to be more specific. For example, instead of this ID:

`${reportType}--${query}`;

We can use something more like:

`${reportPathsType}--${reportType}--${query}`;

Where the reportType is cost, storage, tag, etc. and reportPathsType is ocp, aws, azure, etc.

This will ensure that when a report is requested, the correct report is retrieved from the store.

**Comment by dchorvat1** [comment]
verified
