### ISSUE TITLE
Cost model wizard review step - hide price list table if there are none

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1454]
**Describe the bug**
When creating a new OCP cost model and not rate was added, do not show the table in the review step. It is probably preferred to have a text saying "No rate was added" or "No rates".

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'Create cost model'
3. Enter a name and select Openshift Container Platform as type and click 'Next'
4. Click 'Next' till you get to the last step (the review step)
5. See errror

**Expected behavior**
Do not show table if there are no rates. It would be nice to see "No rates" or "No rate was added".

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/78218308-3df47900-74c6-11ea-94f3-d4bc7d924518.png)

**Comment by dchorvat1** [comment]
verified
