### ISSUE TITLE
Ocp Usage overview not showing the correct cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1457]
The Ocp Usage overview is not showing the correct cost. This page should should zero cost, right now.

For Ocp Usage, we want to use the meta prop `infrastructure.usage.value` as the total cost. However, for the Ocp overview, we still want to use the meta prop `cost.total.value` as the total cost, while using `infrastructure.total.value` for chart data.

**Comment by dchorvat1** [comment]
verified
