### ISSUE TITLE
Disable price list filter if there are no rates

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1488]
**Describe the bug**
When there are no rates in the price list table, disable the filters to not confuse the user with the add rate form.

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'Create cost model'
3. Enter any name and select "Red Hat Openshift Container Platform"
4. Click 'Next'
5. See the error

**Expected behavior**
Disable the filter selectors to imply the user that these are the filters and in order to add a rate she/he needs to click on "Add rate" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/79067727-2e491180-7cca-11ea-80b6-a992eb49aa74.png)

**Comment by dchorvat1** [comment]
verified
