### ISSUE TITLE
Replace "Infrastructure cost" switch to cost type selector

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1490]
## User Story
As User, I want to select the cost type from a select box so that I can select the cost type instead of checking whether I want this rate to be infrastructure cost or not.

This change required to update the rate table to replace "Use infrastructure cost" and "Yes/No" to "Cost type" and "Infrastructure/Supplementary" respectively.

## Impacts
UI

![image](https://user-images.githubusercontent.com/2453279/79105682-d0740280-7d79-11ea-9509-398d6fef544c.png)

**Comment by dchorvat1** [comment]
verified
