### ISSUE TITLE
Chart legend outside of card when using the maximise button.

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1493]
**Describe the bug**
Chart legend outside of card when using the maximise button.

**To Reproduce**
1. Go to Overview
2. Click on three dashes in top left corner
3. See cards

**Expected behavior**
Cards and text should scale correctly

**Screenshots**
![Screenshot from 2020-04-14 13-12-55.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/27f42e92-a2e6-41a2-b4f9-94b7908549de)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 72

**Additional context**
Testing against prod with the QA user

**Comment by dlabrecq** [comment]
I'm not able to reproduce this using Firefox 75 on Mac. Any chance you can update to a later version?

I've minimized and maximized the window, along with entering full screen.

Unfortunately, I don't have access to a dev environment on Fedora.

**Comment by dlabrecq** [comment]
Realized this is related to the hamburger icon (i.e., the nav toggle) in the top left, page header.

I've asked Insights to provide an event when the nav is toggled, so we can resize our components appropriately.

https://projects.engineering.redhat.com/browse/RHCLOUD-5890

In the mean time, I'll see about adding a workaround.

**Comment by dchorvat1** [comment]
verified
