### ISSUE TITLE
Openshift overview cards disappear if you click on tab multiple times

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1494]
**Describe the bug**
Openshift overview cards disappear if you click on tab multiple times

**To Reproduce**
1. Go to Overview
2. Click on Openshift tab twice
3. See cards disappear

**Expected behavior**
Cards should not disappear from view

**Screenshots**
![Screenshot from 2020-04-14 13-16-59.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/79305156-3261-448d-8c52-b5a9bc7828b9)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 72

**Additional context**
Testing against PROD with QA account

**Comment by dlabrecq** [comment]
This appears to be a PatternFly issue. Looking for a workaround.

https://github.com/patternfly/patternfly-react/issues/4074

**Comment by dlabrecq** [comment]
We lazily load tab contents, but the tab component appears to no longer accept null as tab contents.

Added an "empty tag" as a workaround in https://github.com/project-koku/koku-ui/pull/1498

**Comment by lcouzens** [comment]
Verified!
