### ISSUE TITLE
Details table items names spacing is off 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1495]
**Describe the bug**
Names of table items in details pages placement is off. 

**To Reproduce**
1. Go to OpenShift or Infrastructure details
2. See error

**Expected behavior**
Names placed in the middle of the table item.

**Screenshots**
![Screenshot from 2020-04-14 14-16-41](https://user-images.githubusercontent.com/46324552/79224222-03da8e00-7e5b-11ea-944d-c41715eed6c3.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser chrome

**Additional context**
Seen on CI beta

**Comment by dlabrecq** [comment]
The checkboxes and text are aligned as expected.

Mock:
https://marvelapp.com/4d8h858/screen/67166322

PatternFly data table:
http://patternfly-react.surge.sh/documentation/react/demos/paginationtable
