### ISSUE TITLE
Details page export button is not a button consistent accross platform

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1496]
**Describe the bug**
Details page export button is not a button consistent accross platform

**To Reproduce**
1. Go to Details
2. Select items from list
3. See export button

**Expected behavior**
Button should look like a button and be consistent with other buttons across the app

**Screenshots**
![Screenshot from 2020-04-14 13-23-54.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/80aedaac-897c-498c-ab22-c879a2520cc3)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 72

**Additional context**
Testing against PROD with QA account

**Comment by lcouzens** [comment]
Sorry Dan I didnt really clarify the difference in the issue but I think we need to change the colour and drop the text too see here.

![Screenshot from 2020-04-17 12-17-08.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/93de6386-8a7e-4a6d-a367-693837a39629)

The export button should just be the square+arrow

**Comment by dlabrecq** [comment]
IMO, it's not obvious what the icon represents. However, I'll remove the text

**Comment by lcouzens** [comment]
Verified
