### ISSUE TITLE
Details pages export file naming convention

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1497]
## User Story
As a user I would like to see exports from the details pages have a better naming convention on files from exports. For example: app_name-details_name-date so `cost-management-openshift-2020-04-14.csv`

## Impacts
Ex. API, UI, Docs

## Assumptions
-
-

## Acceptance Criteria

- [ ]
- [ ]

**Comment by dchorvat1** [comment]
verified
