### ISSUE TITLE
Overview units wrap oddly

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1502]
The units shown in the overview cards can word wrap oddly. For example, when resizing the window very small, `core-hours` looks odd when `core-` is on a line by itself.

<img width="362" alt="Screen Shot 2020-04-14 at 9 58 30 PM" src="https://user-images.githubusercontent.com/17481322/79291023-8aaf5b00-7e9b-11ea-952f-57f12f0bf286.png">

**Comment by dchorvat1** [comment]
verified
