### ISSUE TITLE
Fix the price list tab empty state and pagination styling

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1505]
**Describe the bug**
On the price list tab, the pagination should be compact and the empty state must be centered

**To Reproduce**
1. Go to 'Cost models'
2.  Filter by source type "Red Hat OpenShift Container Platform"
3. Click on a cost model that is OpenShift and number of sources is 0

**Expected behavior**
The pagination should be compact and the empty state must be centered

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/79372881-c52dfc00-7f5e-11ea-9446-725a21440cab.png)

**Comment by dchorvat1** [comment]
verified
