### ISSUE TITLE
Add text input to filter details tag key values

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1508]
The details page calls the tag API to fetch tag keys and values for use with the group-by menu and toolbar tag filter. However, if there are too many tag key values returned by the tag API request, the UI may hang.

>I did a count for tag keys in OSD’s data and they’ve got tags with 100,000 and 1 million values in them. They clearly picked some AWS auto generated tags to send in their cost and usage report, so those aren’t really user-generated tags, but they’re still there. -- Andrew

To help solve this issue, the tag API will limit the number of tag key values returned to 50 per tag key. If this limit is reached, we would like the toolbar filter to show a text input in place of the existing select component. 

This will allow the user to enter their own tag key value, instead of inadvertently omitting all other values from the filter.

When there are less than 50 tag key values, the toolbar can continue to show the existing select component.

See https://github.com/project-koku/koku/pull/2069

**Comment by dchorvat1** [comment]
verified
