### ISSUE TITLE
Azure cost model assign source filtering 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1510]
**Describe the bug**
When we filter on source name while assigning Azure source to a cost model, we get no results at all.
This is probably due to the request querying for 
`?source_type=AZURE`
instead of 
`?source_type=Azure`

**To Reproduce**
1. Go to Cost models
2. Add an Azure cost model, assign no sources
3. Navigate to the new cost model, click assign source
4. Filter on name
5. See error 

**Expected behavior**
Correct filtering 

**Screenshots**
![Screenshot from 2020-04-17 12-34-23](https://user-images.githubusercontent.com/46324552/79561149-22ce5f80-80a9-11ea-8d8c-1d44440f7b70.png)
![Screenshot from 2020-04-17 12-39-41](https://user-images.githubusercontent.com/46324552/79561158-25c95000-80a9-11ea-8b8f-861814c86d62.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome

**Additional context**
Tested on PROD beta and CI beta

**Comment by boaz0** [comment]
Thanks! I will work on it!

**Comment by lcouzens** [comment]
Verified
