### ISSUE TITLE
Cost model filtering by description leads to empty state page.

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1511]
**Describe the bug**
After we filter cost models by a description that fits none of the existing cost models, instead of displaying "No match found", we get empty state Cost models page and we can't remove the filter unless we refresh the page.

**To Reproduce**
1. Go to Cost models
2. Filter by a description that fits none of the cost models.
3. See error

**Expected behavior**
"No match found" displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome

**Additional context**
Tested on PROD beta/CI beta

**Comment by boaz0** [comment]
![image](https://user-images.githubusercontent.com/2453279/79563314-41d2ee80-80b5-11ea-81ae-1f9d05d74b64.png)

I am pretty sure you have a way to reproduce this. Can you give me that scenario + can you show me the requests and responses of each - that'll help me a lot.

Thanks :hugs:

**Comment by dchorvat1** [comment]
@boaz0 Filtering by name works correctly, you need to filter by description and use a filter that matches none of the cost models to see this bug

**Comment by boaz0** [comment]
Yep, I just saw it. Going to work on it. Thanks :)

**Comment by lcouzens** [comment]
Verified
