### ISSUE TITLE
OpenShift details view all price lists grouping by project/node.

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1512]
**Describe the bug**
When we group cost by project or node in OpenShift details and then we view all price lists using the kebab button, we get no rates back. In the screenshots we can see that the modal looks up rates for cluster `test_bravo`, which is name of the project and not a cluster name. 

**To Reproduce**
1. Go to OpenShift details, group cost by project
2. Click on kebab button, view all price lists
3. See error

**Expected behavior**
Rates correctly displayed

**Screenshots**
![Screenshot from 2020-04-17 13-36-35](https://user-images.githubusercontent.com/46324552/79565700-7f357d00-80b1-11ea-8272-61c21423e7fc.png)
![Screenshot from 2020-04-17 13-36-54](https://user-images.githubusercontent.com/46324552/79565706-82306d80-80b1-11ea-8d66-54dad84d946d.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome

**Additional context**
Tested on PROD beta/CI beta

**Comment by boaz0** [comment]
Thanks - this is something we are trying to figure out since the API was changed and it's not clear how to get cost model uuid or source uuid related to the project/cluster/node.

**Comment by dlabrecq** [comment]
Per today's backlog discussion, the team agreed to remove the kebab option, until the API is updated.

**Comment by dchorvat1** [comment]
verified
