### ISSUE TITLE
Applied usage date range not displayed correctly when veiwing cluster price list

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1513]
**Describe the bug**
Applied usage date range not displayed correctly when viewing cluster price list also cluster per month and node per month metrics show incorrectly.

**To Reproduce**
1. Go to openshift details
2. Click on three dots and `show price list`
3. See pop-up

**Expected behavior**
Text should be displayed correctly

**Screenshots**
![Screenshot from 2020-04-17 12-44-21.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/0218c20d-9143-44b8-a2c0-10feddd3824f)

There is also strange brackets after metrics do we need those??

**Additional context**
Testing against PROD, also producible against CI

**Comment by boaz0** [comment]
Can you attach the `/cost-models/<uuid>` response to the issue too?

Thanks.

**Comment by boaz0** [comment]
I am also confused because on `ci-beta` I can see these:

![Screenshot_2020-04-17 Cost Management](https://user-images.githubusercontent.com/2453279/79569059-9d09de80-80bf-11ea-9573-73d1a1c62042.png)

![image](https://user-images.githubusercontent.com/2453279/79569097-ac892780-80bf-11ea-86f7-3325a4e364cd.png)

**Comment by lcouzens** [comment]
Might be related to that :man_shrugging: but cluster/node still seems incorrect for the metric on CI 
![Screenshot from 2020-04-17 13-38-39](https://user-images.githubusercontent.com/18352403/79570188-e6066680-80b0-11ea-98ae-f7fb37860585.png)

**Comment by boaz0** [comment]
Got it, no problem!
