### ISSUE TITLE
Details pages group cost by dropdown disappears briefly  while loading a selection the first time. 

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1514]
**Describe the bug**
Details pages group cost by drop down disappears brefly while loading a selection the first time. 

**To Reproduce**
1. Go to details page
2. Select something from group by dropdown which has not been cached yet
3. See error page resize briefly while new grouping loads

**Expected behavior**
Group cost by filter should not disappear from the page during load.

**Screenshots**
![Screenshot from 2020-04-17 13-00-17.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/dba5b697-4e53-4791-bfd5-57fd144391e1)

![Screenshot from 2020-04-17 12-59-56.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/c2083f6b-74ee-4cfa-9e4a-eac1c5d9dbeb)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 80

**Additional context**
Testing against PROD also producible against CI

**Comment by dlabrecq** [comment]
This is by design. It was requested that we don't show the group-by menu or the total cost in the header unless the provider and cost APIs have data. Although, we can probably disable the menu instead.

**Comment by lcouzens** [comment]
Verified
