### ISSUE TITLE
Region filter not working as expected in api

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#152]
When applying the region filter to reports/costs/ there is no listed regions shown

1. Add provider to hccm
2. Hit masu api/v1/download/ if required
3. head to api/v1/reports/costs/?filter[region]=*

See filter is applied but no regions data visible
{
    "filter": {
        "region": [
            "*"
        ]
    },
    "data": [
        {
            "date": "2018-09-28",
            "values": [
                {
                    "date": "2018-09-28",
                    "units": "USD",
                    "total": 26.574645075,
                    "account_alias": "389787642310"
                }
            ]
        },
**Expected behavior**
Costings shown with region values.

**Desktop (please complete the following information):**
 - OS: fedora
 - Browser firefox
 - Version 62.0.2

**Additional context**
koku version
commit: "2b3ca9e9b8d80d9524919336886c344f53a9a2fd"
masu version
commit:"ea0847c7b3f3b3ce4d811004a714c71c71475d2a"
Running with the 3scale header.

**Comment by lcouzens** [comment]
@chambridge ah ok, so I can 'group by' then filter on a specific region?

**Comment by dlabrecq** [comment]
This doesn't appear to be an issue with the Koku UI. Can we close this?

**Comment by chambridge** [comment]
@lcouzens Feel free to reopen if we didn't clarify this properly.
