### ISSUE TITLE
Group-by default option

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1527]
The group-by menu may show the wrong option.

**To Reproduce**
1. Go to "Details > OpenShift"
2. Click on "Group cost by"
3. Select "Tag Key: Environment"
4. Click on the "Details > OpenShift" nav link

**Expected behavior**
The group by selected option should default to "Project"

**Additional context**
This can happen when attempting to restore page state from the query URL. Retrieving query params may return undefined, early in the React life cycle. Thus, it's possible to display the wrong default option.

**Comment by lcouzens** [comment]
Verified
