### ISSUE TITLE
Openshift details is showing incorrectly formatted strings in filter dropdown

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1529]
**Describe the bug**
Openshift details is showing incorrectly formatted strings in filter dropdown

**To Reproduce**
1. Go to 'Openshift details'
2. See test in filter dropdown

**Expected behavior**
Filter string should be displayed correctly.

**Screenshots**
![Screenshot from 2020-04-22 12-47-06.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/721e22f2-83d0-4dff-a8bd-031ceec47da1)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 72

**Additional context**
Testing against CI beta with the demo account

**Comment by dlabrecq** [comment]
I'm not able to reproduce with CI beta and cost-demo. 

It's possible there may have been cached code, considering that we refactored the toolbar. However, the toolbars in the details pages looks good to me. 

If this is still an issue, feel free to reopen.

**Comment by lcouzens** [comment]
It seems like this is not reproducible against CI now for w/e reason. That said its still a problem in QA beta/stable and breaking vortex tests. See the screenshot at this link https://ibutsu.cloud.paas.psi.redhat.com/results/5ea2deb47d6fc7ec4a67bc38

I wondered if it was code related but as far as I can tell CI and QA both have the latest code deployed. Take a look at the demo user on QA.

**Comment by dlabrecq** [comment]
I'm looking at QA beta, using the cost-demo user, but don't see any issues with the filter menu.

https://qa.cloud.redhat.com/beta/cost-management/details/ocp?group_by[project]=*&order_by[cost]=desc

**Comment by dlabrecq** [comment]
I'm looking at QA beta, using the cost-demo user, but don't see any issues with the filter menu.

https://qa.cloud.redhat.com/beta/cost-management/details/ocp?group_by[project]=*&order_by[cost]=desc

![Screen Shot 2020-04-24 at 11.53.11 AM.png](https://images.zenhubusercontent.com/5b47705f01db7d22de6439cd/255d99de-ee6d-4c2b-80a4-0f8b95884713)

**Comment by lcouzens** [comment]
Just reproduced it again on CI in Firefix, chrome seems fine.

**Comment by lcouzens** [comment]
Seems like if you go to the details and refresh or hit overview then back to details it then screws up the string.

**Comment by dlabrecq** [comment]
Thanks. It's difficult to reproduce, but have a little more to go on now.

**Comment by dchorvat1** [comment]
verified
