### ISSUE TITLE
Remove tag modal islarge workaround

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1531]
When there are only a few tags, the modal appears too large. Ideally, the modal would shrink to the height of its contents.

We had some workarounds for PatternFly's isLarge / isSmall properties not working properly. We can probably remove those styles now.

<img width="1082" alt="Screen Shot 2020-04-23 at 10 55 10 AM" src="https://user-images.githubusercontent.com/17481322/80116936-8ac2f100-8554-11ea-99f5-70ae44d7d617.png">

**Comment by dchorvat1** [comment]
verified
