### ISSUE TITLE
AWS Sources Wizard flow should specify report file format

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku-ui#1535]
## User Story
As a user I want to create a a cost and usage report properly so that my data can be ingested by cost management.

## Impacts
- UI 
- Docs

## Assumptions
- We want to call out that we specifically do NOT want to enable report data integration for Amazon Athena
- We want to call out that compression type should be `GZIP`

## UI Details
![Screen Shot 2020-04-23 at 3 39 00 PM](https://user-images.githubusercontent.com/3845021/80142078-96c0aa00-8578-11ea-8b4a-ad329b5ae4be.png)

- Options in AWS
![Screen Shot 2020-04-23 at 3 40 35 PM](https://user-images.githubusercontent.com/3845021/80142214-cec7ed00-8578-11ea-9db2-9c2182064a01.png)

## Acceptance Criteria

- [ ] The wizard calls out not to use Athena
- [ ] The wizard specifies GZIP compression

**Comment by chambridge** [comment]
@adberglund do we need a doc update too?

**Comment by adberglund** [comment]
@chambridge Yeah, we do.

**Comment by dayleparker** [comment]
Thanks for the heads-up, Andrew! I've created this JIRA to track the docs update: https://projects.engineering.redhat.com/browse/CRCDOCS-200

**Comment by dlabrecq** [comment]
Created Jira issue https://issues.redhat.com/browse/COST-55
