### ISSUE TITLE
Perspective offers choices that have no data

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku-ui#1536]
**Describe the bug**
When a user only has a cloud source registered (say an AWS source) the default view on the Overview page is `All cloud filtered by OpenShift` which can't have any data if the account has no OpenShift source. 

**To Reproduce**
1. Create an account with only a cloud source type (AWS/Azure)
2. Access the overview page
3. Look at Perspective drop down menu

**Expected behavior**
We should further restrict the perspectives to not include anything OpenShift related when the account does not have an OpenShift source.

**Screenshots**
![Screen Shot 2020-04-24 at 11 07 14 AM](https://user-images.githubusercontent.com/3845021/80227736-0fc50d80-861c-11ea-85e2-d83ff407e2df.png)

**Additional context**
It would be worth looking at the reverse case too, just OpenShift, and make sure we don't show the cloud costs there.

**Comment by dlabrecq** [comment]
We dynamically add options for AWS, Azure, and Ocp usage. However, `All cloud filtered by OpenShift` is always shown -- we can change that.

We will only show the Ocp tab if Ocp providers are available. And the infrastructure tab is shown only if Ocp, Aws, or Azure providers are available.

**Comment by dchorvat1** [comment]
verified
