### ISSUE TITLE
Price list depends on API labels for i18n keys

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1537]
The price list localizes several strings from the cost-model API. The code appears to depend on these API's `label_metric` string as the i18n key for our localized strings? For example, the `node currency rate` i18n key below appears to be one of these labels.

UI price list i18n strings:
```
"price_list": {
      "modal": {
        "cluster currency rate": "Cluster price rate tier {{index}} ({{ unit }})",
        "cpu request rate": "CPU request rate tier {{ index }} ({{ unit }})",
        "cpu usage rate": "CPU usage rate tier {{ index }} ({{ unit }})",
        "memory request rate": "Memory request rate tier {{ index }} ({{ unit }})",
        "memory usage rate": "Memory usage rate tier {{ index }} ({{ unit }})",
        "node currency rate": "Node price rate tier {{index}} ({{ unit }})",
        "storage request rate": "Storage request rate tier {{ index }} ({{ unit }})",
        "storage usage rate": "Storage usage rate tier {{ index }} ({{ unit }})",
        "volume request rate": "Volume request rate tier {{ index }} ({{ unit }})",
        "volume usage rate": "Volume usage rate tier {{ index }} ({{ unit }})"
      }
    },
```

Unfortunately, when the API label changes, or new ones are added, it breaks the UI. See the screenshot below from issue #1513.

![Screenshot from 2020-04-17 12-44-21.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/0218c20d-9143-44b8-a2c0-10feddd3824f)

We need to refactor the code so we don't depend on API labels as i18n keys. Or, the API should localize its own strings.

Looking at the cost-models API, it may be possible to use the metric `name` instead of its `label_metric` property? That ID seems less likely to change.

<img width="359" alt="Screen Shot 2020-04-24 at 11 33 10 AM" src="https://user-images.githubusercontent.com/17481322/80230079-68e27080-861f-11ea-98fa-888903d1f576.png">

**Comment by boaz0** [comment]
Hey @dlabrecq 

I probably didn't understand your suggestion but what will happen when a new metric is added like "memory_kb_usage_per_month"? wouldn't it be shown wrongly because it doesn't exist in `en.json`?

I think the only way to solve it is to keep track on new API metrics or to ask from the backend team to translate the labels in the response.

**Comment by dlabrecq** [comment]
I was basically asking if there may be a better key that we can rely on? Obviously, when a new metric is added, this will break every time.

I agree that the API should be translating its own labels.

**Comment by dlabrecq** [comment]
FYI, I created https://github.com/project-koku/koku/issues/2104 to get the discussion going.

**Comment by dlabrecq** [comment]
IMO, we should not be using the labels as keys. We should display the labels as is. For example, consider creating a string like so:

"rate": "{{metric_label}} tier {{index}} ({{ unit }})",

That way, this won't break when a new metric label is introduced

**Comment by dlabrecq** [comment]
Per today's backlog discussion, the team agreed that the API will localize its own strings. There will be an epic created to discuss this for the next milestone.

Ultimately, when the API returns a translated string (e.g., German, French, etc.), it will not match our i18n keys and the UI will break. Thus, the UI should display the labels as is.

**Comment by dlabrecq** [comment]
Created Jira issue:f https://issues.redhat.com/browse/COST-50
