### ISSUE TITLE
RFE: Clarify duplicate provider error to name the field that has been duplicated

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku-ui#157]
## User Story
When a user attempts to add a provider with an ARN that already exists, a generic error message is displayed "Danger: This field must be unique." and the offending input field has a thin red line. It would be helpful if the error message specifically names which field is in error and the input field should have a better visual that it is in error.

## Impacts
UI

## Role
User

## Assumptions
User is trying to add a provider that already exists

## Acceptance Criteria
An error message names any fields that are in error and the offending input element clearly shows that it is in error with a error icon on the field or full error outline

![hccm_dupe_provider_error](https://user-images.githubusercontent.com/2432396/46678167-11ea8700-cbb2-11e8-9bea-6e68b260fb87.png)

**Comment by dlabrecq** [comment]
@boaz I feel this will be addressed with your new onboarding flow work?

**Comment by boaz0** [comment]
@dlabrecq that's correct.
