### ISSUE TITLE
OCP: Dashboard AWS and OCP tabs

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#169]
## User Story
As a user, I want to tab between AWS and OCP on the dashboard.

## Impacts
UI

## Assumptions
Data is still populated via the AWS API calls

## UI Details

See mocks https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens

## Acceptance Criteria

The dashboard should allow the user to tab between AWS and OCP.

**Comment by chambridge** [comment]
Acceptance Criteria:
- [ ] If user has only AWS provider only the AWS tab will be shown
- [ ] If user has only OCP provider only the OCP tab will be shown

**Comment by dlabrecq** [comment]
Do you mind if we create another issue for these conditions? I'm not sure we can determine if the user has an OCP provider today. And adding a provider is only stubbed out right now, so we would never see the OCP tab.

**Comment by dlabrecq** [comment]
Currently, the empty state for AWS and OCP is shown via each tab. If there is no OCP provider, that tab would show the empty state, instructing the user how to add one. Likewise, the AWS tab would provide similar behavior. Will confirm with @nlcwong.

**Comment by chambridge** [comment]
So if you get the provider data back there is a type associated with a provider currently "AWS" or "OCP".

We can call the API directly to create OCP provider if you don't have time to have the UI modal call it.

I'm fine if you want to address this in a separate issue, just capture the linkage here.

I can see there being an empty state as you described above or you just don't have tabs and a single empty state to create a provider, but I'll leave that to Natalie to design.
