### ISSUE TITLE
Design: Currency conversion

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#17]
Associated with https://app.zenhub.com/workspace/o/project-koku/koku/issues/19

Use Case
========
As a user, I want to be able to view costs in Euros instead of USD so that I can calculate my costs in my native country.

Acceptance Criteria
===============
- [ ] Wireframes/storyboard
- [ ] Review storyboard with UX stakeholders
- [ ] Review storyboard with CMaaS stakeholders

**Comment by nlcwong** [comment]
@chargio Is this a requirement for MVP (Jan/Mar) timeframe?

**Comment by chargio** [comment]
It should be possible to define charges and visualize them in other currencies, yes.

Currency conversion (showing costs in one currency while accruing charges in another currency), can be split into a second use case (reverting the name back to the original).

Steps:
1. Everything is in Dollar
2. The user can see charges in any currency. There is no way to add charges in different currencies.
3. The user can add charges in different currencies, using some online currency conversion system. The charges are stored in the original currency and they have to be converted every time.
4. The user can define currency exchange rates for a period. Normally, those exchange rates will be used for 6 to 12 months, independently on the actual exchange rate provided in real time. The user can select whether to use constant exchange rates or real time ones. (Use case already in Aha!)

**Comment by dlabrecq** [comment]
Decided we will not to port this issue to Jira.
