### ISSUE TITLE
Graphics overlap when making browser narrower and then wider

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#173]
**Describe the bug**
When you make the browser narrower, it ends up being a single column (mobile?). If you get that and then you make it wider again, the cards overlap.

**To Reproduce**
1. Go to dashboard
2. Make the browser as narrow as you can
3. Make the browser wide again
4. See error. All cards overlap.

**Expected behavior**
Cards should not overlap, the behaviour should be the same as the user navigated there from the beginning.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14
 - Browser Chrome
 - Version Ltest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dlabrecq** [comment]
We're using PatternFly 4 cards, so this could be an issue for pf-next?

Unfortunately, I'm not able to reproduce running with locally the Insights proxy. Also tried using http://koku-ui-koku-dev.1b13.insights.openshiftapps.com. Seems to be working on Firefox 61.0.1 and Chrome 69.0.3497.100 on Mac.

Can you please clarify where you're seeing this? Perhaps a screenshot?

**Comment by dlabrecq** [comment]
I was able to reproduce on Firefox using https://koku-ui-hccm-staging.1b13.insights.openshiftapps.com/
