### ISSUE TITLE
PF4: Replace dashboard progress bar with PF4 component

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#180]
## User Story
Replace custom progress bar on dashboard with PatternFly 4 progress component.

## Impacts
UI

## Assumptions
The PatternFly 4 component can achieve the same visualizations

## UI Details

The React based progress component is now available for PatternFly 4

http://patternfly-react.surge.sh/patternfly-4/components/progress

## Acceptance Criteria

The dashboard provides the same level of functionality with the new PF4 components.

**Comment by boaz1337** [comment]
I'll take this, if you don't mind... :inbox_tray:

**Comment by dlabrecq** [comment]
I actually started working on this one. I'm encountering typescript erros with the progress component and have filed issues with PF4.

https://github.com/patternfly/patternfly-react/issues/782
https://github.com/patternfly/patternfly-react/issues/784
