### ISSUE TITLE
Dynamically hide Insights links

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#198]
**Describe the bug**
As a user, I do not want to see the OCP and AWS links in the Insights navigation pane when providers are not available.

**To Reproduce**
1. Login
2. When there are no AWS and/or OCP providers

**Expected behavior**
The "OpenShift Charges" and "AWS" links should not appear in the Insights navigation pane

**Screenshots**
Should look more like this:
![overview - no sources](https://user-images.githubusercontent.com/17481322/47242461-d2dfe100-d3bc-11e8-843b-967035881ffa.png)

**Comment by chambridge** [comment]
Looks like all left hand navigation is going to be controlled in `insights-chrome`. I'm not sure this is doable. Will need to work with Insights front-end team on this.

**Comment by chambridge** [comment]
@dlabrecq @nlcwong 

Looks like all left hand navigation is going to be controlled in `insights-chrome`. I'm not sure this is doable. Will need to work with Insights front-end team on this.

**Comment by dlabrecq** [comment]
Created issue https://github.com/RedHatInsights/insights-chrome/issues/65

**Comment by dlabrecq** [comment]
This won't be fixed. The Insights issue has been closed.
