### ISSUE TITLE
Download Charts as Images (design needed)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#20]
## User Story
As a user, I want to be able to download a chart as an image so that I can reuse it in external tools (presentations, documents, etc).

## Impacts
UI, Docs

## Role
User

## Assumptions

- The user will get the chart as is with no options to change values.
- The download will be a SVG or PNG file.

#Implementation Details
The charts provided on the user interface will provide an option to download the image.

## Acceptance Criteria

- [ ] Verify that a chart image can be downloaded from the user interface dashboard and reflects the same chart seen in the reports page.

**Comment by chambridge** [comment]
@dmiller9911 This was reviewed during the refinement meeting. If you are ok with the definition of the story please move it into the Backlog in Zenhub.

**Comment by nlcwong** [comment]
@chargio is this still a requirement for MVP (Jan/Mar) timeframe?  I honestly do not think so and we should not be in the business of creating charts (tableau can be used for that). If they really want the chart, screenshot.

**Comment by chargio** [comment]
I agree, they should be able to create their own charts if they are capable of downloading the data into excel (with full data, not only summaries)
