### ISSUE TITLE
Download data in chart (Design needed)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#21]
## User Story
As a user, I want to be able to download the data used in a chart as a CSV or JSON file so that I can reuse it in external tools (Excel, Jasper Reports, etc).

## Impacts
API, UI, Docs

## Role
User

## Assumptions
The user will get the data in used to comprised the chart from the API in addition to any data they may have “hidden” based on any interactive selections in the UI.

## Implementation Details
The charts provided on the user interface will provide an option to download the data as CSV/JSON.

## Acceptance Criteria

- [ ] Verify that a chart data can be downloaded from the user interface dashboard and reflects the same chart data seen in the dashboard.

**Comment by chambridge** [comment]
@dmiller9911 This was reviewed during the refinement meeting. If you are ok with the definition of the story please move it into the Backlog in Zenhub.

**Comment by dmiller9911** [comment]
@chambridge Is it expected that the UI will convert the JSON to CSV? I am unsure how large the JSON blob will be.  I am cool to start with UI doing it first and if it is too slow we can reevaluate.

**Comment by chambridge** [comment]
Nope. You should be able to call the API asking for  'text/csv', and get the appropriate data back.

https://github.com/project-koku/koku/issues/154

**Comment by nlcwong** [comment]
@chargio Is this still a requirement for MVP (aka Jan/Mar timeframe)?

**Comment by chargio** [comment]
IT should cover the requirements, if the customer is capable of downloading
all the data so it can be imported into a BI/Excel/etc.

I haven't been able to test it yet as it is not working on the staging
environment.


Sergio Ocón

Product Manager, cost management

Red Hat Inc <https://www.redhat.com>

sergio.ocon@redhat.com    M: +34-692058130
<http://redhatemailsignature-marketing.itos.redhat.com/>
<https://red.ht/sig>
