### ISSUE TITLE
Fix ascending/descending arrow alignment

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#212]
**Describe the bug**
Fix ascending/descending arrow (i.e., in the "month over month change" column) for AWS & OCP detail pages.

**To Reproduce**
1. Go to AWS cost details page (i.e., Cloud Cost)

**Expected behavior**
The ascending/descending arrow should be centered vertically

**Screenshots**
![screen shot 2018-10-20 at 10 35 36 pm](https://user-images.githubusercontent.com/17481322/47262529-85e13500-d4b8-11e8-9e98-e2aaa6e605dc.png)

**Comment by boaz1337** [comment]
https://github.com/project-koku/koku-ui/pull/214 fixes this
