### ISSUE TITLE
Show Costs as defined by the Price List

### ISSUE THREAD

**Issue by blentz** [project-koku/koku-ui#224]
## User Story
As user, I want to define rates so that I see what my OCP environment costs.

## Impacts
UI, Docs

## Role
User

## Assumptions
- Koku API has support for Rate CRUD operations
- Koku API has integrated Rates into OCP Report queries.

## Acceptance Criteria

- [ ] A user should be able to create a new Rate, modify an existing Rate, and delete Rates.
- [ ] A `Rate` should define a `Cost` that applies to a `Metric` and a `Time`. (e.g. $0.25 per CPU-hour, or $0.01 per GiB Network-IO per minute.)
- [ ] A user should be able to see a list of defined Rates.
- [ ] A user should be able to associate a Rate with an Account or OCP Cluster
- [ ] Costs based on the Rate should be visible in Reports and Dashboard Cards.

**Comment by dlabrecq** [comment]
Created an epic. Closing in favor of https://github.com/project-koku/koku-ui/issues/524
