### ISSUE TITLE
Broken Insights navigation links

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#230]
It appears that the Insights CI isn't using the Koku UI navigation config? 

When clicking on the "OpenShift Charge" link, it goes to https://access.ci.itop.redhat.com/insights/platform/cost-management/openshift-charge. The UI is currently configured to be https://access.ci.itop.redhat.com/insights/platform/cost-management/ocp. I'm not advocating one over the other, we just need to be in sync.

**To Reproduce**
1. Click on "OpenShift Charge" in the left-side navigation pane
2. See error

**Expected behavior**
The user should navigate to https://access.ci.itop.redhat.com/insights/platform/cost-management/ocp

**Comment by chambridge** [comment]
@dlabrecq 
Looks like this PR in `insights-chrome` is what changed the behavior of the dynamic left navigation:
https://github.com/RedHatInsights/insights-chrome/pull/49

I'll put in a PR to get these back in sync.

**Comment by chambridge** [comment]
Fixed with https://github.com/RedHatInsights/insights-chrome/pull/62
