### ISSUE TITLE
Overview Page - Font size of card items is miss-sized

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#239]
The font size of the tab texts looks smaller than the bar chart (or progress charts) labels.

1. Go to Cost Management > Overview

![overview cards - font size](https://user-images.githubusercontent.com/31672086/47587810-1c3aae00-d932-11e8-8f4b-1c0f323dc05f.png)

Would think the tab text would be bigger (visually) than the bar chart labels.

**Comment by dlabrecq** [comment]
The progress bar is from PF4, so we may be using an older version of pf-next?

**Comment by christiemolloy** [comment]
In pf-4 the font size for tabs and progress bars is 16px
