### ISSUE TITLE
Add Account button color is hard to read on black background

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#240]
The Add Account button is currently blue, but on a black background, it is hard to read.

1. Go to Cost Management > Overview

![bluebttnonblkbkgrd](https://user-images.githubusercontent.com/31672086/47588065-eba74400-d932-11e8-845f-b58f9c593159.png)

There is a utility that allows the user to set the background color and the components laid out on the panel will adjust appropriately (their color). [https://pf-next.com/components/Button/examples/]( https://pf-next.com/components/Button/examples/)

**Comment by dlabrecq** [comment]
It appears that we're not using the pf-dark theme style from pf-next. The button text should be white?
