### ISSUE TITLE
Dashboard card graph missing legend new month

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku-ui#248]
**Describe the bug**
The graphs on each dashboard card are missing the legend for the new month

**To Reproduce**
1. Navigate to cost-management overview page
2. View any of the dashboard cards and any panel
3. The legend only displays the date range for the previous month and no entry for the current month

**Expected behavior**
The legend has a color entry for the current month and a date range of "Nov 1"

**Screenshots**
![hccm_graph_missing_november_legend](https://user-images.githubusercontent.com/2432396/47853400-fdff0300-ddb4-11e8-9eb0-23d4c5395d9f.png)

**Desktop (please complete the following information):**
 - OS: Fedora 28
 - Browser: Chrome 69 & Firefox 62

**Comment by chambridge** [comment]
API returns placeholder for day:
`Nov 1: []`

UI needs to handle when day exist but no data is available.

**Comment by boaz1337** [comment]
Would it make sense to set the value to 0?

**Comment by dlabrecq** [comment]
@nlcwong This is related to the issues below. We need a design to help determine what to show when there is no data.

https://github.com/project-koku/koku-ui/issues/380
https://github.com/project-koku/koku-ui/issues/381

**Comment by dlabrecq** [comment]
Related to https://github.com/project-koku/koku-ui/issues/450
