### ISSUE TITLE
Cost per service for current month vs. last month 

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#25]
## User Story
As a user, I want to be able to see my Cost by Service for the current month in comparison to the last month so that I can understand my service cost breakdown month-to-month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view cost data for accounts that are visible to them via the AWS organization.

## UI Details
UI will provide a chart/table with the costs broken down by Service for the current month in comparison to the last month.

## Acceptance Criteria

- [ ] The user is able to see the costs for Service but only for the accounts visible via AWS organization for the current month in comparison to the last month

**Comment by dlabrecq** [comment]
Can this be closed?
