### ISSUE TITLE
Unable to logout of UI

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#261]
**Describe the bug**
After login you are unable to log out again using username->logout
Also after clicking on your username the dropdown gets stuck open until you refresh the page. 

**To Reproduce**
1. Go to CI environment dashboard
2. Login to UI
3. Click on username
4. Try to click 'logout'

**Expected behavior**
Logout should happen

**Screenshots**
![screenshot from 2018-11-07 10-29-09](https://user-images.githubusercontent.com/18352403/48127236-20909080-e27b-11e8-939b-cac02677a243.png)

**Desktop (please complete the following information):**
OS: fedora
Browser firefox
Version 63

**Comment by chambridge** [comment]
We don't control this portion of the UI, it is owned by the Insights chroming service. You should open an issue here:
https://github.com/RedHatInsights/insights-chrome/issues

**Comment by lcouzens** [comment]
Oh yeah my bad, thanks Chris. Also just for reference https://github.com/RedHatInsights/insights-chrome/issues/63
