### ISSUE TITLE
Storage trend for the current month vs. the last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#29]
## User Story
As user, I want to see my current storage use and a trend of storage use for the current month in comparison to last month so that understand my storage usage month to month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view storage data for accounts that are visible to them via the AWS organization.

## UI Details
UI will a value for the current storage usage and provide a chart/table with the trend of storage used for the current month in comparison to last month.

## Acceptance Criteria

- [ ] The user is able to see the storage data but only for the accounts visible via AWS organization for the current month in comparison to last month.

**Comment by chambridge** [comment]
@dmiller9911 This was reviewed during the refinement meeting. If you are ok with the definition of the story please move it into the Backlog in Zenhub.

**Comment by dlabrecq** [comment]
I believe this has been implemented per @nlcwong 's mocks. Can this be closed?
