### ISSUE TITLE
OCP Details Page Header - Group by

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#298]
The following mock shows the header of the OCP charges details page with the group by drop down options visible.  
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/332238366_OCPCharge-GrpByProj-DD

The options of the drop down has the options of...
- Projects
- Clusters
- Nodes
- Tag Keys \* TBD: For this option, for MVP we are limiting them to a list of 5 tag keys which would be determined in another modal dialog in the settings section (To be designed).

**Comment by dlabrecq** [comment]
This has been completed
