### ISSUE TITLE
Load language from user preference (Design needed)

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#30]
## User Story
As user, I want to set my preferred language for the UI.

## Impacts
UI, API

## Role
User

## Assumptions
- The user can set their preferred language.
- The UI is displayed in the preferred language.

## UI Details
UI will display a dropdown somewhere for the user to change their language, and persist that in the API. On other page loads, the preferred language will be used.

## Acceptance Criteria

- [ ] The User can set their language
- [ ] The UI displays in the current users preferred language.

**Comment by dlabrecq** [comment]
Would this be handled by the Insights platform now?

**Comment by nlcwong** [comment]
No current MVP plans to support this within Cost Management, but it is assumed that this will be handled from the platform team (to allow a user to prefer language).
