### ISSUE TITLE
Design: Dashboard with Empty State/Zero Data Scenario

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#31]
As a new user to the application, I want to see what financial data (if any) I can see of my IT environment.

**Comment by chambridge** [comment]
Didn't you define this?

**Comment by chambridge** [comment]
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332390378
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332473950
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332474608
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332461857
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332238952
