### ISSUE TITLE
Tagging matching

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#32]
## User Story
As a user, i want to be able to define how things are tagged.
We have different sources for tags:
- On-premises
- AWS
- Azure
- GCP

It is possible that the strategy to set up those tags is different , or even that different strategies have been used in different parts of the providers (i.e. Amazon use by deparment).

We need an UI that allows the user to define how the tags will be stored.

## Impacts
Ex. API, UI, Docs

## Assumptions
-
-

## Acceptance Criteria

- [ ]
- [ ]

**Comment by chambridge** [comment]
I don't believe this is for *Release 1*.

There isn't much in the way of details (investigation around tagging from different providers, implementation, acceptance criteria) ... Perhaps this should be in Aha! for the time being.

**Comment by chargio** [comment]
Closing this an copying it to Aha! until is ready to be introdcued
