### ISSUE TITLE
[BUG] Graphics no showing while using an alias in AWS accounts

### ISSUE THREAD

**Issue by vestival** [project-koku/koku-ui#326]
**Describe the bug**
Graphics no showing while using an alias in AWS accounts

**To Reproduce**
1. Go to https://access.ci.itop.redhat.com/insightsbeta/platform/cost-management/
2. Click on Cloud Cost
3. Expand the alias account
4. See error (no graphic or info is shown)

**Expected behavior**
Info like the shown in the numeric account name

**Screenshots**

![image](https://user-images.githubusercontent.com/6848398/49241346-e775b700-f407-11e8-8c77-e4429b557be0.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by chambridge** [comment]
Fixed with:
https://github.com/project-koku/koku-ui/pull/330
