### ISSUE TITLE
Buttons on chroming do not work

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#327]
**Describe the bug**
The buttons on the chroming do not work

**To Reproduce**
Always

**Expected behavior**
They work

**Screenshots**
![image](https://user-images.githubusercontent.com/7500590/49286807-90212680-f49b-11e8-9c0d-ef381cfbb741.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version latest

**Additional context**

**Comment by chambridge** [comment]
We don't control the buttons mentioned above. Please open the issue against the proper component:
https://github.com/RedHatInsights/insights-chrome/

**Comment by chargio** [comment]
https://github.com/RedHatInsights/insights-chrome/issues/75
