### ISSUE TITLE
Export button does not work

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#328]
**Describe the bug**
The export button does not work

**To Reproduce**
Go to the details page
press the export button

**Expected behavior**
A csv with the information should be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/7500590/49287545-32420e00-f49e-11e8-8bd2-f97dd978514f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version latest

**Additional context**

**Comment by chambridge** [comment]
You have to select items in order to export. The button is disable until a row or all rows are selected.
