### ISSUE TITLE
Cloud cost page uses list view from patternfly3

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#333]
If I understand correctly we should use components from Patternfly Next. Cloud cost and OpenShift Charge pages use `List View` from https://www.patternfly.org/pattern-library/content-views/list-view/  There is no such ui component as `List View` in PF Next, but there is `Data List` https://pf-next.com/components/DataList/examples. I believe koku-ui should use that component instead of outdated `List View`

**Comment by dlabrecq** [comment]
This is an HTML/CSS implementation and not an available component in pf-react.

Please note that we already have issues tor replace PF3 functionality with PF4 -- as the components become available. See: https://github.com/project-koku/koku-ui/issues?q=is%3Aissue+is%3Aopen+label%3APF4
