### ISSUE TITLE
User should not see The "No money screen" while refreshing

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#345]
**Describe the bug**
When the user logs in for the first time, the "No money, no problem" screen appear by default, until the screen is refreshing. It feels like there is a problem with the configuration, not that data is being uploaded.

**To Reproduce**
1. Go to the dashboard

**Expected behavior**
An empty page or a loading page is shown until the information is loaded. If there is no account configured, the screen will be "no money, ...". if there is data, the user will go from an empty (or loading screen) to the actual data.

**Screenshots**

**Desktop (please complete the following information):**
N/A
**Additional context**

**Comment by chambridge** [comment]
@nlcwong This seems to need a design for an intermediate loading view.

**Comment by chargio** [comment]
@nlcwong What is your input here?
I find it quite confusing. The empty state and the loading state are two different things. We will follow your design

**Comment by nlcwong** [comment]
Loading screen design: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/341167609_Overview-LookingForSources

**Comment by boaz0** [comment]
@nlcwong I think we also need a design for a scenario where the request fails: timeout, bad-request, server-error, etc.

I believe something similar to what you did now but with some general message like: "Oops... there was a problem with retrieving the data from the server".

Will that be a problem to add it to invisionapp? I guess I should open a ticket for it too, right?
