### ISSUE TITLE
Data is shown as gb

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#346]
**Describe the bug**
Data in the details page is shown as gb.

**To Reproduce**
Navigate to the details page

**Expected behavior**
The units should be coherent:
GB (international units)
GiB (digital information units)

**Additional context**

**Comment by chambridge** [comment]
Looks like a duplicate of #347 and also does not provide much information. Please place all the bugs content in a single bug with enough information to clearly understand the issue. Screenshots are helpful.

Please use terminology of the application "details page" is unclear. Is the AWS or Openshift related.
