### ISSUE TITLE
Tooltips for the graphics should show current and last month

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#350]
**Describe the bug**
The tooltip only shows one label, not both last month and this month

**To Reproduce**
Hover your mouse over the graphic

**Expected behavior**
There should be two values, as we are comparing them, well differentiated

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7500590/49790902-959a2e80-fd2f-11e8-9f04-64f5b88671eb.png)

**Comment by dlabrecq** [comment]
You're looking at the tooltip for the month of November. The data point for December is just above that, on the blue line. If you want to see the tooltip for December, you must hover over the blue line.

Note that the PF4/Victory charts are functioning as designed.

**Comment by chargio** [comment]
I had that conversation with @nlcwong. Is it possible to show the two points together? This is comparing the two values, it would add value to show both

**Comment by dlabrecq** [comment]
Using the OCP dashboard as an example, do we really want to show 4 values in a single tooltip? You would also get the same tooltip for all 4 lines.

**Comment by chargio** [comment]
I would show them two to two if that is possible: last month vs this month for reserved and usage.

**Comment by dlabrecq** [comment]
Did some testing with Victory and it doesn't support what you're looking for out of the box. It may still be possible to do something with a custom tooltip component, but will need a design.

**Comment by dlabrecq** [comment]
The tooltips currently show data points for each month for a given day. Will clean up tooltip labels via the fit and finish effort.
