### ISSUE TITLE
When opening the details page the information shown the first time is wrong

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#352]
**Describe the bug**
The default view of the graphics is not showing the information that describes the drop-down, but the same that is described in grouped charges by

**To Reproduce**
1. Go to the details page for OCP
2. Select group by (anything would do)
3. Expand one row to show the graphic

**Expected behavior**
The graphic and legend should correspond to the one that is selected by default within the project

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7500590/49791535-fd04ae00-fd30-11e8-9ec8-93ca241709eb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chargio** [comment]
If I refresh I get the proper image
![imagen](https://user-images.githubusercontent.com/7500590/49791589-17d72280-fd31-11e8-9ac8-748684887bdc.png)

**Comment by dlabrecq** [comment]
These pages are still a work in progress as the APIs were literally just made available.

Please note that the OCP page was a copy of AWS. As a result, we still have the old AWS chart in the list item row.

This will be replaced with a bullet chart. In fact, I'm slated to work on it for this sprint 15.

Note that we have already created issues for this work.

**Comment by dlabrecq** [comment]
Closing as we already have the issues below for adding functionality to the details.

Bullet charts:
#200
#199
#321
#320
#319
#318
#293
#292

Top 3/5 projects:
https://github.com/project-koku/koku-ui/issues/310
