### ISSUE TITLE
Overview page for OCP has 'other items' listed first in Top 5

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#355]
**Describe the bug**
When we have other items with a value higher than any single item it appears first in the top 5 list.

**To Reproduce**
1. Add OCP provider with more than 5 projects
2. Navigate to OCP Overview screen 
3. Look at top items on any card

**Expected behavior**
After discussing with @nlcwong we expect to see highest value top 5 items then everything else grouped under other.

**Screenshots**
![screenshot from 2018-12-12 16-49-31](https://user-images.githubusercontent.com/18352403/49891860-7ab6df80-fe3f-11e8-92db-11bf1f2a002d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome V66

**Additional context**
I just checked out AWS data and there is similar happening there.

![screenshot from 2018-12-12 19-05-37](https://user-images.githubusercontent.com/18352403/49892811-c79bb580-fe41-11e8-9207-0750087b9f5c.png)

The position of other is clearly based from its collected value, but it should stay below the top 5 items so we can quickly see the top 5 ranking. The mocks show it at the bottom but to be fair the value is also lower so hard to compare exactly.
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens

**Comment by chambridge** [comment]
@nlcwong is going to "user test" this to get clarity on whether Other should be at the top or bottom.
