### ISSUE TITLE
Use Insights Proxy for local development

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#36]
The insights apps make use of a chroming service that utilizes edge side includes from Akamai. To facilitate local development the insights team provides a proxy to run locally to simulate this environment.

https://github.com/RedHatInsights/insights-proxy

**Comment by chambridge** [comment]
Are we still doing this?

**Comment by chambridge** [comment]
Deferred to R2

**Comment by chambridge** [comment]
Worked with:
https://github.com/project-koku/koku-ui/issues/118
