### ISSUE TITLE
Show a warning when there are gaps in OKD graph data.

### ISSUE THREAD

**Issue by blentz** [project-koku/koku-ui#380]
## User Story
As a Koku-UI user, I want to see a warning when there are gaps in the graphed data so that I know there is a problem with retrieving data from my OKD clusters.

## Impacts
UI

## Assumptions
- UI can detect missing values within the data returned by Koku-UI
- If required, Koku could return metadata when data set is incomplete (please open an issue to implement this, if it is required.)

## UI Details
There are two reasons why a particular data point might be zero or undefined. It will either be because there is no usage at all or because there is a connectivity problem (e.g. Operator Metering is not running or misconfigured).

So, when a data set has gaps - a zero or undefined value for a particular day/month - we should show a warning that says something along the lines of "We noticed unexpected values in the data. Please double-check that data collection is functioning normally."

## Acceptance Criteria

- [ ] If customer OKD data set has values for the whole time period, no warning is shown.
- [ ] If customer OKD data set is missing values within the time period, a warning is shown indicating there may be a problem with their OKD cluster.

**Comment by dlabrecq** [comment]
Also related to https://github.com/project-koku/koku-ui/issues/248

**Comment by nlcwong** [comment]
We should not use the graphs as a warning mechanism about source collection status. That should be done elsewhere.  These graphs will be used for reports, not necessarily to show status of a cluster's metric collection.
