### ISSUE TITLE
Graphs should show an extrapolation for missing data

### ISSUE THREAD

**Issue by blentz** [project-koku/koku-ui#381]
## User Story
As a Koku-UI user, I want my graphs to show dotted-line extrapolations for periods with missing data so that my graphs are less disrupted by missing data points.

## Impacts
UI

## Assumptions
- Koku-UI or Koku-API can detect missing data points within a data set
-

## UI Details
The MVP for this is a basic linear extrapolation.

Given the following data set:
```
Jan-01: 10
Jan-02: 20
Jan-03: None
Jan-04: None
Jan-05: 50
```
The graph should show a solid line from Jan-01 to Jan-02, then a dotted-line connecting the values of Jan-02 to Jan-05, then a solid line from Jan-05 on forward.

## Acceptance Criteria

- [ ] A graph with no missing data should display normally
- [ ] A graph with missing data points should show an extrapolation line to cover the window of missing data. 

**Note:** This issue says "dotted-line", but that is not a strict requirement. The actual implementation can be different - whether it's a different line color or line weight or some other design choice is fine. The goal is simply that the user should be able to see an extrapolation across the missing data and know that it's an extrapolation, not actual data points.

**Comment by dlabrecq** [comment]
Also related to https://github.com/project-koku/koku-ui/issues/248

**Comment by chargio** [comment]
Can we consider that today is within this use case?
Meaning: today is not 24 hours, so the costs are almost always showing a bar going down. We could use dotted lines when the data is not 24h long, as the graphic is quite visible.

**Comment by dlabrecq** [comment]
The Victory charts already extrapolate between lines of data. (Victory just cannot extrapolate without data at the end or beginning of a dataset.) In the example below, we only have previous cost data for March 1-5 and March 26-31; however, the Victory chart still connects the lines.

Previous data extrapolation:
![Screen Shot 2019-04-24 at 1 53 07 PM](https://user-images.githubusercontent.com/17481322/56681881-547c3880-6698-11e9-9c29-d223ece4d34d.png)

Raw data:
![Screen Shot 2019-04-24 at 1 35 21 PM](https://user-images.githubusercontent.com/17481322/56681210-d4090800-6696-11e9-8268-8ad7bd25b944.png)

Unfortunately, Victory does not provide functionality to change the extrapolation color or make just that segment a "dotted-line". Victory also cannot provide tooltips for days without data.

It may be possible to overlay yet another chart on top? However, some of our charts have up to 4-8 lines of data already, so adding extrapolation colors/dotted-lines for each could create a bit of clutter.

**Comment by chargio** [comment]
Is this something that should be solved in Patternfly? Shoud we open an issue there?

**Comment by dlabrecq** [comment]
I don't believe this is a PatternFly issue, since this use case is specific to Cost Management.

**Comment by blentz** [comment]
@dlabrecq - I care more that it does extrapolation than how it's drawn. So, if the behavior is already there, that's good enough. :smile:

**Comment by dlabrecq** [comment]
Thanks, that's good to know. If we need to represent extrapolation differently, we can reopen.
