### ISSUE TITLE
Open Detail Item in OpenShift Costs page failure

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#399]
**Describe the bug**
When expanding a project on the Openshift charge page. it blow up.

**To Reproduce**
1. Go to `OpenShift Cost` on the left navigation
2. Click on the expand arrow icon in any row from the results
3. The table disappears

**Expected behavior**
Content is expanding successfully.

**Screenshots**
![error bug 1](https://user-images.githubusercontent.com/2453279/50905885-7ffe4e80-142c-11e9-9469-18ca066dce12.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 63.0.3

**Comment by boaz0** [comment]
//cc @lcouzens

**Comment by dlabrecq** [comment]
This is a known issue -- I filed the issue below with Insights.

https://github.com/RedHatInsights/insights-chrome/issues/87

I have not been successful debugging insights beta myself, but welcome you're input as to why this may be happening?

**Comment by dlabrecq** [comment]
Replaced the PF3 bullet chart, on the OCP details page, with a custom component based on PF4 (Victory) charts.
