### ISSUE TITLE
Add provider modal provider type ID changes

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#401]
**Describe the bug**
Add provider source modal has a dropdown for selecting OCP/AWS there is no test-id and the id for the element changes making automation difficult at best. 

**To Reproduce**
1. Browse to Overview page
2. Click Add a source
3. Inspect dropbown element 
4. cancel/refresh page
5. Click add source again
6. inspect dropdown element again

**Expected behavior**
All elements should have a unique test-id

Element details:
<select aria-label="provider type selector" id="Provider Type4" class="pf-c-form-control" aria-invalid="false"><option class="" value="AWS">AWS</option><option class="" value="OCP">OCP</option></select>

**Screenshots**
![screenshot from 2019-01-11 17-07-29](https://user-images.githubusercontent.com/18352403/51048633-6ba08a00-15c3-11e9-8595-de69e363ca7d.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox

**Comment by dlabrecq** [comment]
This modal is in the process of being completely replaced by https://github.com/project-koku/koku-ui/issues/201. I'll make a note there to ensure test IDs are added properly.

**Comment by boaz0** [comment]
@dlabrecq I actually forgot about this. I will add this soon.
Thanks for the heads up!
