### ISSUE TITLE
OCP overview cards not loading and blowing up page

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#413]
**Describe the bug**
OCP overview cards not loading and blowing up page

**To Reproduce**
1. Add OCP provider
2. Navigate to OCP overview cards

**Expected behavior**
UI overview cards should load correctly and show OCP data

**Screenshot""
![screenshot from 2019-01-18 20-54-16](https://user-images.githubusercontent.com/18352403/51412368-441d6480-1b63-11e9-9d52-5bbd63845a10.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 66

**Additional context**
Data loads correctly if I hit the OpenShift Charge page

Console error
```[KEYCLOAK] Token refreshed
chrome.js:74 [KEYCLOAK] Estimated time difference between browser and server is 1 seconds
chrome.js:74 [KEYCLOAK] Token expires in 899 s
react-dom.production.min.js:179 TypeError: Cannot read property 'forEach' of undefined
    at i (getComputedOcpReportItems.ts:58)
    at s (getComputedOcpReportItems.ts:4)
    at g (chartUtils.ts:41)
    at Object.render (ocpDashboardWidget.tsx:83)
    at oa (react-dom.production.min.js:163)
    at ia (react-dom.production.min.js:162)
    at fa (react-dom.production.min.js:169)
    at $a (react-dom.production.min.js:204)
    at Ka (react-dom.production.min.js:205)
    at Oi (react-dom.production.min.js:220)
ya @ react-dom.production.min.js:179
```
Network response:
```
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 13.1 KB | 19.71 s
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | (from disk cache) | 10 ms
?filter[time_scope_units]=month&filter[time_scope_…tion]=monthly&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | (from disk cache) | 39 ms
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 21.6 KB | 22.62 s
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 35.3 KB | 20.80 s
?filter[time_scope_units]=month&filter[time_scope_…tion]=monthly&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 1.6 KB | 20.09 s
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 21.7 KB | 18.62 s
?filter[time_scope_units]=month&filter[time_scope_…lution]=daily&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 35.1 KB | 22.62 s
?filter[time_scope_units]=month&filter[time_scope_…tion]=monthly&filter[limit]=5&group_by[project]=* | 200 | xhr | xhr.js:178 | 20.0 KB | 17.70 s
 
```

**Comment by chambridge** [comment]
Based on the flow I can only guess this is the problem:
https://github.com/project-koku/koku-ui/blob/master/src/utils/getComputedOcpReportItems.ts#L108

**Comment by lcouzens** [comment]
Looks like there was a few weird responses from some of the API calls too some look ok like the first one here, but the second looks like it can't access something.
[response.txt](https://github.com/project-koku/koku-ui/files/2774860/response.txt)
[response-2.txt](https://github.com/project-koku/koku-ui/files/2774859/response-2.txt)

**Comment by boaz0** [comment]
I couldn't reproduce it on CI environment.

@lcouzens can we take this offline and see if there is a way you can show me how you reproduce it.

I guess that @chambridge feeling is right. We are not properly validating the `report` argument before parsing it.
