### ISSUE TITLE
Historical graphs not showing previous month data

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#414]
**Describe the bug**
Historical graphs not showing previous month data

**To Reproduce**
1. Add OCP provider
2. Navigate to OpenShift Charge
3. Expand project item
4. Click on 'View Historical Data'

**Expected behavior**
Graphs showing historical month over month data

**Screenshots**
![screenshot from 2019-01-18 22-39-24](https://user-images.githubusercontent.com/18352403/51416872-4edff580-1b73-11e9-967b-d40aadd064b0.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
I am only seeing this issue on Historical data graphs, the data show on the overview page shows month over month data correctly and I can also see the previous month data in the API

**Comment by dlabrecq** [comment]
Looks correct locally and on Insights beta. 

Please note that if there is no previous month data, there is nothing for the UI to show.

Is this nise data? I don't recognize the "grow_dev's" project name.

**Comment by lcouzens** [comment]
This is Nise data again but I have previous month data which I can see in the API and in the overview page cards too. Just seems to be an issue with the historical graphs on production. Should be able to look at the qa account.
![screenshot from 2019-01-23 16-33-41](https://user-images.githubusercontent.com/18352403/51621924-72b58980-1f2d-11e9-8b12-48c6a12f5435.png)
![screenshot from 2019-01-23 16-31-49](https://user-images.githubusercontent.com/18352403/51621938-78ab6a80-1f2d-11e9-904e-38a0ac30cba2.png)

**Comment by dlabrecq** [comment]
You might try closing the modal and opening that again. It's possible that the list item you just expanded has not finished loading? 

I've noticed that the historical charts don't always load completely, when I rush to click on the "View Historical Button". I'm thinking we could disable that button until everything has loaded?

**Comment by dlabrecq** [comment]
I've been working with the historical modal (updating per high fidelity mocks) and no longer see the issue -- I've probably refreshed 100+ times during development.

Closing since https://projects.engineering.redhat.com/browse/RHIPLAT2-338 is marked completed. Feel free to reopen if encountered, again.
