### ISSUE TITLE
Historical graph data does not scale well

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#415]
**Describe the bug**
Historical graph data does not scale well, it seems some of the graph lines get cut at the top and the legend is difficult to read as text/color blocks seem to overlap.

**To Reproduce**
1. Add OCP provider
2. Navigate to OpenShift Charge
3. Expand project item
4. Click on 'View Historical data' button

**Expected behavior**
A clean/clear graph and legend that's easy to read 

**Screenshots**
![screenshot from 2019-01-18 22-58-49](https://user-images.githubusercontent.com/18352403/51417239-f7db2000-1b74-11e9-8345-a9a9d081650d.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 66

**Additional context**
Just for some context, I was running this on a full screen browser on a 1920x1080 resolution. Also on a side note sometimes the legend colors don't match the graphs lines.
![screenshot from 2019-01-18 22-39-24](https://user-images.githubusercontent.com/18352403/51417460-0544da00-1b76-11e9-9905-2e92ab22544e.png)

**Comment by dlabrecq** [comment]
The "does not scale well" comment is somewhat subjective. Please note that we have high fidelity mocks to change the colors and legend layout, which will help with the crowding. This is still a work in progress.

**Comment by dlabrecq** [comment]
Closing in favor of the high fidelity work below.

https://github.com/project-koku/koku-ui/issues/397
