### ISSUE TITLE
Long list of tags shown on details page for each project/cluster could lead to bad user experience

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#416]
**Describe the bug**
Currently when you expand a project or cluster to see bullet charts we also see tags relevant to that item. This can be a real issue if you have more than 8 tags associated with an item. Depending on how many tags one might have you could end up with some endless scrolling. Not sure on the best resolution here but some sort of a-z grouping might be an option.

**To Reproduce**
1. Add OCP provider
2. Navigate to OpenShift Charge
3. Expand item
4. See list of tags associated with item

**Expected behavior**
A clean set of details for the item

**Screenshots**
![screenshot from 2019-01-18 23-13-57](https://user-images.githubusercontent.com/18352403/51418009-e3008b80-1b78-11e9-97cb-66c74b7fff2b.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 66

**Comment by dlabrecq** [comment]
@nlcwong is iterating on the design.
