### ISSUE TITLE
Openshift charges table background is scrolling

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#419]
**To Reproduce**
1. Go to 'OpenShift Charges'
2. Scroll down for a while
3. The background is scrolling as well

**Expected behavior**
The background shouldn't be scrolled.

**Screenshots**
![screenshot_20190121_105440](https://user-images.githubusercontent.com/1011257/51466790-4d791d80-1d6b-11e9-9d5b-daf3e7c8b21f.png)
![screenshot_20190121_105607](https://user-images.githubusercontent.com/1011257/51466796-4f42e100-1d6b-11e9-8850-c37a35b59ff7.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 64

**Comment by boaz0** [comment]
I don't think it's a bug.

//cc @nlcwong @dlabrecq

**Comment by quarckster** [comment]
If you look in to other pages, you can see the difference.

**Comment by dlabrecq** [comment]
The Insights platform appears to add the background to all pages. The details page uses a div with a different color to essentially hide the background. The div container already uses `min-height: 100%`; however, the PF3 list may be extending beyond its container? 

Ideally, we would be using paginated data and this wouldn't be an issue. We have an issue to replace the PF3 list with a PF4 table or data list component -- perhaps that may help?

**Comment by dlabrecq** [comment]
We've replaced the PF3 list with a PF4 table and I no longer see the issue in production. I'm looking at a table in the OCP Details page with 28 rows and there is no background showing.
