### ISSUE TITLE
RFE List of current sources added and the option to remove them

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#423]
## User Story
As a user I want to be able to see the current sources I have added and the option to remove them

## Impacts
UI

## Assumptions
- Providers have already been added

## UI Details
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/337454507_SourcesList

## Acceptance Criteria

- [Some list view of current providers]
- [Option to delete one or many providers]

**Comment by dlabrecq** [comment]
Created an epic. Closing in favor of https://github.com/project-koku/koku-ui/issues/523
