### ISSUE TITLE
Download icon and text

### ISSUE THREAD

**Issue by karelhala** [project-koku/koku-ui#436]
**Describe the bug**
When downloading report in cost management there is different icon and behavior as is in rest of insights. Please use [@red-hat-insights/insights-frontend-components/Components/DownloadButton](https://github.com/RedHatInsights/insights-frontend-components/tree/master/src/PresentationalComponents/DownloadButton) component to be consistent.

**To Reproduce**
Every download/export button.

**Comment by dlabrecq** [comment]
@nlcwong I don't believe that is how our export is expected to be used.

**Comment by dlabrecq** [comment]
@nlcwong I'm planing to use PF4's ExternalLinkSquareAltIcon icon per Kyle's high fidelity mocks below.

ExternalLinkSquareAltIcon:
![screen shot 2019-02-18 at 4 19 17 pm](https://user-images.githubusercontent.com/17481322/52976822-fd589f80-3398-11e9-8101-6ce86a726ff2.png)

Kyles Mock:
https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165166

**Comment by nlcwong** [comment]
@dlabrecq sounds good!
@karelhala we have high fidelity mocks that we were told will become the export icon for PF4. Also in terms of behavior, we have a requirement to give the user the ability to select the type of data they are to export.
