### ISSUE TITLE
Current source button/data disappears when you add a new source

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#437]
**Describe the bug**
Current source button/data disappears when you add a new source

**To Reproduce**
1. Add a source AWS
2. Add another source OCP
3. Tab button to switch to previous source cards on overview disappear 

**Expected behavior**
New source should be added to current view

**Screenshots**
![screenshot from 2019-01-28 14-01-03](https://user-images.githubusercontent.com/18352403/51841808-618ec300-2307-11e9-8575-dc0348de79ae.png)
![screenshot from 2019-01-28 14-00-17](https://user-images.githubusercontent.com/18352403/51841819-6784a400-2307-11e9-82ea-ffba86f1f28f.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 66

**Additional context**
This happens in both cases whether you add AWS first or OCP first, the second alt add removes the first.
Work around: Refreshing the page loads both tab

**Comment by dlabrecq** [comment]
@boaz0 perhaps this is something you can look at while implementing the new onboarding flow?

**Comment by boaz0** [comment]
No problems. Will work on that.

**Comment by dlabrecq** [comment]
I believe this may be related to https://github.com/project-koku/koku-ui/issues/453?

**Comment by lcouzens** [comment]
Possibly, not sure though as this is an issue with only 2 providers are added so it shouldn't be hitting the pagination problem.

**Comment by dlabrecq** [comment]
The providers API now supports a type query parameter. I've refactored the code to obtain the AWS and OCP counts separately. I believe that change should also resolve the issue.
