### ISSUE TITLE
OCP overview cards scale text badly

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#438]
**Describe the bug**
OCP overview cards scale text badly

**To Reproduce**
1. Add OCP provider
2. Navigate to OpenShift Container Platform (Overview)
3. Resize the browser/window
4. Graph legend text goes outside card border

**Expected behavior**
Text/graphs should resize cleanly

**Screenshots**
![screenshot from 2019-01-28 15-30-56](https://user-images.githubusercontent.com/18352403/51846624-dcf57200-2311-11e9-9630-e191363f025b.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 66

**Additional context**
AWS overview cards do not seem to suffer from this issue.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/project-koku/koku-ui/pull/443
