### ISSUE TITLE
Validate cluster id duplication

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#439]
**Describe the bug**
Cluster ID is unique and we would like to validate that on client side.
The way to validate that on client side is by using the provider list when loading the overview page.
However, what happens if that list wasn't received yet and the user is entering the Cluster ID.

In that scenario it's not clear what we should do.

**To Reproduce**
1. After Login go to the onboarding wizard
2. Click on OCP in type and enter the source name
3. Follow the instructions till you get to Usage Collector part
4. Make sure the dashboard aren't loaded yet and enter a Cluster ID that is already entered

**Expected behavior**
Show a message that can't validate unique Cluster ID?
Maybe keep the unique validation on the server side and have a way to go back and change it in case the Adding request fails.

//cc @nlcwong 

related to #434 and to #201

**Comment by dlabrecq** [comment]
The overview page already makes a request for the AWS and OCP providers. However, that list is paginated and we would need to make multiple requests to search for a cluster ID. 

Currently, we simply use these requests to see if we have at least one AWS and/or OCP provider.

That said, I know the providers API was changed to allow fetching a particular provider. Not sure how helpful that would be (i.e., would it contain the cluster ID you're looking for)?

**Comment by dlabrecq** [comment]
@boaz0 Would you please take this one, considering it's related to the onboarding flow?

**Comment by boaz0** [comment]
No problem. I just want to talk with @nlcwong before to see if what I have in mind correlates to her design

**Comment by dlabrecq** [comment]
FYI, the API reports now include cluster IDs and aliases. However, the provider API still provides paginated data.

Is this still something we want to validate client side?

**Comment by boaz0** [comment]
No, we eventually are going to relay on the server side validation and jump to the right step to edit that property.

**Comment by dlabrecq** [comment]
Ok, I will close this issue.
