### ISSUE TITLE
Overview link stops working after navigation to Cloud Cost or OpenShift Charge

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#441]
**Describe the bug**
Overview link stops working after navigation to Cloud Cost or OpenShift Charge

**To Reproduce**
1. Navigate to Cost Management - OpenShift Charge
2. Click on Overview link
3. Link is highlighted but page does not load

**Expected behavior**
Overview page should load correctly

**Screenshots**
![screenshot from 2019-01-30 09-29-27](https://user-images.githubusercontent.com/18352403/51971787-e5fd5500-2471-11e9-83dd-cbd0eb84462d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 66

**Additional context**
Cloud Cost and OpenShift Charge links continue to work as expected.

**Comment by dlabrecq** [comment]
This is an Insights issue

https://github.com/RedHatInsights/insights-chrome/issues/137

**Comment by lcouzens** [comment]
Fixed
