### ISSUE TITLE
Onboarding: Move "Add Source" button

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#446]
**Describe the bug**
As a user, I want to add a source via the gear icon from the Insights masthead.

**To Reproduce**
1. Go to 'Overview'
2. Click on the gear icon
3. Scroll down to 'Add Source'

**Expected behavior**
The "Add Source" button is replaced by an option in the gear icon / menu. Clicking on that option should launch the sources list page, similar to the current "Add Source" button.

**Additional context**
- FYI, the platform is (as of today) still designing a centralized Settings page that will (hopefully launched from the gear) that we can plop our "button" into to launch our own sources page for tech preview or until sources supports cost (which will be post-summit). So please hold off until i can get some direction from platform to coordinate new launch location.
- May need to get the platform to provide an API for us to modify the gear icon?

**Comment by nlcwong** [comment]
FYI, the platform is (as of today) still designing a centralized Settings page that will (hopefully launched from the gear) that we can plop our "button" into to launch our own sources page for tech preview or until sources supports cost (which will be post-summit).  So please hold off until i can get some direction from platform to coordinate new launch location.

**Comment by dlabrecq** [comment]
This use case is no longer valid. We are now planning to launch the sources page from the Insights settings area.
