### ISSUE TITLE
Cost pages show no data at the beginning of the month

### ISSUE THREAD

**Issue by psav** [project-koku/koku-ui#447]
**Describe the bug**
The Cost pages don't show previous months data and have no way to get to it, meaning that when the first of the month rolls around, it is difficult for a user to continuing assessing reports. Perhaps having the option of a static month or a rolling month option could be a better idea.

**To Reproduce**
1. Visit the Cost page on the first of the month

**Expected behavior**
Some kind of access to previous months data in the UI is essential for customers to continue to asses costs.

**Comment by chambridge** [comment]
I've assigned this to @nlcwong as this is a design issue that has been discussed before, but really needs user feedback.

**Comment by dlabrecq** [comment]
Related to https://github.com/project-koku/koku-ui/issues/450

**Comment by chargio** [comment]
Is it possible for the API to return 0 in day one until we have data?
So the legend and the data point are populated in the UI. That would show the main problem here, that is the lack of feedback of what is going on.
I will explore other options with UI separately.

**Comment by dlabrecq** [comment]
The API now returns an empty list, which is length 0. We can check that, but we still have no data to show in the chart. There's no "data point" to populate the chart. 

My question is, do we show the legend, regardless if there is data shown in the chart?

**Comment by chargio** [comment]
Yes, we should show the legend, as it is now is confusing. Shouldn't the API come back with a data point that is 0?

**Comment by chambridge** [comment]
I think the API is responding correctly. It’s good to be able to differentiate between having no data and having data that resulted in a value of zero.

**Comment by dlabrecq** [comment]
Per an email conversation between @chargio and @nlcwong, the solution we're proposing is to show the previous two months, on the first of each month. For example, for March 1st, we want to continue showing data for February and January. Then, we would begin showing data as normal on March 2nd. 

This will allow us to collect a full day's worth of data, helping to ensure we have data to show in the details page. Project details will now become accessible and users could continue viewing historical charts. Likewise, the charts and progress bars shown in the overview page would be populated instead of displaying blank states.

**Comment by dlabrecq** [comment]
Currently, the APIs do not support the proposed solution. I opened the feature request below, but understand it's not a simple request and requires a significant amount of work.

https://github.com/project-koku/koku/issues/669

**Comment by dlabrecq** [comment]
"Sergio views this as low-priority. So, this can be included in the time-scope re-engineering discussion." -- See https://github.com/project-koku/koku/issues/669

**Comment by nlcwong** [comment]
@dlabrecq should this be closed out?

**Comment by dlabrecq** [comment]
Perhaps we can reopen this particular issue when the APIs provide support? In the mean time, issue project-koku/koku#669 has been created with Koku.

**Comment by dlabrecq** [comment]
We will close this issue in favor of project-koku/koku#669. An epic will be created in Jira, instead.
