### ISSUE TITLE
Dropdown name/text is not consistent between elements on details pages

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#449]
**Describe the bug**
Dropdown name/text is not consistent between elements on details pages

**To Reproduce**
1. Navigate to cloud cost or openshift charge
2. See Group cost by and Sort by

**Expected behavior**
Both dropdowns should be shown with name and selection

**Screenshots**
![screenshot from 2019-02-01 14-46-46](https://user-images.githubusercontent.com/18352403/52130591-7c787480-2632-11e9-94b0-1c30907d35f6.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 66

**Comment by dlabrecq** [comment]
This was done intentionally, per the mocks below.

See: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/323822460

<img width="923" alt="screen shot 2019-02-01 at 9 58 30 pm" src="https://user-images.githubusercontent.com/17481322/52158994-88812800-266c-11e9-9f64-9914ba4b80e7.png">

Not sure I agree that the dropdown labels must be the same, but that's @nlcwong 's call? Regardless, the sort dropdown will be removed shortly in favor of the sort functionality provided by the PF4 table. 

Ultimately, the page will look more like this mock, but without the sort menu:

https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165166

That said, we have an issue for that work; thus, I will close this one in favor of https://github.com/project-koku/koku-ui/issues/207
