### ISSUE TITLE
Tool tip box does not scale to fit current text on pie charts

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#457]
**Describe the bug**
Tool tip box does not scale to fit current text on pie charts

**To Reproduce**
1. Add AWS provider
2. Navigate to Cloud Cost
3. Expand an account
4. Hover over pie chart segment

**Expected behavior**
Clear readable tool tip pops up with segment name

**Screenshots**
![screenshot from 2019-02-06 10-39-43](https://user-images.githubusercontent.com/18352403/52336164-13ab4680-29fc-11e9-8acb-996adad16a51.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 65

**Comment by dlabrecq** [comment]
This is a bug with Victory / PF4. Regardless, the pie chart is being replaced with bar charts. Therefore, I'll close this issue in favor of https://github.com/project-koku/koku-ui/issues/462
