### ISSUE TITLE
Slow render and interaction of OpenShift charge

### ISSUE THREAD

**Issue by karelhala** [project-koku/koku-ui#469]
**Describe the bug**
With couple of rows present in OpenShift Details table it takes a lot of time before the data are loaded and when interacting with the table. And a lot of requests are fired, this makes using the table really hard.

**To Reproduce**
1. Go to OpenShift Details
2. Wait for render

**Expected behavior**
Table is loaded faster and when clicking on each row new query is sent and detail is rendered.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Additional context**
To fix this problem you might want to consider using this code (with a bit of improvements done to loading div). Basically load data and render them only if row is expanded to shave both render and fetch time from server.
```diff
diff --git a/src/pages/ocpDetails/detailsTable.tsx b/src/pages/ocpDetails/detailsTable.tsx
index 21df166..bf97d1c 100644
--- a/src/pages/ocpDetails/detailsTable.tsx
+++ b/src/pages/ocpDetails/detailsTable.tsx
@@ -115,11 +115,13 @@ class DetailsTableBase extends React.Component<DetailsTableProps> {
             this.getTotalCost(item, index),
           ],
           isOpen: false,
-          item,
+          tableItem: {
+              groupById, query, index, item
+          }
         },
         {
           parent: index * 2,
-          cells: [this.getTableItem(item, groupById, query, index)],
+          cells: [<div key={`${index*2}-child`}>Loading</div>],
         }
       );
     });
@@ -261,7 +263,14 @@ class DetailsTableBase extends React.Component<DetailsTableProps> {
 
   private handleOnCollapse = (event, rowId, isOpen) => {
     const { rows } = this.state;
+    const { tableItem: { item, groupById, query, index } } = rows[rowId];
     rows[rowId].isOpen = isOpen;
+    if (isOpen) {
+      rows[rowId + 1].cells = [this.getTableItem(item, groupById, query, index)];
+    } else {
+      rows[rowId + 1].cells = [<div key={`${index * 2}-child`}>Loading</div>];
+    }
+
     this.setState({
       rows,
     });

```

When I had 30 rows it took 60s to render. With this diff applied it renders in 5s. Collapse and expand took about 10s to render, now it's less than 2s.

**Comment by karelhala** [comment]
ping @dlabrecq you might be interested in this issue.

**Comment by dlabrecq** [comment]
Thanks. Will give that a try

**Comment by dlabrecq** [comment]
FYI. I created a PR here: https://github.com/project-koku/koku-ui/pull/471

Thanks, again!
