### ISSUE TITLE
Design: common header for all content pages

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#47]
All content pages should have a similar header style (which includes a navigational breadcrumb) so the user has an easier time orienting themselves around the application.

## Impacts
- API: maybe
- UI: definitely
- Docs: maybe

## Role
- User who is an admin/operator

## Assumptions
- The information architecture matches the user's mental model
- PF4 styling will be available

## UI Details
- Will need styling help

## Acceptance Criteria
- [ ] Consulted with Mgmt UXD stakeholders
- [ ] Consulted with HCCM stakeholders
- [ ] Consulted with UXD Visual design to make sure PF4 compliant
- [ ] Update designs to affected Invision prototype(s)

**Comment by chambridge** [comment]
Assuming this is more or less handled by Insights Platform. Closing for now; reopen if necessary.
