### ISSUE TITLE
'No data was found' page shown when adding an AWS local provider only

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#470]
**Describe the bug**
'No data was found' page shown when adding AWS local provider only

**To Reproduce**
1. Go to api/v1/providers/
2. Added AWS-local provider
3. Navigate to Overview page

**Expected behavior**
Should see data for local provider

**Screenshots**
![screenshot from 2019-02-11 12-51-34](https://user-images.githubusercontent.com/18352403/52564450-25c22600-2dfc-11e9-84ae-4524a2ed21ab.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
This is mainly an issue when running certain test automation on CI/QA
I guess we are doing some strict check when we hit the providers API for AWS/OCP as when I add a real AWS account the local data suddenly appears.

**Comment by dlabrecq** [comment]
@boaz0 Can you please take a look at this one, along with your upcoming AWS onborading work?

**Comment by boaz0** [comment]
No problem

**Comment by dlabrecq** [comment]
Is this still an issue? A lot has changed regarding providers are created; modal, error messages, etc.

**Comment by boaz0** [comment]
I can't reproduce it. I need more details on this. Maybe the responses from the backend will help here.

**Comment by dlabrecq** [comment]
I was hoping @ lcouzens could reproduce it? Otherwise, we can close

**Comment by dlabrecq** [comment]
I was hoping @lcouzens could reproduce it? Otherwise, we can close

**Comment by dlabrecq** [comment]
Feel free to reopen if this is still an issue.
