### ISSUE TITLE
UI filter fields not updated correctly when changing group by cost

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#477]
**Describe the bug**
UI filter fields not updated correctly when changing group by cost

**To Reproduce**
1. Navigate to AWS Details
2. Click on 'Group by cost' dropdown
3. Change to Services or Regions
4. Try to filter on anything

**Expected behavior**
Filter default text should match group by value and added filters should also match group by value.

**Screenshots**
![screenshot from 2019-02-13 09-46-22](https://user-images.githubusercontent.com/18352403/52702591-617ffb80-2f74-11e9-886f-8a828c0c6e52.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 65

**Additional context**
This is currently an issue on CI insightsbeta

**Comment by dlabrecq** [comment]
This probably broke with the recent change to introduce the PF4 table -- still a work in progress. Should be an easy fix?

**Comment by lcouzens** [comment]
After our discussion earlier a similar issue might be happening on the OCP details when trying to group by/filter by tags. Lets check that out too to save opening additional bugs. :+1:

**Comment by dlabrecq** [comment]
Had a cut/paste error for the AWS details page -- got that working again.

The OCP details page looks ok to me. For example, I group by `Tag key: alertmanager`, then apply "open" as a filter, I then see "openshift-monitoring" as expected.

![chrome-capture](https://user-images.githubusercontent.com/17481322/52755125-d4b45c80-2fca-11e9-93b7-3f9b57355f29.gif)

**Comment by lcouzens** [comment]
@dlabrecq Right you can filter by project name but not by a tag value, maybe I explained it wrong and thats the bit that @nlcwong needs to design still.

**Comment by dlabrecq** [comment]
That's correct. You cannot enter a `tag: key` pair into the filter. At one time, we had tag buttons you could click on to apply a filter, but Natalie asked that functionality be removed.

**Comment by dlabrecq** [comment]
I'll create another issue when Natalie has her mocks ready and we better understand what functionality needs to be implemented.
