### ISSUE TITLE
Group by cost/charges dropdown can grow infinitely with tags added

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#478]
**Describe the bug**
Group by cost/charges dropdown can grow infinitely with tags added

**To Reproduce**
1. Add provider with a large number of tags
2. Navigate to AWS/OpenShift Details
3. Click on Group by cost/charges
4. See list of items

**Expected behavior**
We Need a better method for tag grouping, Perhaps a specific view for seeing related tags then type in a tag name? I'm not sure but having them all in a dropdown is not user friendly.

**Screenshots**
![screenshot from 2019-02-13 09-14-11](https://user-images.githubusercontent.com/18352403/52703226-c5ef8a80-2f75-11e9-9c44-522873ed71dd.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 65

**Additional context**
Currently using my account on CI insightsbeta

**Comment by dlabrecq** [comment]
@nlcwong Can you please take a look at this design?

**Comment by nlcwong** [comment]
@sergio @chambrid we need to know if we can only show specific tag keys (out of box hand picked by us) the user can choose in that drop down for summit/tech preview, but for GA, we'll need to include in the tag management flow, how users can customize what tag keys they can group by.

**Comment by nlcwong** [comment]
Per conversation with Dan, the dropdown will list "Tag Key..." and if the user selects that, a select component (that allows a type ahead) to then display the various tag keys they could group by.

**Comment by nlcwong** [comment]
We as an application do not have the feature to limit the tag keys that are shown to be able to group by.  We will wait to see what the platform can provide as a tagging solution to see how we can either have our requirement integrate with their work and/or use what they have done and extend it out.

**Comment by dlabrecq** [comment]
We may still split tags into their own menu. However, the number of tags shown is now limited via the application settings page.

https://ci.cloud.redhat.com/beta/settings/applications/cost-management
