### ISSUE TITLE
'More tags' button on project item in OCP details expands beyond page (tag quantity dependent)  

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#481]
**Describe the bug**
'More tags' button on project item in OCP details expands beyond page (tag quantity dependent)  

**To Reproduce**
1. Navigate to OpenShift Details
2. Expand project on details page
3. Click on More tags button
4. See log list

**Expected behavior**
Should see a clear easy to read list of tags

**Screenshots**
![screenshot from 2019-02-13 11-59-59](https://user-images.githubusercontent.com/18352403/52726183-94dd7d00-2faa-11e9-89d4-1456f984d160.png)

**Desktop (please complete the following information):**
 - OS: Fedroa
 - Browser Chrome
 - Version 66

**Additional context**
I was testing this against CI insiightsbeta

Spoke to @nlcwong and this needs some designs

**Comment by dlabrecq** [comment]
Was afraid this might happen with too many tags. We should move this to a scrollable modal.
