### ISSUE TITLE
No longer able to add AWS provider with new wizard flow

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#485]
**Describe the bug**
No longer able to add AWS provider with new wizard flow

**To Reproduce**
1. Go to Overview
2. Click on 'Add a Source'
3. Try to select AWS from dropdown (option greyed out)

**Expected behavior**
Should be able to select AWS as a provider

**Screenshots**
![screenshot from 2019-02-14 11-45-13](https://user-images.githubusercontent.com/18352403/52788324-79c94680-3058-11e9-8cfa-24422d2de6b9.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
I would guess this is because its still in progress but just to be sure and tracked.
This is on CI insightsbeta

**Comment by dlabrecq** [comment]
The OCP provider functionality is complete and the AWS functionality is scheduled for this sprint. We have an issue for that here https://github.com/project-koku/koku-ui/issues/201

**Comment by dlabrecq** [comment]
FYI @boaz0 

During today's standup, Chris asked if we could revert the provider functionality. We cannot push the latest UI to production without the ability to add an AWS provider.

We can leave the OCP provider modal in the source, but I'll just change the "Add Source" to open the old modal for now. When the AWS functionality has been added, we can open the new modal.
