### ISSUE TITLE
Onboarding wizard has no error message on failure

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#486]
**Describe the bug**
Onboarding wizard has no error message on failure

**To Reproduce**
1. Go to Overview
2. Click on 'Add a Source'
3. Fill out details to add OCP source (remembering name/cluster ID)
4. Click continue to add source
5. Add a new source with the same name/ID
6. Red cross for Confirmation Status

**Expected behavior**
There is two issues to tackle here, if we get a Confirmation Status as a Green tick we need some details such as:
You have successfully setup X Source with the following details:
Type
Name
Cluster identifier

Or if Confirmation Status is a Red cross (Failure) we need details on what went wrong and why,
Such as:
Configuration for X Source failed because:
Already have X Name or Cluster identifier?

**Screenshots**
![screenshot from 2019-02-14 13-14-43](https://user-images.githubusercontent.com/18352403/52789431-b5b1db00-305b-11e9-85b5-169a8115aa81.png)
![screenshot from 2019-02-14 13-23-10](https://user-images.githubusercontent.com/18352403/52789436-b8accb80-305b-11e9-9d9b-cf7fb519e0ad.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
This was running against CI insightsbeta

**Comment by boaz0** [comment]
That's awkward that you don't see any message. I will look at this.
In addition, according to the design I was given the status message should be "Successfully added" or "Something went wrong".

Nonetheless, I do think what you're suggesting is better IMHO.

Thanks.

**Comment by boaz0** [comment]
Yep - I see why it happened. Also the animations are not working. I apparently overridden this when I rebased. I am going to work on it and probably will push a fix in ~3 hours
