### ISSUE TITLE
AWS details expanded account shows '1 other' when it should show the item name

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#489]
**Describe the bug**
AWS details expanded account shows '1 other' when it should show the item name

**To Reproduce**
1. Go to AWS details
2. Click on expand arrow on a table item
3. See cost related  items
4. We show 3 items + 1 Other in some cases

**Expected behavior**
If there is only 4 items we shouldn't be showing '1 Other' just the actual named item. Also we remove the 'Show More' link so we can't see what the other item actually is.

**Screenshots**
![screenshot from 2019-02-14 17-17-05](https://user-images.githubusercontent.com/18352403/52804834-1bfb2580-307d-11e9-840c-599850049b86.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
This is on CI insightsbeta

**Comment by dlabrecq** [comment]
I believe this is a function of the backend API. When we request a limit, the API returns an "Other" group for the remaining services. Since "Other" is returned, the UI displays that as expected.

**Comment by dlabrecq** [comment]
I'll ensure the 'Show More' link is shown, but the 'Other" change must come from the API.
