### ISSUE TITLE
'Show More' popup on AWS details - expanded table item has no page title

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#490]
**Describe the bug**
'Show More' popup on AWS details - expanded table item has no page title

**To Reproduce**
1. Go to AWS details
2. Click on arrow to expand an account
3. Click on 'Show More' button
4. See popup has no title or any information on what its showing you

**Expected behavior**
Popup should have a title

**Screenshots**
![screenshot from 2019-02-14 17-14-50](https://user-images.githubusercontent.com/18352403/52805229-0cc8a780-307e-11e9-98fa-496bfa08c569.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by dlabrecq** [comment]
I'm not able to reproduce with insights beta.

![screen shot 2019-02-18 at 11 04 34 am](https://user-images.githubusercontent.com/17481322/52963148-0764a900-336d-11e9-80cb-aedb0afe7400.png)

**Comment by dlabrecq** [comment]
Looking at when this was opened, I suspect you were testing while I was updating items on this page? If this is still an issue, feel free to reopen. However, the modal definitely has a title.
