### ISSUE TITLE
Add a Source modal does not close when you click finish

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#492]
**Describe the bug**
Add a Source modal does not close when you click Confirm
**To Reproduce**
1. Go to Overview page
2. Click on 'Add a Source'
3. Fill out details correctly
4. Click Confirm
5. Source seems to get added but modal does not close.

**Expected behavior**
Source should be added and modal should be closed.

**Screenshots**
![screenshot from 2019-02-16 23-02-48](https://user-images.githubusercontent.com/18352403/52906240-79d76b00-323f-11e9-8bc5-14a0d84a29e3.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
I get the same issue regardless if I add AWS or OCP provider.

**Comment by dlabrecq** [comment]
I don't know that we will make further changes to this particular modal? That is, considering we now have a new modal for OCP onboarding. When the AWS functionality is ready (during sprint 18), we will switch it on and completely replace this functionality.

@boaz0 Please ensure the new onboarding flow doesn't have a similar issue and close if applicable.
