### ISSUE TITLE
OCP on AWS

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#516]
## User Story
As a user, I want to see an overview of OCP on AWS.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- All tabs will use the same basic card layouts, just shown horizontally Vs vertically
- Other than the total cost, cards will omit tabs containing progress bars
- Not certain we have APIs to display AWS `cost` and `running`?
- Legends, titles, etc. may be refactored via a later PR?
- This is not high fidelity, so there will be more changes to come...

## UI Details
See latest mock: https://redhat.invisionapp.com/share/MJQQ9LYYB7Q

## Screenshots
![screen shot 2019-02-27 at 10 57 38 am](https://user-images.githubusercontent.com/17481322/53503737-a3ce3000-3a7e-11e9-83e4-c3df0c60fb81.png)

## Acceptance Criteria
- 

Epic Issues
https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/516

**Comment by dchorvat1** [comment]
Verified 
Commit: '81e6c8a'
