### ISSUE TITLE
AWS/OpenShift details pages missing padding after the table

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#517]
**Describe the bug**
AWS/OpenShift details pages missing padding after the table

**To Reproduce**
1. Go to AWS/OpenShift details pages
2. Use group by which has long list of items
3. Scroll down to bottom
4. See no padding

**Expected behavior**
We should have padding on the bottom of the table

**Screenshots**
![screenshot from 2019-02-24 23-57-43](https://user-images.githubusercontent.com/18352403/53307398-09a89500-3890-11e9-87a5-90875cc570cb.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Present on CI/QA/PROD insights/insightsbeta

**Comment by boaz0** [comment]
I believe this is a bug in PF4

**Comment by lcouzens** [comment]
Maybe but other pages seem fine though. 
![screenshot from 2019-02-25 08-52-44](https://user-images.githubusercontent.com/18352403/53325332-fec72200-38da-11e9-8174-5f5c01b11619.png)

**Comment by boaz0** [comment]
I think it's caused by the checkbox. Unless you have a selectable table that is aligned correctly.

**Comment by lcouzens** [comment]
I actually think the table is extending past the padding completely like before. See the screenshot below, you can see there is a small break in the grey padding left/right. That's caused from the table extending outside of the padding size but the background scrolling with the page. I know platform added a template view to the pages recently (matching the grey padding) so loading looked better but that now makes the table look like its within the padding but its really not.
![screenshot from 2019-02-25 09-43-56](https://user-images.githubusercontent.com/18352403/53328679-6b91ea80-38e2-11e9-9e1f-9461abd561b5.png)

**Comment by dlabrecq** [comment]
We don't have any padding on the bottom. It's an easy fix.
