### ISSUE TITLE
Left hand nav and page header scroll with AWS/OpenShift details page table views 

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#518]
**Describe the bug**
Left hand nav and page header scroll with AWS/OpenShift details page table views 

**To Reproduce**
1. Go to AWS/OpenShift Details
2. Group by large list of items
3. Scroll down
4. See Left hand nav and Page header disapear

**Expected behavior**
We should only be scrolling the app/table data.

**Screenshots**
![screenshot from 2019-02-24 23-53-57](https://user-images.githubusercontent.com/18352403/53307452-b5ea7b80-3890-11e9-9ecb-3707c30b6b88.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Present on CI/QA/PROD insights/insightsbeta

**Comment by lcouzens** [comment]
This is also present on the Overview page.

**Comment by dlabrecq** [comment]
Not able to reproduce on Insights production with Mac:

- Chrome version 72.0.3626.109 (Official Build) (64-bit).
- Firefox 65.0.1 (64-bit)

**Comment by dlabrecq** [comment]
Note that we don't control the left hand navigation pane. Please open an issue with Insights.
