### ISSUE TITLE
Alert doesn't fit into modal window

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#520]
**Describe the bug**
Error alert doesn't fit to "Add Source" modal window.

**To Reproduce**
1. Go to "Cost Management" / "Overview"
2. Click on "Add Source"
3. Add some incorrect data
4. Alert will popup in the modal window, but it seems it doesn't fit to the window.

**Expected behavior**
Alert width should be smaller or it should go out of the modal window.

**Screenshots**
![screenshot_20190225_114931](https://user-images.githubusercontent.com/1011257/53332410-97699c00-38f3-11e9-8816-49a18e9f0780.png)

**Desktop (please complete the following information):**
 - OS: openSUSE 15.0
 - Browser: Firefox
 - Version: 65

**Comment by dlabrecq** [comment]
FYI, we're in the process of replacing this modal. When the AWS functionality is complete, we will turn it on. See https://github.com/project-koku/koku-ui/issues/201

@boaz0 Can you please confirm that the new modal does not have this issue and close.
