### ISSUE TITLE
Price List

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#524]
## User Story
As user, I want to define rates so that I see what my OCP environment costs.

## Impacts
UI, Docs

## Role
User

## Assumptions
- Koku API has support for Rate CRUD operations
- Koku API has integrated Rates into OCP Report queries.
- We will show a price list only for summit

## UI Details
Price List Mock (Option B): https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/352926696
![Screen Shot 2019-03-20 at 12 23 22 PM](https://user-images.githubusercontent.com/17481322/54701276-1032d100-4b0b-11e9-8de2-381e32c4ee98.png)

Details Mock (Option B): https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/352926695
![Screen Shot 2019-03-19 at 2 08 44 PM](https://user-images.githubusercontent.com/17481322/54631061-9559af80-4a51-11e9-8492-3478f010b16a.png)

## Acceptance Criteria (for summit)
- [x] The price list can be launched from a kebab in the OCP details page.
- [x] The price list can be launched only when grouped by cluster.
- [ ] A user should be able to see a list of defined Rates.

## Acceptance Criteria (post summit)
- [ ] A user should be able to create a new Rate, modify an existing Rate, and delete Rates.
- [ ] A `Rate` should define a `Cost` that applies to a `Metric` and a `Time`. (e.g. $0.25 per CPU-hour, or $0.01 per GiB Network-IO per minute.)
- [ ] A user should be able to associate a Rate with an Account or OCP Cluster
- [ ] Kebab drop-down menu (#739)

## Epic Issues
https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/524

**Comment by chargio** [comment]
There should be another use case for assignments.

A price list could be different per provider (i.e. OCP in AWS has a different cost than the same one runnign on Azure)

This could be a good starting point taking into account that we will need more than one or one that is capable of discriminating based on the provider.

**Comment by boaz0** [comment]
@dlabrecq I think we should keep this open because it has post summit action items.
Thanks.

**Comment by dlabrecq** [comment]
I'll open a new issue for post summit work.

**Comment by dlabrecq** [comment]
I created issue https://github.com/project-koku/koku-ui/issues/754. We want QA to review this work for summit.

**Comment by boaz0** [comment]
Got it! Thanks a lot!
