### ISSUE TITLE
'Looking for sources' empty state never times out

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#533]
**Describe the bug**
'Looking for sources' empty state never times out

**To Reproduce**
1. Add random OCP provider
2. refresh page
3. 'Looking for sources...' never disappears

**Expected behavior**
If we don't find sources after X seconds we should be timing out with an error message.

**Screenshots**
![screenshot from 2019-02-26 09-48-44](https://user-images.githubusercontent.com/18352403/53405952-e32e4b00-39b0-11e9-9def-163778856d35.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
ocp provider I added:
![screenshot from 2019-02-26 10-26-56](https://user-images.githubusercontent.com/18352403/53406068-15d84380-39b1-11e9-9120-bbef2ec803cd.png)

**Comment by dlabrecq** [comment]
Are there any errors in the browser console? Or, any network requests fail?

Not sure what the timeout should be? However, we can start by showing the unexpected error page after 60 seconds?

**Comment by dlabrecq** [comment]
The logic used to determine if a provider exists needed to change slightly.
