### ISSUE TITLE
New modal AWS IAM policy json string formatted wrong

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#540]
**Describe the bug**
New modal AWS IAM policy json string formatted wrong

**To Reproduce**
1. Go to Overview
2. Click on 'Add a source'
3. Fill in source type/name click continue
4. Fill in bucket name click continue
5. Copy json text to paste into policy on AWS
6. try pasting the json, formatting is wrong and we have bucket_name as the bucket name

**Expected behavior**
Copied json should be formatted correctly, we should also probably fetch the bucket name from the previous page and put that in the json text. (step 4 above)
At the very least we need to have an instruction to check the bucket name is correct in the policy.

**Screenshots**
![screenshot from 2019-02-27 10-43-06](https://user-images.githubusercontent.com/18352403/53485230-96fd0c80-3a7d-11e9-89bf-f9d0e0e8f68c.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Comment by boaz0** [comment]
Thanks I will fix that!
