### ISSUE TITLE
New modal create IAM role instructions very vague

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#541]
**Describe the bug**
New modal create IAM role instructions very vague

**To Reproduce**
1. Go to Overview
2. Click on 'Add a source'
3. Fill in source type/name click continue
4. Fill in bucket name click continue
5. Create policy click next
6. Try to create role

**Expected behavior**
```
Select Another AWS Account from the list of trusted entities and paste the following value into the Account ID field:
```
We should probably put 'Another AWS Account' in quotes as that's a button selection
We also have no indication of whether we should/shouldn't tick additional options:
Require external ID
Require MFA
```
Complete the process to create your new role
```
This is very vague, no mention of tags, it says optional on AWS but we should probably mention it too, we also have no mention on role naming or description. We should have some advice for this step for sure.

**Screenshots**
![screenshot from 2019-02-27 11-01-41](https://user-images.githubusercontent.com/18352403/53485951-6fa73f00-3a7f-11e9-9818-ba81727eb3cc.png)

![screenshot from 2019-02-27 11-06-59](https://user-images.githubusercontent.com/18352403/53486317-4aff9700-3a80-11e9-825a-8bcbbef06c79.png)

![screenshot from 2019-02-27 11-10-08](https://user-images.githubusercontent.com/18352403/53486321-4e931e00-3a80-11e9-9cdf-89bf027768bb.png)

**Additional context**
Testing against CI insightsbeta

**Comment by boaz0** [comment]
@nlcwong can you look at this please? :smiley:

**Comment by dlabrecq** [comment]
I believe @dayleparker has contributed several edits for the onboarding modal. For example, I found the following issues related to the onboarding modal:

Select a source edits #787
OpenShift edits https://github.com/project-koku/koku-ui/issues/788
Usage Collector (OCP) https://github.com/project-koku/koku-ui/issues/790
Configure data collection (OCP) https://github.com/project-koku/koku-ui/issues/791

@dayleparker Has this particular AWS issue been addressed? If not, can you please take a look at this?

**Comment by dlabrecq** [comment]
ping @dayleparker

**Comment by nlcwong** [comment]
One of the things we were trying to aim for is that instructions found in the UI is to be vague in that we are assuming the user is an AWS admin who has experience in doing the things we need them to do.  With that said, we also would have links to the RH documentation that would have more filled out instructions.  I do remember Judd mentioning that it would be great to include mention about importing tags (that was missing from the sources flow).

With all this said, I'm still waiting to see what the sources group is going to do.  Its not clear on what our integration would actually feel like, but when that conversation spins back up, I will follow up on this issue then.

**Comment by dlabrecq** [comment]
AWS onboarding has been ported to the sources-ui. OCP and Azure will be ported under.

Sources-Cost OCP Wizard: ManageIQ/sources-ui#127
Sources-Cost Azure Wizard: ManageIQ/sources-ui#128
