### ISSUE TITLE
'Add a Source' empty state button no longer functions

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#544]
**Describe the bug**
'Add a Source' empty state button no longer functions

**To Reproduce**
1. Go to Overview page (with no providers added)
2. Click on 'Add a Source' button in center of page
3. Button highlights but nothing happens

**Expected behavior**
Button should work correctly to load now modal

**Screenshots**
![screenshot from 2019-02-27 12-26-16](https://user-images.githubusercontent.com/18352403/53490258-2f4dbe00-3a8b-11e9-92d3-e8f6bcfc6876.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by boaz0** [comment]
I think I know why.
