### ISSUE TITLE
User management (RBAC)

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#554]
## User Story
As an admin, I would like to create a user who can only view certain cost data in my world so that they can see cost data that only pertains to the information they have authorization to see.

## Impacts
- UI
- Docs

## Assumptions
- API is already available
- For tech preview, we are designing our own UI, but for GA, we are hoping that platform would implement something that can be shared by all participating apps.

## UI Details
TBD

## Acceptance Criteria
- [ ]
- [ ]

## Epic Issues
To view the linked "backlog", "in progress", and "completed" issues associated with this epic, add the  [Zenhub browser extension](https://www.zenhub.com). 

Alternatively, view the Zenhub board for this [epic](https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/554).

**Comment by dlabrecq** [comment]
Closing this epic since another team will now be responsible for implementing the RBAC UI.
