### ISSUE TITLE
New modal failure message keeps active after closing

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#557]
**Describe the bug**
After closing the 'add source' dialog with 'x' button instead of 'close' after adding a source failed, the error message appears immediately after clicking 'add source' again.

**To Reproduce**
1. Go to overview
2. Click on 'add source'
3. Input invalid data so error message appears in the end.
4. Close the dialog with 'x' button instead of 'close'
5. Click on 'add source' again
6. The error message gets displayed 

**Expected behavior**
Beginning of the add source wizard is displayed

**Screenshots**
![screenshot from 2019-03-01 11-51-28](https://user-images.githubusercontent.com/46324552/53634024-6520ad00-3c19-11e9-9d65-badd185df3d5.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser: Chrome
 - Version 71

**Additional context**
Tested on CI Insightsbeta

**Comment by boaz0** [comment]
Yeah, I thought closing the windows means to stay at the same spot through the process but just hiding the modal. Clicking on close, however, will reset everything.

If we should reset the wizard progress when clicking on the `x` button, then I will fix it.

Thanks.

**Comment by lcouzens** [comment]
@dchorvat1 When you raise a bug please don't forget to tag it with 'bug' and give it a priority based on its impact.

**Comment by lcouzens** [comment]
Personally I don't think it makes sense to save the modal state from the :x: button, If we really want to save the state then we should have a :heavy_minus_sign: sign instead as that has a clear generic use.
Although that being said I can't think of a reason why you would want to minimize the modal anyway, but maybe there is a use case for it that I can't think of :)

**Comment by dlabrecq** [comment]
FYI, we started using `severity` for bugs instead of `priority` per discussion with Jen. Priority has caused some confusion and it's something we wish to reserve for features slated for summit, tech-preview, etc.
