### ISSUE TITLE
AWS historical charts resize the first time they are opened causing a scroll bar to appear

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#559]
**Describe the bug**
AWS historical charts resize the first time they are opened causing a scroll bar to appear

**To Reproduce**
1. Go to AWS details
2. Click on expand arrow
3. Click on 'historical charts' button
4. See charts load without data then resize with data causing them to expand to far

**Expected behavior**
Pop up size should be correct to cover the range of the graphs regardless of data

**Screenshots**
First time you load historical data after browser refresh:

![screenshot from 2019-03-02 14-10-49](https://user-images.githubusercontent.com/18352403/53683556-0ed76b00-3cfa-11e9-92c7-e6ab462b567c.png)

Close and reopen historical data without browser refresh:

![screenshot from 2019-03-02 14-11-24](https://user-images.githubusercontent.com/18352403/53683563-2adb0c80-3cfa-11e9-861a-074278bb61cb.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by dlabrecq** [comment]
Not able to reproduce with Chrome on Mac

Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by dlabrecq** [comment]
Although, I cannot reproduce the issue myself, I'm going to try making the modal slightly wider. It looks like the legend just wrapped onto the next line.
