### ISSUE TITLE
AWS details page dropdown disappears after selecting 'account', 'service' or 'region'

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#560]
**Describe the bug**
AWS details page dropdown disappears after selecting 'account', 'service' or 'region'

**To Reproduce**
1. Go to AWS detail page
2. Click on group by dropdown
3. Select anything from the list
4. Dropdown disappears and data does not update/change

**Expected behavior**
Dropdown should not disappear and data should be grouped by selection

**Screenshots**
![screenshot from 2019-03-02 14-50-05](https://user-images.githubusercontent.com/18352403/53683607-b94f8e00-3cfa-11e9-9426-6f1c793bcb5e.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by dlabrecq** [comment]
I'm seeing a `{"order_by":{"total":["Unsupported parameter"]}}` message, most likely due to a recent API change
