### ISSUE TITLE
Bucket name is not populated into json string in new 'Add a Source' modal

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#562]
**Describe the bug**
Bucket name is not populated into json string in new 'Add a Source' modal

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Add a Source'
3. Select 'Amazon Web Services (AWS)'
4. Set source name
5. Click continue
6. Set 'S3 bucket name'
7. click next
8. copy/paste json string

**Expected behavior**
json string should be pr-populated with the bucket name we already set in the previous step

We shouldn't provide a copy/paste feature if the string needs manual editing by the user,
or if we do we need instructions to say it needs editing.

**Screenshots**
![screenshot from 2019-03-02 15-08-38](https://user-images.githubusercontent.com/18352403/53683812-13e9e980-3cfd-11e9-9847-f38c1dda116d.png)

![screenshot from 2019-03-02 15-12-12](https://user-images.githubusercontent.com/18352403/53683836-983c6c80-3cfd-11e9-8c17-c284e1136f27.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by boaz0** [comment]
Although it's not an excuse, I just followed the mocks :innocent:.
Anyway, I guess I need to update this part, right?:

```json
"Resource": [ "arn:aws:s3:::<bucket_name_here>", "arn:aws:s3:::<bucket_name_here>/*"]
```

where `<bucket_name_here>` is the bucket name entered a few steps before. :national_park:
