### ISSUE TITLE
Some 'Add a Source' modal copy/paste text strings contain '#'

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#563]
**Describe the bug**
Some 'Add a Source' modal copy/paste text strings contain '#'

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Add a Source'
3. Navigate through OCP configuration
4. Notice some copy/paste strings start with '#'
5. Pasting and running a string starting with '#' will fail

**Expected behavior**
Strings should not contain '#'s

**Screenshots**
![screenshot from 2019-03-02 15-20-57](https://user-images.githubusercontent.com/18352403/53683976-557b9400-3cff-11e9-8a49-4f86fdd755f4.png)

![screenshot from 2019-03-02 15-22-43](https://user-images.githubusercontent.com/18352403/53683979-5a404800-3cff-11e9-84e5-c3518e6ed06e.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing Against CI insightsbeta

**Comment by boaz0** [comment]
I don't mind removing `#` at the beginning but we do have to mention that it is must to be executed as root user.
