### ISSUE TITLE
'Add a Source' modal final steps should have a 'complete' button not 'continue'

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#564]
**Describe the bug**
'Add a Source' modal final steps should have a 'complete' button not 'continue'

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Add a Source'
3. Complete OCP or AWS source details
4. Click 'continue' to finish/complete setup

**Expected behavior**
Button should really say 'Complete' or 'Finish' or better yet, we should continue to a final screen with all the options we setup. Then the user can confirm the arn/bucket/cluster/source names and confirm to finish the setup.

**Screenshots**
![screenshot from 2019-03-02 15-22-43](https://user-images.githubusercontent.com/18352403/53684104-f0c13900-3d00-11e9-8e9c-62a8f0ac59d9.png)

![screenshot from 2019-03-02 15-31-10](https://user-images.githubusercontent.com/18352403/53684106-f9b20a80-3d00-11e9-926b-23cbe4258d91.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by boaz0** [comment]
Yeah, sure. I don't mind doing that.
Does it sound reasonable to you @nlcwong?
