### ISSUE TITLE
Export data modal selects 'daily' aggregate type, when clicking on 'monthly'

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#586]
**Describe the bug**
Clicking 'monthly' label in export data modal selects 'daily' aggregate type

**To Reproduce**
1. Go to aws/ocp details
2. Select any of the items to export
3. Click 'export' to open the modal
4. Click on 'monthly' label, nothing happens
5. Click on 'monthly' radio button, 'monthly' aggregate type gets selected
6. Click on 'monthly' label, 'daily' aggregate type gets selected back

**Expected behavior**
Clicking 'monthly' label selects monthly aggregate type

**Screenshots**
![screenshot from 2019-03-08 10-24-05](https://user-images.githubusercontent.com/46324552/54019901-b0443e00-418c-11e9-8986-886eb5fd4e0f.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 71

**Comment by dlabrecq** [comment]
Clicking on the label is expected behavior; however, we need unique IDs to ensure that works properly.
