### ISSUE TITLE
Looking for sources loading indefinitely

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#587]
**Describe the bug**
After refreshing the page on AWS Details or OpenShift Details pages, Looking for sources state sometimes fails to finish

**To Reproduce**
1. Go to AWS Details/OpenShift Details
2. Refresh page
3. In around one third of the cases, Looking for sources appears and never finishes

**Expected behavior**
Details page gets displayed correctly

**Screenshots**
![screenshot from 2019-03-08 12-25-00](https://user-images.githubusercontent.com/46324552/54026833-8cd6be80-419f-11e9-80ca-e280c5f3ed9f.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 71

**Additional context**
ENV: CI insightsbeta
The way to reproduce makes this issue show up pretty inconsistently. Most of the times, after another refresh the page displays correctly, but it becomes a problem in automated testing, since it makes a portion of the tests fail.

**Comment by dlabrecq** [comment]
Need more information about the providers request. (I have never been able to reproduce while inspecting the browser's network tab.) For example, it would be helpful to understand if the request failed to return, took too long, etc.

The code was changed for sprint 19 to show the table, header, etc.by default, unless the providers fetch status is in progress. However, the page won't update unless the fetch status changes. 

We may still need some sort of time out to force the page to update during these edge cases?

**Comment by dchorvat1** [comment]
The providers requests always return 200 status, even when the page itself doesn't load properly
