### ISSUE TITLE
OCP on AWS details page

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#598]
## User Story
As a user, I want to see a OCP on AWS details page.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- This will be a copy of OCP, until we have filter APIs available to show just OCP on AWS.
- Insights will need to create a new navigation link. See https://github.com/RedHatInsights/insights-chrome/issues/182
- Custer is shown only when grouping by project and node
- Tags are shown only when grouping by project
- Tags API is not available for cluster & node

## UI Details
See the OCP on AWS mocks below:

Project Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350233292
Cluster Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350233
Node Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350233288

## Screenshots
<img width="1281" alt="Screen Shot 2019-03-08 at 3 30 01 PM" src="https://user-images.githubusercontent.com/17481322/54054033-1a71d880-41b7-11e9-8d0d-e6286dcd6efb.png">

## Acceptance Criteria
- [x] Details page appears similar to OCP
- [x] Expanding row provides similar functionality to mocks, minus assumptions above

## Epic Issues
To view the linked "backlog", "in progress", and "completed" issues associated with this epic, add the  [Zenhub browser extension](https://www.zenhub.com). 

Alternatively, view the Zenhub board for this [epic](https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/598).

**Comment by dchorvat1** [comment]
verified
commit 'f08df48308c33d0e35f9a010c42cb322289a5604'
