### ISSUE TITLE
Details layout updates

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#602]
## User Story
As a user, I want to see detail page layouts per the mock below

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- May need input about the text in the legend label layouts

## UI Details
Labels and legends should appear similar to the OCP on AWS mock below:

Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350233288

## Screenshots
<img width="1281" alt="Screen Shot 2019-03-08 at 3 30 01 PM" src="https://user-images.githubusercontent.com/17481322/54054033-1a71d880-41b7-11e9-8d0d-e6286dcd6efb.png">

## Acceptance Criteria
- [ ] Expanding row layout appears similar to the mock
- [ ] 

## Epic Issues
To view the linked "backlog", "in progress", and "completed" issues associated with this epic, add the  [Zenhub browser extension](https://www.zenhub.com). 

Alternatively, view the Zenhub board for this [epic](https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/602).

**Comment by dchorvat1** [comment]
verified 
commit 'f08df48308c33d0e35f9a010c42cb322289a5604'
