### ISSUE TITLE
New AWS cards

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#603]
## User Story
As a user, I want to see AWS network and database cards per the mock below

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
-

## UI Details
AWS network and database cards should appear similar to the OCP on AWS mock below:

Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350009551

## Screenshots
<img width="1184" alt="Screen Shot 2019-03-08 at 4 28 48 PM" src="https://user-images.githubusercontent.com/17481322/54056846-46915780-41bf-11e9-9be6-e27f5a872737.png">

## Acceptance Criteria
- [ ] AWS database card appears similar to the mock
- [ ] AWS network card  appears similar to the mock

Epic Issues
https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/603

**Comment by lcouzens** [comment]
Verified
