### ISSUE TITLE
Historical tool tips cut off be modal size

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#606]
**Describe the bug**
Historical tool tips cut off be modal size

**To Reproduce**
1. Go to 'details page'
2. Click on 'historical data'
3. Show first day tool tip

**Expected behavior**
Tool tip data should be readable

**Screenshots**
![Screenshot from 2019-03-11 11-30-33](https://user-images.githubusercontent.com/18352403/54121121-82136800-43f1-11e9-89c0-f943b738f7bb.png)
![Screenshot from 2019-03-11 11-29-45](https://user-images.githubusercontent.com/18352403/54121124-850e5880-43f1-11e9-8542-f1a2dff3cf96.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 65

**Additional context**
Testing against CI insightsbeta

**Comment by dchorvat1** [comment]
The modal also cuts off the bottom 'day of month' text when resized

**Comment by dlabrecq** [comment]
The tooltip is provided by Victory, the underlying library for the charts. We could make the margin much larger, but that may be undesirable.

@dchorvat1 When resizing the window, the modal should be scrollable.
