### ISSUE TITLE
Lint: locales are inconsistent 

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#614]
**Describe the bug**

There is a diff between `src/locales/{de,es}.json` and `src/locales/en.json`

**Comment by dlabrecq** [comment]
Are you sure you have the latest? I just performed a diff and they look the same to me.

```
> diff en.json de.json 
> diff en.json es.json 
> diff de.json es.json
```

**Comment by dlabrecq** [comment]
I was also thinking we could remove these locales, since we're not using them.

**Comment by boaz0** [comment]
fixed in https://github.com/project-koku/koku-ui/pull/621

Thanks @dlabrecq
