### ISSUE TITLE
Sources filter functionality

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#649]
**Describe the bug**
There are some issues with filtering for the new sources page.

1. There is no results row when a filter is applied. As a user, I'm expecting to clear filters similarly to the details pages. Currently, the only way to clear a filter is to delete the previous filter string and press enter.

2. The filter does not accept partial strings. This could be an issue for the back-end API to solve. (In that case, please file an issue with koku.) However, I could not match "hccm", only exact matches (e.g., "hccm-vmware") are found.

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Add Sources'
3. Enter a filter such as 'hccm'

**Expected behavior**
As a user, I should be able to clear individual filters. I should also be able to add partial filters.

**Screenshots**

Partial string:
![Screen Shot 2019-04-01 at 9 47 59 AM](https://user-images.githubusercontent.com/17481322/55332396-4ead8180-5463-11e9-8db1-d0e822f1a408.png)

Full String:
![Screen Shot 2019-04-01 at 9 48 14 AM](https://user-images.githubusercontent.com/17481322/55332426-5a00ad00-5463-11e9-8408-5e9e58b781dc.png)

**Additional context**
See https://docs.google.com/document/d/1_t1dV00l9j529vSWduzAkqtnGlLtlFE7e8zidylkGKo/edit?ts=5ca4eef3

**Comment by boaz0** [comment]
@nlcwong @dlabrecq @dayleparker

Current state:
- [x] filter does accept partial strings: `name=boaz` will return any source that contains "boaz" in its name
- [x] filter does "AND" on type and name: `name=boaz&type=OCP` will return all OpenShift sources that contain "boaz" in their name
-[ ] filter does "OR" on name/type: `name=[boaz,david]` will return all sources that their names contain "boaz" or "david" (e.g. david-1, 1-boaz-david, david-boaz, boaz-23, davidistheman).
