### ISSUE TITLE
OpenShift details popover for derived and infrastructure cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#670]
**Describe the bug**
Add popover to describe derived and infrastructure cost.

"The number on the header will be “Infrastructure cost”, but the title will be “Cost” and will have a popover to let the user know what infrastructure cost is (see Steve!)"

"Will need to include popovers in the header to explain what each cost means (ACTION ITEM: Steve, Dayle, Dan, and myself to edit copy)"

**To Reproduce**
1. Go to 'OpenShift details'
2. See error

**Expected behavior**
When "copy" is available, add popover to describe derived and infrastructure cost. This will be launched from an '?' icon next to the title.

Update from Dayle:
```
Derived cost
The cost based on the user’s defined price list. Calculated as infrastructure_cost + markup, or on a premises without infrastructure, calculated as CPU usage * rate.

Infrastructure cost
The cost based on raw usage data from the underlying infrastructure.
```

We also want top add a tooltip on the cost number, similar to https://github.com/project-koku/koku-ui/issues/661

**Additional context**
See Dayle's comment: https://docs.google.com/document/d/1_t1dV00l9j529vSWduzAkqtnGlLtlFE7e8zidylkGKo/edit?ts=5cac595b

Related Issue: https://github.com/project-koku/koku-ui/issues/661

**Comment by dayleparker** [comment]
Feel free to assign the writing task to me. I'll just need your review for whether it makes sense @dlabrecq :)

**Comment by dlabrecq** [comment]
Thanks, @dayleparker. I can take it from here now that we have the copy. Much appreciated.
