### ISSUE TITLE
AWS historical data not mapped on graphs

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#693]
**Describe the bug**
When we display historical data for AWS items, we don't get any data displayed on graphs

**To Reproduce**
1. Go to AWS details
2. Choose an item with some cost data
3. Display historical data
4. See that no data gets displayed on graphs

**Expected behavior**
Data plotted on graphs

**Screenshots**
![Screenshot from 2019-04-04 12-14-11](https://user-images.githubusercontent.com/46324552/55548395-a5b98d80-56d3-11e9-87d9-073161822f4a.png)

**Desktop (please complete the following information):**
 - OS: rhel
 - Browser chrome
 - Version 71

**Comment by lcouzens** [comment]
@dchorvat1 I think this is an issue on all AWS graphs currently, pretty sure I was seeing this on the Overview cards too anyway.
