### ISSUE TITLE
Update Dashboard to Match High Fidelity Mockups

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#70]
## Impacts
UI

## UI Details
Need to update the look of the dashboard to match the mockup here: https://redhat.invisionapp.com/share/BJN9KGLTUD8#/screens

## Acceptance Criteria
- [ ] Dashboard cards match the high fedelity mockups.

**Comment by boaz1337** [comment]
I believe this can be closed as #78 was merged
