### ISSUE TITLE
Update Masthead to follow High Fidelity Mockups

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#71]
## Impacts
UI

## UI Details
Need to update masthead to match styles of mockup here:
https://redhat.invisionapp.com/share/BJN9KGLTUD8#/screens

## Acceptance Criteria

- [ ] - Masthead styles match high fidelity mockup
- [ ] - Background image matches the one in the mockup.

**Comment by dlabrecq** [comment]
Merged via #78
