### ISSUE TITLE
Update Sidebar to match High Fidelity Mockup

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#72]
## Impacts
UI

## UI Details
Need to make sidebar styles match the high fidelity mockup here: https://redhat.invisionapp.com/share/BJN9KGLTUD8#/screens

## Acceptance Criteria

- [x] - Sidebar styles match the styles in the mockup here
- [x] - Icons match mockup for overview and cost.

**Comment by dmiller9911** [comment]
We still need the top piece on mobile, views. Design can be found here: https://docs.google.com/presentation/d/1Ye5Vhj3AqQStZINtqUJ4Y8-mzKX3qBWRmlMQdP-lnwY/edit (last slide)

![image](https://user-images.githubusercontent.com/8880102/44529453-2504ce80-a6ba-11e8-8914-59ca712ab8ac.png)

I meant to include this in this ticket, but forgot. Mind grabbing that peice too? Eyeballing the sizes should be ok. It won't match up 1:1 right now since the masthead is not quick like those designs.

**Comment by boaz1337** [comment]
I am closing this - solved in #80 and #77.
