### ISSUE TITLE
I can't log out in cloud.redhat.com

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#722]
**Describe the bug**
When pressing the logout link in the header, I get some calls to SSO but I am back into the same page with the same identification
![Screenshot 2019-04-08 at 17 11 49](https://user-images.githubusercontent.com/7500590/55735361-75e6ee80-5a21-11e9-9b67-b45dc342bc1b.png)

**To Reproduce**
1. Login
2. Go the header, choose Logout
3. Wait

**Expected behavior**
Logout of the user and ask for login again

**Screenshots**

![Screenshot 2019-04-08 at 17 13 35](https://user-images.githubusercontent.com/7500590/55735498-ba728a00-5a21-11e9-9819-f96106be5c47.png)

![Screenshot 2019-04-08 at 17 14 57](https://user-images.githubusercontent.com/7500590/55735571-de35d000-5a21-11e9-8fb1-cb412ffb69aa.png)

**Desktop (please complete the following information):**
 - OS: mac OS Mojave 10.14.3
 - Browser: Chrome
 - Version 73.0.3683.86

**Additional context**

**Comment by lcouzens** [comment]
@dlabrecq this is platform issue right, I raised it already. https://projects.engineering.redhat.com/browse/RHIPLAT2-705

**Comment by dlabrecq** [comment]
Yes, Insights controls the login.

**Comment by dlabrecq** [comment]
On a related issue, I keep getting unauthorized errors after a very short amount of time. Refreshing the page helps restore a valid token. Might help logout as well?

**Comment by dlabrecq** [comment]
Confirmed this is a problem logging out from the Insights dashboard using https://ci.cloud.paas.upshift.redhat.com/ (i.e., it's not just Cost management).

**Comment by dlabrecq** [comment]
The issue with the Insights logout appears to be working now.
