### ISSUE TITLE
Wrong number and calculations in AWS tab in the dashboard

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#727]
**Describe the bug**
The interface shows NaN % instead of proper adata in the AWS tab

**To Reproduce**
1. Go to the AWS tab in the dashboard

**Expected behavior**
The proper numbers and percentages are shown

**Screenshots**
<img width="576" alt="Screenshot 2019-04-09 at 15 46 56" src="https://user-images.githubusercontent.com/7500590/55805811-72b23800-5adf-11e9-9d3f-21df8ff27e28.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Mavericks
 - Browser Chrome
 - Version 73

**Additional context**

**Comment by dlabrecq** [comment]
This is an older issue and has since been fixed. You may need to view the latest CI?

**Comment by dlabrecq** [comment]
Note that ci.cloud.paas.upshift.redhat.com does not have the latest. However, I can confirm that it's working locally.

That said, the beta version appears to have the very latest. Although, some requests appear to be painfully slow. May need to refresh or switch tabs for all cards to load here?

See https://ci.cloud.paas.upshift.redhat.com/beta/hybrid/cost-management/
