### ISSUE TITLE
OCP cards show wrong totals 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#738]
**Describe the bug**
Cards on ocp overview show wrong total values

**To Reproduce**
1. Go to OpenShift overview
2. View cards
3. See that the values don't add up

**Expected behavior**
Correct total values in the cards

**Screenshots**
![Screenshot from 2019-04-11 11-23-35](https://user-images.githubusercontent.com/46324552/55946407-fb021b80-5c4c-11e9-93fd-e74845d55915.png)
![Screenshot from 2019-04-11 11-19-35](https://user-images.githubusercontent.com/46324552/55946420-fc334880-5c4c-11e9-8bcf-653b992d9357.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Additional context**
Cost tab values don't add up correctly, memory, volume and cpu usage cards show incorrect GB-hours/Core-hours as dollar values

**Comment by dlabrecq** [comment]
For AWS, the sum of top services adds up to the total. However, there is are infrastructure and derived costs associated with OCP. If you hover over the cost, you'll see a tooltip providing an explanation.

Below are the APIs we pull data from. You can see that the UI simply displays the values as provided.

Note that the infrastructure and total costs for AWS are the same.

AWS total cost:
/reports/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily

OCP total cost:
/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily

OCP top projects:
/reports/openshift/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=3&group_by[project]=*

**Comment by dchorvat1** [comment]
But for the CPU, memory and usage cards the totals are still incorrect, "$269 Core-hours used" doesn't seem right to me

**Comment by dlabrecq** [comment]
Yes, the cpu and memory cards should show usage, not cost. I'll fix that one.

FYI, still working on fit & finish issues and making lots of changes.
