### ISSUE TITLE
Historical data modal cropped out of browser

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#753]
**Describe the bug**
Historical data modal gets cropped out of browser when we resize the browser width to a size smaller than the modal.

**To Reproduce**
1. Go to any of the details pages
2. Display historical data of an item
3. Resize browser width to it's smaller than the modal
4. See that there is no way to reach the rest of the modal, we can't close the modal (close button is cropped out) or see the rest of it

**Expected behavior**
There should be a way to reach the whole modal when browser is too small to display it whole - the modal would be resized too, or we could scroll to the sides

**Screenshots**
![Screenshot from 2019-04-15 11-01-45](https://user-images.githubusercontent.com/46324552/56120746-159b0400-5f6f-11e9-9478-cfd72c71c3b4.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Comment by dlabrecq** [comment]
The modal is a fixed size. If the window is smaller than the modal, you must scroll.

**Comment by dchorvat1** [comment]
It scrolls only up and down, when I resized the browser down in terms of width, I couldn't get to the rest of the modal

**Comment by dlabrecq** [comment]
Yes, this is nothing new. Scrolling horizontally is not currently supported by the PatternFly modal.

I've filed the issue below.
https://github.com/patternfly/patternfly-react/issues/new

**Comment by dlabrecq** [comment]
This has been fixed in PatternFly and will be introduced to the koku-ui when the latest packages are updated.
