### ISSUE TITLE
Update Insights navigation links

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#756]
The Insights navigation pane does to highlight properly when navigating between pages. For example, the user can jump from the Cost Management's overview page via a link to the OpenShift details page.

Apparently, we now have an API to call when navigating within the app.

"This PR adds option to call app nav from application itself. Just call insights.chrome.appNavClick({ id: 'page-id'}) and correct item in navigation will highlight."

See https://github.com/RedHatInsights/insights-chrome/pull/247

**Comment by dlabrecq** [comment]
When I call `insights.chrome.appNavClick({id: 'ocp-on-aws'})`, the navigation pane collapses. I cannot see the navigation selection in the navigation pane.

Filed Insights issue:
https://projects.engineering.redhat.com/browse/RHIPLAT2-756

**Comment by dchorvat1** [comment]
@dlabrecq The links for details pages now work correctly, however, navigation still shows "Overview" when clicking "Add sources" button, and "Catalog Sources" when I click "Cost Management Sources" in the navigation

**Comment by dlabrecq** [comment]
This is a known issue. Insights owns/controls that navigation pane, so we've created the Insights issue below.

https://projects.engineering.redhat.com/browse/RHIPLAT2-762
