### ISSUE TITLE
Sources page warnings in the browser console

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#763]
While testing the latest PatternFly packages, I noticed the sources page is generating the following messages in the browser console. And the expansion toggles no longer work.

I don't believe this is a PatternFly issue because we're passing the `t` object instead of using `translate` from `react-i18next`. The `deleteAction` object is also our code.

If you feel this is a table component problem, please file an issue with PatternFly so we can fix this ASAP.

<img width="1281" alt="Screen Shot 2019-04-16 at 9 18 44 PM" src="https://user-images.githubusercontent.com/17481322/56254186-c8fa1a80-608d-11e9-9f1d-0882225370a3.png">

**Comment by boaz0** [comment]
Hi Dan,

Although I see the warning messages, everything works fine to me.

Anyway, I will push a change to fix these warnings so you can check again if it fixes the problem.

Thanks.

**Comment by dlabrecq** [comment]
I saw the breakage with the new PatternFly packages. You can try that out here: https://github.com/project-koku/koku-ui/pull/758
