### ISSUE TITLE
Sources: Empty screen text edits

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#764]
**Describe the bug**
Text edits for the 'no sources configured' screen to provide more informative yet concise text.

**Expected behavior**
_In the grey space, please update the heading to:_

No sources are configured

_In the grey space, update the explanation to:_

To use Cost Management, you must connect the application to at least one source.

**Screenshots**
Screen 3 in https://redhat.invisionapp.com/share/XJR3A3996KR#/screens/356380301/comments/113855640 

**Additional context**
This wording is better for future translation, and provides more context to users.

Another option is to provide more info on this screen, like what Cloud Meter has done in screen #2 here: https://redhat.invisionapp.com/share/UFI078IZVAW#/screens/296433291. Thoughts?

**Comment by boaz0** [comment]
Thanks @dayleparker 
I will be working on it in the next weeks.

**Comment by dayleparker** [comment]
Thanks @boaz0. If this hasn't been done yet, can we improve this text (from the above comment) a little, so we can provide the user with more useful info about Cost Management's purpose:

_Old text suggestion (from above)_ :
"To use Cost Management, you must connect the application to at least one source."

_New text_ :

To use Cost Management to manage your cloud costs, you must connect the application to at least one data source. 

Add an AWS account or an OpenShift Container Platform cluster to get started.

**Comment by dayleparker** [comment]
Thanks for making this update, @boaz0! :)
