### ISSUE TITLE
Price List: API update 

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#765]
## User Story
As user, I want to have a friendly name to the metrics with the better units (GB-months/core-hours).

## Impacts
UI

## Role
User

## Assumptions
- [x] https://github.com/project-koku/koku/pull/817 is merged

## UI Details
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/352926696

## Acceptance Criteria

- [x] Under metric use the display name and not the name with the first part of the unit
- [x] Rename `usage start` to `Applied usage range` and calculate its value by getting it from `usage_start` and `usage_end`
- [x] Rename `usage end` to `Applied usage date range`which is given in the second part of the unit

**Comment by dccurtis** [comment]
@boaz0 We can iterate on the `display_name` after you get it integrated in the UI.  Will probably need some guidance from @nlcwong on this.

**Comment by boaz0** [comment]
@dccurtis no problem.

**Comment by nlcwong** [comment]
@dccurtis guidance on what now?
