### ISSUE TITLE
Details table items cropped out of browser 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#767]
**Describe the bug**
When we resize the browser at details pages, the table items resize to some extent, but eventually they get out of the browser with no possibility to reach the missing elements.

**To Reproduce**
1. Go to any of the details pages
2. Resize browser horizontally
3. See error

**Expected behavior**
Table items aligned with the rest of the table, a way to reach all the elements

**Screenshots**
![Screenshot from 2019-04-17 15-02-09](https://user-images.githubusercontent.com/46324552/56289992-7dde1700-6122-11e9-8188-193ef37312b9.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Additional context**
This is similar to #753, however, unlike the modal, the table items are not fixed size

**Comment by dlabrecq** [comment]
It appears that the table remains a minimum size, until the window reaches a certain point. Then, the table changes its layout (becomes responsive) for a very small window. However, if you resize larger again, the table fixes itself. 

Filed an issue with PatternFly:
https://github.com/patternfly/patternfly-react/issues/1790

**Comment by dlabrecq** [comment]
Fixed by https://github.com/project-koku/koku-ui/issues/770
