### ISSUE TITLE
Sources: Add a source > Obtain login (OCP)

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#789]
**Describe the bug**
Edits to the screen where you get your OCP login to adhere to brand standards for OpenShift, etc.

**Expected behavior**
Revised text:

Obtain your login credentials

To gather OpenShift Container Platform metering data, Cost Management requires the login token for the Operator Metering service account.

- Log in to the OpenShift Container Platform cluster with an account that has access to the Operator Metering namespace.
- To obtain your login token, run:
[command...]
- To maintain security, store the token file on a file system with limited access.

Also, please add a popover with the text shown in the linked screenshot.

**Screenshots**
https://redhat.invisionapp.com/share/XJR3A3996KR#/screens/356616236

**Comment by boaz0** [comment]
@dayleparker where the "learn more" link in the popover should take the user?
