### ISSUE TITLE
Left hand nav shows overview instead of details after clicking 'All projects' button

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#808]
**Describe the bug**
Left hand nav shows overview instead of details after clicking 'All projects' button

**To Reproduce**
1. Go to 'Overview'
2. Click on 'All Projects'
3. See left hand nav

Left hand nav should update to respected details page

**Screenshots**
![Screenshot from 2019-04-29 11-17-20](https://user-images.githubusercontent.com/18352403/56890476-764b3600-6a71-11e9-984c-0da56405ca56.png)
![Screenshot from 2019-04-29 11-25-32](https://user-images.githubusercontent.com/18352403/56890507-87944280-6a71-11e9-8a1b-25f158018e94.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD with demo user
This happens on all overview cards openshift on cloud/openshift/cloud
Try 'All projects', 'All clusters', 'All services', 'All regions' and 'All accounts'

**Comment by dlabrecq** [comment]
This is a duplicated of https://github.com/project-koku/koku-ui/issues/756
