### ISSUE TITLE
Painful experience trying to hid/show graph lines using legend buttons

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#810]
**Describe the bug**
Painful experience trying to hid/show graph lines using legend buttons

**To Reproduce**
1. Go to 'Overview'
2. Click on legends lines to show/hid graph lines

This legend buttons are easy to miss click especially on high res screens.

**Expected behavior**
These buttons need to be larger, even if its just a case of adding a larger click-able box

**Screenshots**
![Screenshot from 2019-04-29 11-34-51](https://user-images.githubusercontent.com/18352403/56891146-69c7dd00-6a73-11e9-8a23-82af5d56224f.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD

**Comment by dlabrecq** [comment]
The legend size is defined by the PatternFly 4 chart legend component. However, it should be noted that PF does not support hide/show. This is something we added and not likely that we will change the legend size.

**Comment by dlabrecq** [comment]
The patternfly.org site says only this for chart legends:

`Interactive Legend (optional): Clicking on a series in the legend should toggle the visibility of the series in the chart. `

Note that our high fidelity mocks use a line Vs a square legend symbol. Using a square symbol would increase the clickable area slightly.

See:
https://www.patternfly.org/pattern-library/data-visualization/line-chart/#design
https://www.patternfly.org/pattern-library/data-visualization/bullet-chart/#design

**Comment by nlcwong** [comment]
@lcouzens if we make the text clickable, would that be efficient?
