### ISSUE TITLE
Openshift volume card missing comparison unit

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#811]
**Describe the bug**
Openshift volume card missing comparison unit

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Openshift'
3. Scroll down to 'Volume' card
4. See comparison '()' missing GB-Month

**Expected behavior**
Should show unit

**Screenshots**
![Screenshot from 2019-04-29 12-05-53](https://user-images.githubusercontent.com/18352403/56892420-7bab7f00-6a77-11e9-80cc-fff7e56b85cc.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD with demo user

**Comment by dlabrecq** [comment]
This is a back end issue. The unit was there unit we blew away our CI data. Please file an issue with the koku database

**Comment by dlabrecq** [comment]
The UI is functioning as expected. If there is no unit provided, we don't hard code one. Don't know if the units should be GB-mo, GB-hours, core-hours, etc.

**Comment by dlabrecq** [comment]
Moved this to koku https://github.com/project-koku/koku/issues/838
