### ISSUE TITLE
Empty state 'Add sources' button does not navigate to sources page

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#812]
**Describe the bug**
Empty state 'Add sources' button does not navigate to sources page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Overview' on user without providers
2. Click on 'Add sources'
3. Add source modal appears

**Expected behaviour**
Should redirect to sources page

**Screenshots**
![Screenshot from 2019-04-29 13-28-58](https://user-images.githubusercontent.com/18352403/56896162-ef9f5480-6a82-11e9-9a3f-000693092acb.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD

**Comment by dlabrecq** [comment]
It appears that you're testing with old code?

The "Add Sources" button was intended to launch the providers modal. It was never meant to navigate to the sources page.

That said, this has been changed to show a "View all sources" link which does navigate to the sources page.

See https://github.com/project-koku/koku-ui/issues/801
