### ISSUE TITLE
Filtering by type on sources page does not work 

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#814]
**Describe the bug**
Filtering by type on sources page does not work 

**To Reproduce**
1. Go to 'Add sources'
2. Switch filter to 'Type'
3. Apply any text filter
4. Page shows `We encountered an unexpected error.`

**Expected behavior**
Should show filtered types.

**Screenshots**
![Screenshot from 2019-04-29 13-50-15](https://user-images.githubusercontent.com/18352403/56897198-c59b6180-6a85-11e9-9c6d-18c6b4482b5c.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD

**Comment by dlabrecq** [comment]
This is a duplicated of https://github.com/project-koku/koku-ui/issues/649
