### ISSUE TITLE
Processing data empty state never changes

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#818]
**Describe the bug**
Processing data empty state never changes

**To Reproduce**
1. Go to 'Openshift on cloud details'
2. Group cost by 'Tag key: 5dc_key'
3. See empty state

**Expected behavior**
Should time out eventually

**Screenshots**
![Screenshot from 2019-04-29 15-40-39](https://user-images.githubusercontent.com/18352403/56908458-3babc280-6a9e-11e9-9965-e3679e5f7967.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD also the same on CI

**Comment by dlabrecq** [comment]
This looks like a koku issue. It doesn't matter what tag is applied. They all fail to return a value.

**Comment by dlabrecq** [comment]
The API used to group_by tag key is not returning a value.

Created the following issue with koku. 
https://github.com/project-koku/koku/issues/840
