### ISSUE TITLE
Replace custom CopyClipboard with PatternFly 4 component. 

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#821]
**Describe the bug**
Replace our custom CopyClipboard component with PatternFly 4's ClipboardCopy component. 

http://patternfly-react.surge.sh/patternfly-4/components/clipboardcopy/

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Add sources'
3. Click on 'Add source'
4. Choose 'RH OCP' and click continue
5. See the CopyClipboard component

**Expected behavior**
Update pages (e.g., in the onboarding modal) to use the ClipboardCopy from PatternFly-react.

**Screenshots**
![Screen Shot 2019-04-29 at 3 35 16 PM](https://user-images.githubusercontent.com/17481322/56921686-685adc80-6a94-11e9-9b95-3d7ca9e2fec6.png)

**Comment by boaz0** [comment]
If you don't mind I will work on it although I am not sure I will be able in this sprint but probably the one after.

**Comment by dlabrecq** [comment]
That's fine. Not needed right away. Just wanted to create an issue -- similar to replacing the PF3 toolbar, eventually.

**Comment by boaz0** [comment]
Got it
