### ISSUE TITLE
Sources: missing localizations

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#823]
**Describe the bug**
There are hard-coded strings in the sources page.

**To Reproduce**
1. Go to the 'sources' page
2. See error

**Expected behavior**
All strings, including aria labels, need to be added to our en.json file for localization.

**Screenshots**
sourceSettings/filterToolbar.tsx
![Screen Shot 2019-04-29 at 4 28 44 PM](https://user-images.githubusercontent.com/17481322/56924832-e078d080-6a9b-11e9-850a-659c084f0be2.png)

sourceSettings/sourceSettings.tsx
![Screen Shot 2019-04-29 at 4 29 17 PM](https://user-images.githubusercontent.com/17481322/56924881-fbe3db80-6a9b-11e9-8c5c-b5aac0dad82a.png)

**Comment by boaz0** [comment]
I'm probably missing something but I can't find where I missed localization in the above pictures.

**Comment by dlabrecq** [comment]
It's the English strings (e.g., Add Source), and aria labels (e.g., select property for use for filtering).
