### ISSUE TITLE
AWS overview network and database card values don't add up

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#846]
**Describe the bug**
Data for "top services" tab in network and database cards in AWS overview seem incorrect

**To Reproduce**
1. Go to AWS overview
2. See network/database services

**Expected behavior**
Values adding up to the totals

**Screenshots**
![Screenshot from 2019-05-02 11-43-50](https://user-images.githubusercontent.com/46324552/57067785-46e63480-6cd0-11e9-81d1-7f84460677fe.png)
![Screenshot from 2019-05-02 11-43-54](https://user-images.githubusercontent.com/46324552/57067787-49488e80-6cd0-11e9-979c-4a9b46d5a310.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Additional context**
tested on CI beta

**Comment by dlabrecq** [comment]
Using the wild card with `group_by[service]=*`, appears to take precedence over 

`filter[service]=AmazonRDS,AmazonDynamoDB,AmazonElastiCache,AmazonNeptune,AmazonRedshift,AmazonDocumentDB`

Replacing the group_by's wild card with the filter string seems to work, but only for the service tab. 

The other tabs appear to still need the wild card (e.g., `group_by[accounts]=*` and `group_by[regions]=*`) along with the filter for the costs to add up correctly.

**Comment by dlabrecq** [comment]
It may be possible to back out our special-case code after the koku issue below has been addressed?

https://github.com/project-koku/koku/issues/848
