### ISSUE TITLE
Drop down goes behind tabs in expanded row

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#852]
**Describe the bug**
Drop down goes behind tabs in expanded row

**To Reproduce**
1. Go to 'Cloud Details'
2. Expand the first row
3. Click on group_by dropdown
4. See Dropdown text goes behind row tabs

**Expected behavior**
Dropdown should be in the forground

**Screenshots**
![Screenshot from 2019-05-03 13-23-59](https://user-images.githubusercontent.com/18352403/57137307-669c5c00-6da7-11e9-8d36-d05102ba6a5d.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD with demo user

**Comment by dlabrecq** [comment]
This is a known PatternFly issue.

https://github.com/patternfly/patternfly-react/issues/1636
