### ISSUE TITLE
Bad text fomatting on OCP add source modal

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#869]
**Describe the bug**
Bad text fomatting on add source modal

**To Reproduce**
1. Go to 'sources'
2. Click on 'add a source'
3. Select ocp and click next
4. See formatted bullet points

**Expected behavior**
There should be even spaces between text plus bullet points should be tabbed in

**Screenshots**
![Screenshot from 2019-05-14 10-48-16](https://user-images.githubusercontent.com/18352403/57688818-420d7300-7636-11e9-9cfa-4ce452d40cfa.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser FireFox
 - Version 66

**Comment by boaz0** [comment]
Thanks - I will be checking this out.
BTW, @lcouzens can you confirm this problem also on Chrome?
