### ISSUE TITLE
Incorrect button text in "Add source" modal

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#870]
**Describe the bug**
Incorrect text of the onboarding modal buttons (probably a typo in the formatted strings)

**To Reproduce**
1. Go to sources
2. Click on Add source
3. See error

**Expected behavior**
Correct button texts

**Screenshots**
![Screenshot from 2019-05-15 14-49-26](https://user-images.githubusercontent.com/46324552/57777549-75c5c700-7722-11e9-8cc8-d204f8aa1274.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Additional context**
tested on CI beta

**Comment by boaz0** [comment]
That's odd. I will fix it. Thanks.
