### ISSUE TITLE
Delete source dialog confirmation button out of dialog bounds

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#871]
**Describe the bug**
When we are deleting a source with a long name, the confirmation button reaches over the borders of the dialog

**To Reproduce**
1. Go to sources
2. Try to delete a source with a long name 
3. See error

**Expected behavior**
Button should not go over the bounds of the dialog

**Screenshots**
![Screenshot from 2019-05-15 14-48-15](https://user-images.githubusercontent.com/46324552/57778000-6f841a80-7723-11e9-9648-cda8779306cd.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome/Firefox

**Additional context**
tested on CI beta

**Comment by boaz0** [comment]
Good catch. I will work on that.
