### ISSUE TITLE
Error message for unauthorized / not entitled

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#885]
**Describe the bug**
The message when the user is not entitled does not provide the right information.

**To Reproduce**
Log in with a user that is not an admin and is not entitled.
Go to any application

**Expected behavior**
The message should be relevant and explain what is happening.

**Screenshots**

![image](https://user-images.githubusercontent.com/7500590/58572119-5ad37680-823b-11e9-8378-6237b5e55f43.png)

**Comment by dlabrecq** [comment]
In this scenario, the UI appears to receive a `403 Forbidden` message.

![Screen Shot 2019-05-30 at 9.49.55 AM.png](https://images.zenhubusercontent.com/5b47705f01db7d22de6439cd/f6896a27-770b-48aa-b92d-cc7a0f53db3b)

@nlcwong What should the message say?

**Comment by dlabrecq** [comment]
It would be helpful to see the network error in the browser's console. I suspect the UI received a `401` error?

@nlcwong What should the message say?

**Comment by nlcwong** [comment]
I will work on a 403 error state design (this is also part of my cross-app ux work that I've assigned myself).

**Comment by nlcwong** [comment]
@chargio I was talking to platform UX about entitlements and this is their solution (apparently it was implemented for Insights & Cloud Services for RHEL Hosts (CSfRH)): https://marvelapp.com/c58f6c0

It sounded like platform has a way of intercepting the links and popping up the box to let the user know what is what.  I think we should start a conversation with Platform on how this can apply to Cost as well (for instance, can they have special messages for the different entitlement packages and make links to the various product pages so they can purchase the SKU, etc.)?

**Comment by nlcwong** [comment]
@dlabrecq  As for the RBAC issue of no-authorization, we can use the following empty state message for that: https://marvelapp.com/1hcda086

**Comment by dlabrecq** [comment]
Yes, that would be fine

**Comment by lcouzens** [comment]
As far as I can see this is still not updated correctly based from entitlements. I was testing against QA with a user that was not entitled.

![Screenshot from 2020-02-07 09-46-18.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/f6132f8f-6cae-4245-b479-32d009495e0d)

**Comment by dlabrecq** [comment]
We're looking for a 401 Unauthorized error status response code. That's the only way to see the unique message.

Perhaps you encountered a different error code in the browser console?

**Comment by lcouzens** [comment]
Verified
