### ISSUE TITLE
Graph tooltips out of graph bounds

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#898]
**Describe the bug**
Graph tooltips reach out of graph bounds and get behind/block other parts of the UI

**To Reproduce**
1. Go to any page with graphs (OpenShift overview displayed on screenshots) 
2. Mouseover on graph 
3. See that near the edges of the graph, tooltip reaches out of graph

**Expected behavior**
Tooltip should display correctly

**Screenshots**
![Screenshot from 2019-06-07 11-10-36](https://user-images.githubusercontent.com/46324552/59094077-a9f16980-8915-11e9-8b3e-2911c1efdf76.png)
![Screenshot from 2019-06-07 11-10-39](https://user-images.githubusercontent.com/46324552/59094079-ac53c380-8915-11e9-8d01-7199f9a4d996.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 73

**Additional context**
Tested on CI beta

**Comment by dlabrecq** [comment]
This is partly a PatternFly 4 bug and partly a Victory issue.

I've fixed an issue in PatternFly, which keeps the tooltip within the boundary of the chart when showing multiple data points. See https://github.com/patternfly/patternfly-react/pull/2324

However, there is a Victory issue with single data points. I filed the issue with Victory below.
`https://github.com/FormidableLabs/victory/issues/1336`
