### ISSUE TITLE
Sources: Wrong date in `Date added` column

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#906]
**Describe the bug**
Source Settings is showing the wrong date under `Date added`.

**To Reproduce**
1. Go to Source settings page:
 a. Click on Settings in the navigation bar on the left to expand it
 b. Choose Cost management
2. Create a new source:
 a. Click on the "add source" button
 b. Follow the instructions (NOTE: it's easier to create a new OCP source than AWS)
3. Find the source in the table and notice that the `Date added` is not set to "now" or "X seconds/minutes ago"

**Expected behavior**
To see the real time when this source was created: "1 second ago"

**Additional context**
An [issue](https://github.com/project-koku/koku/issues/912) was opened the koku repository since the creation date is not specified in API.
Waiting on [this PR](https://github.com/project-koku/koku/pull/913) to be merged in order to start working on it on the client side.

**Comment by adberglund** [comment]
The current provider API has a `created_timestamp` field which we should use. I believe what is being used is `{"customer": {"date_created"}`
