### ISSUE TITLE
Sources: Adding a new source causes API a DDoS attack on backend

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#907]
**Describe the bug**
I noticed today while playing with onboarding that after adding a new source, the UI sends many requests to `api/v1/proviers?type=OCP` and ``api/v1/proviers?type=AWS`. It does that non-stop unless I'm refreshing my page.

**To Reproduce**
1. From the `overview` page expand `Settings`
2. Click on `Cost Management Sources`
3. In the `Settings` page click on `Add source`
4. Open Dev Tools (on Firefox it is done by clicking on F12) and go to the Network tab
5. Add a new source (follow the instruction. Note: It's easier to add a new OCP source than AWS)
6. After the source was added, notice that there are many requests sent to the backend and they are not stopping.

**Expected behavior**
No DDoS attack. I assume there should be only 1-2 call(s) to the backend.

**Screenshots**
![1](https://user-images.githubusercontent.com/2453279/60021840-5f087d80-969b-11e9-84e9-c6d903a32302.png)

**Comment by boaz0** [comment]
@dlabrecq at first look it seems like a typo in this condition:

```
(onboardingStatus === FetchStatus.complete && onboardingErrors)) &&
```
instead of

```
(onboardingStatus === FetchStatus.complete && **!**onboardingErrors)) &&
```

Although I am trying to figure out why we should fetch OCP & AWS providers when onboarding status is complete and there are errors?

**Comment by dlabrecq** [comment]
I don't see the `**!**onboardingErrors` code in the source?

The onboardingErrors check is to ensure we don't make another request. For example, whenever the page is updated. (An update happens even whenever a request returns, regardless of its state.) If we already made a request and there is an error, we don't want to make another request.
