### ISSUE TITLE
OCP details page crashes after expanding row item

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#915]
**Describe the bug**
Page disappears and becomes unresponsive after expanding a row item in OCP details.
TypeError shows up in the browser console (in the screenshot).

**To Reproduce**
1. Go to OCP details
2. Expand a row item
3. See error

**Expected behavior**
Row expands correctly

**Screenshots**
![Screenshot from 2019-07-10 13-04-01](https://user-images.githubusercontent.com/46324552/60964599-029c9380-a314-11e9-9ece-c1f616ef11bb.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome 
 - Version 75

**Additional context**
First seen on CI beta, similar behavior on PROD

**Comment by dchorvat1** [comment]
this is probably happening because of the `"limit": null` value returned from the API
```
"total": {
            "usage": {
                "value": 0.366769,
                "units": "Core-Hours"
            },
            "request": {
                "value": 1.61,
                "units": "Core-Hours"
            },
            "limit": null,
            "capacity": {
                "value": 3542.0,
                "units": "Core-Hours"
            },
            "infrastructure_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "cost": {
                "value": 0.0,
                "units": "USD"
            }
        }
```

**Comment by dlabrecq** [comment]
This is a known issue with koku.
See https://github.com/project-koku/koku/issues/927
