### ISSUE TITLE
Sources: Operator metering login screen --> reporting-operator

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#916]
**Describe the bug**
Wherever we talk about the 'Operator Metering' or 'metering-operator' service 
account in this step of adding OCP sources, it should be the reporting-operator service account.

We also need to update the command in this screen:

# oc serviceaccounts get-token reporting-operator > ocp_usage_token

**Screenshot**

<img width="1117" alt="Screenshot 2019-07-11 at 17 18 08" src="https://user-images.githubusercontent.com/20275317/61063254-f1c94c00-a3ff-11e9-86dd-eff2aeb85cf0.png">

**For more info**

See the Bluejeans recordings at the end of the Cost onboarding Google doc.
Check out the video from Fri 6/14/19 at around 56:00.

@adberglund, can you please verify that I have these details/names (ie. reporting-operator) right?

**Comment by adberglund** [comment]
@boaz0 @dayleparker That is correct. Previously we were using the `metering-operator` service account but we moved to use the `reporting-operator` service account.

**Comment by boaz0** [comment]
Cool, thanks a lot for approving this @adberglund

**Comment by boaz0** [comment]
merging in 1..2..3..:bomb:
