### ISSUE TITLE
Sources > Add OCP source - contrab typo

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#923]
**Describe the bug**

Just a couple text edits please:

* The first command just needs "contrab" fixed to "crontab" --> should be 
crontab -u <username> -e

* The instruction that ends with "every 45 minutes" should have a : at the end of the line, like:

Create a crontab entry to run the Usage Collector every 45 minutes:

For more info, see:

![image](https://user-images.githubusercontent.com/20275317/61288917-76351980-a7c8-11e9-8181-2e92c0b3aa9e.png)

**Comment by boaz0** [comment]
Thanks @dayleparker
