### ISSUE TITLE
PF4 chart colors

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#928]
PatternFly 4 charts are now themed with colors from pf-core. For consistency, we should consider removing the custom colors we created (for charts and legends) in favor of the themed colors provided by PatternFly.

**Comment by boaz0** [comment]
//cc @aagarw10

**Comment by dlabrecq** [comment]
Note that we will still need to customize the `colorScale` used by the chart component. That is, the colors representing the current and previous months. However, those colors should be pulled from react-tokens. 

We want to duplicate the same gray theme color pallet used by the PF4 chart. The green colors should come from the PF4 chart's green theme color pallet. And the `colorScale` should be applied in the same order.
