### ISSUE TITLE
Filter component nuances (cost-models and sources)

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#945]
**Describe the bug**
There are a few small differences between the filter component in cost models details and source settings pages.

![image](https://user-images.githubusercontent.com/2453279/63021748-f1fab280-bea9-11e9-8585-f6cea6f665eb.png)

//cc @nlcwong 

**To Reproduce**
1. Go to `Cost model details`
2. Then go to expand `Settings` and click `Cost management sources`

**Expected behavior**
Unified style for both filters

**Screenshots**
![image](https://user-images.githubusercontent.com/2453279/63021748-f1fab280-bea9-11e9-8585-f6cea6f665eb.png)

**Comment by dlabrecq** [comment]
After speaking with @nlcwong, we would like to update the toolbar for the Cost management Sources page to be in sync with the Cost Model page.

The design is here:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#attribute-value-textbox-filters

![Screen Shot 2019-08-14 at 10 19 59 AM](https://user-images.githubusercontent.com/17481322/63028615-273cdb80-be7d-11e9-9694-4288cd3d5a74.png)

**Comment by dlabrecq** [comment]
Closing since sources is currently being ported
