### ISSUE TITLE
Cost model filtering shows results for non-matching strings

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#953]
**Describe the bug**
When filtering by name in cost model details page, the filter shows any cost model with name consisting of each of the letters in the string we filter by.

**To Reproduce**
1. Go to cost model details
2. Apply nonsense filters that contain only letters from a desired cost model
3. See error

**Expected behavior**
UI should not return non-matching cost models

**Screenshots**
![Screenshot from 2019-08-21 14-40-17](https://user-images.githubusercontent.com/46324552/63432966-81f8a900-c422-11e9-80d2-3985b0901400.png)

**Desktop (please complete the following information):**
 - OS: rhel
 - Browser chrome
 - Version 75

**Additional context**
Tested on CI beta

**Comment by boaz0** [comment]
@dchorvat1 thanks for filling this issue. After taking a look at the code it looks like a bug in the back-end. I opened an issue in project-koku/koku and will push a fix as soon as possible.

**Comment by boaz0** [comment]
@dchorvat1 - :warning: a fix was [merged](https://github.com/project-koku/koku/pull/1030)

**Comment by boaz0** [comment]
ping @dchorvat1 can you confirm this bug was fixed?

**Comment by dchorvat1** [comment]
Verified on CI, the api now returns correct cost models filtered by name

**Comment by boaz0** [comment]
![Yeeeeeeeeeeay!!!](https://media.giphy.com/media/aY1VtVR4g8kMg/giphy.gif)
