### ISSUE TITLE
Cost model empty state shows add a source modal

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#955]
**Describe the bug**
When we try to add a new cost modal from empty state, add source modal opens.

**To Reproduce**
1. Go to cost model details with no cost models in the db
2. Click on "Create a cost model"
3. See error

**Expected behavior**
Cost model wizard

**Screenshots**
![Screenshot from 2019-08-22 12-12-19](https://user-images.githubusercontent.com/46324552/63506770-7b2b6e00-c4d6-11e9-926f-0bd731680c82.png)

**Additional context**
Tested on CI beta

**Comment by boaz0** [comment]
Thank you @dchorvat1 - I think I know what's the problem.
