### ISSUE TITLE
Cost Details Pie Charts don't color correctly

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku-ui#96]
**Describe the bug**
Cost details pie chart isn't following the `colorScale` as the entire pie is one color.

**To Reproduce**
1. Go to the Cost details page by clicking on the "Cost Details" tab
2. Click on a List Item *>*
3. Scroll down to see the pie chart

**Expected behavior**
Pie Chart should have various colors that match the legend items

**Screenshots**

<img width="925" alt="image" src="https://user-images.githubusercontent.com/29379759/44936819-3a29cf00-ad44-11e8-862e-b72ae81c378e.png">

**Comment by boaz1337** [comment]
It has to do with `VictoryGroup`, I believe.

**Comment by boaz1337** [comment]
I opened an issue [here](https://github.com/FormidableLabs/victory/issues/1109) and opened a workaround [here](https://github.com/project-koku/koku-ui/pull/99)
