### ISSUE TITLE
Upgrade react to ^16.8.0

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#968]
The React version we are using is at least 16.7.0. I would suggest we catch up with the current version (as React now in version 16.9.0).

Looking at packages.json I don't see where we are specifying react but I guess `react` is a dependency in one of them and that's why we get old version of react.

**Comment by dlabrecq** [comment]
We had updated React to 16.8.0 and it caused issues with Insights navigation -- react router also had to be updated to us this version. Thus, it was backed out. 

See https://github.com/project-koku/koku-ui/pull/932

Unless there is a specific reason to update, I suggest we stick with what ever version Insights is working with?

FYI, I believe Insights is using ^16.4.2 and the PatternFly dependency is ^16.4.0.

**Comment by boaz0** [comment]
Reopening - since I've already seen some insights projects using it. I thought maybe we can give it another try.

What do you think @dlabrecq

**Comment by dlabrecq** [comment]
Sure, we can try again. Just need to ensure we don't have any navigation issues with the router.

**Comment by dlabrecq** [comment]
Looking at the Insights starter app and it's still using ^16.4.2.

"react": "^16.4.2",
"react-dom": "^16.4.2",
"react-redux": "^5.0.7",
"react-router-dom": "^4.2.2",

**Comment by boaz0** [comment]
[frontend component](https://github.com/RedHatInsights/frontend-components/blob/master/package.json):
```
        "react-dom": "^16.10.2",
        "react-redux": "^5.0.7",
        "react-router-dom": "^4.2.2",
```

[advisor](https://github.com/RedHatInsights/insights-advisor-frontend/blob/master/package.json):
```
    "react-dom": "16.12.0",
    "react-redux": "5.1.0",
    "react-router-dom": "5.1.2",
```

[inventory](https://github.com/RedHatInsights/insights-inventory-frontend/blob/master/package.json):
```
    "react-dom": "^16.8.6",
    "react-redux": "^5.1.1",
    "react-router-dom": "4.3.1",
```

[sources](https://github.com/RedHatInsights/sources-ui/blob/master/package.json):
```
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
```

**Comment by boaz0** [comment]
So it looks like react 16.8 works well with react-router-dom 4.x

**Comment by dlabrecq** [comment]
It looks like our package.json (i.e., `"react-dom": "^16.6.3"`) installs "16.8.6".

**Comment by boaz0** [comment]
OMG :scream: you're right! how that happened!

I guess this issue was resolved and can be closed!

Thanks.
