### ISSUE TITLE
Security Alert

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#976]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2453279/64623821-4c782780-d3f2-11e9-8601-2d6ac8d40ac2.png)

**To Reproduce**
1. Go to https://github.com/project-koku/koku-ui/network/alerts
2. See error

**Expected behavior**
No security alerts!

**Comment by dlabrecq** [comment]
The PF issue https://github.com/patternfly/patternfly-react/issues/2906 has been completed / merged. Need to update the PF packages and re-evaluate.
