### ISSUE TITLE
"View all price list" in ocp details results in page crash

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#987]
**Describe the bug**
When we try to display the price list of a cluster from kebab menu in ocp details, page crashes and black page gets displayed. 
Following error got displayed in browser console, all the API requests were successful.

**To Reproduce**
1. Go to OCP details
2. Click on "View all price list" in kebab menu
3. See error

**Expected behavior**
Price list gets shown without errors

**Screenshots**
![Screenshot from 2019-09-13 10-09-59](https://user-images.githubusercontent.com/46324552/64847506-7490a200-d60f-11e9-8f66-cf0368bf49e9.png)

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 75

**Additional context**
Tested on CI beta

**Comment by boaz0** [comment]
@dchorvat1 I can't reproduce it because there is no OCP data right now.
But I think it's related to the rates api changes.

Can you provide me an environment where I can run my UI changes?
Thanks.

**Comment by dchorvat1** [comment]
@boaz0 I uploaded some test data to my account, you should see the data and be able to reproduce it there on CI
